[MIG] stock_picking_supplier_ref: Migration to 14.0
OCA/stock-logistics-workflow pull request #1005
Opened 2022-05-23 07:18 UTC by Reyes4711

Standard migration to 14.0

2022-05-31 21:45 UTC, flotho requested changes
Hi,

Thanks for your work.
I think that small changes could easily improve your contribution.

Regards

2022-05-31 21:45 UTC, flotho commented on stock_picking_supplier_ref/readme/DESCRIPTION.rst
> +This module adds the field supplier reference in pickings.
Which reference are we talking about

2022-05-31 21:45 UTC, flotho commented on stock_picking_supplier_ref/models/stock_picking.py
> +    reference = fields.Char(string="Supplier Reference")
IMHO reference is too more "open" definition. I mean, are we talking about the reference of the supplier_reference available in the PO, are we talking about the picking reference of the supplier ?
I would recommend to make some small changes to better specify the use case.

2022-08-04 11:26 UTC, Reyes4711-S73 commented
@flotho In this PR we are doing only the standard migration of this module, not doing some improvements. To do this, we need to create another PR with all the improvements to do.
Besides, changing the name of this field maybe do some problems with people are using this module. In the PR of improvements, you must do a script which does the change of the name of field to the new name.

2022-09-27 06:03 UTC, rousseldenis commented
> @flotho In this PR we are doing only the standard migration of this module, not doing some improvements. To do this, we need to create another PR with all the improvements to do. Besides, changing the name of this field maybe do some problems with people are using this module. In the PR of improvements, you must do a script which does the change of the name of field to the new name.

@Reyes4711-S73 You can do for sure changes in this PR. For reference name, I agree with @flotho. To support existing installations, you should provide a migration script.

2022-11-02 11:19 UTC, Reyes4711-S73 commented
@rousseldenis @flotho In a few days I will do this changes

2022-11-11 07:34 UTC, Reyes4711-S73 commented
@rousseldenis and @flotho Added suggested improvements. If is all correct, could you merge this PR?

2022-11-24 08:28 UTC, rousseldenis approved these changes

2022-11-24 08:28 UTC, rousseldenis commented
/ocabot migration stock_picking_supplier_ref

2023-01-23 07:54 UTC, hildickethan-S73 approved these changes

2023-01-23 08:03 UTC, Reyes4711-S73 commented
@rousseldenis Could you merge this PR?

2023-01-23 08:04 UTC, rousseldenis commented
@flotho Could you update your review?

@Reyes4711-S73 Could you squash your two last commits (as the add of openupgradelib is linked to the improvement)?

2023-01-24 20:08 UTC, flotho approved these changes
LGTM, thanks for the update

2023-01-25 07:05 UTC, Reyes4711-S73 commented
@rousseldenis Squashed. Please, could you merge this PR now?

2023-01-25 12:32 UTC, flotho approved these changes

2023-02-13 08:38 UTC, ferran-S73 approved these changes

2023-02-13 08:40 UTC, rousseldenis commented
/ocabot merge patch

2023-02-13 08:53 UTC, merged