[15.0] [MIG] stock_move_assign_picking_hook
OCA/stock-logistics-workflow pull request #1035
Opened 2022-07-08 09:23 UTC by JasminSForgeFlow

Standard Migration

@ForgeFlow

2022-07-08 09:45 UTC, MiquelRForgeFlow approved these changes

2022-07-08 09:45 UTC, MiquelRForgeFlow commented on stock_move_assign_picking_hook/i18n/stock_move_assign_picking_hook.pot
> +"Project-Id-Version: Odoo Server 14.0\n"
```suggestion
"Project-Id-Version: Odoo Server 15.0\n"
```

2022-07-08 10:53 UTC, LoisRForgeFlow requested changes
I think this is not needed anymore, in v15 there is a hook already in place. https://github.com/odoo/odoo/commit/71ef4b728ea0fd3848208f83a05915e84e862b9a

Isn't it?

2022-07-08 10:57 UTC, AaronHForgeFlow reviewed
I miss this part: https://github.com/odoo/odoo/blob/15.0/addons/stock/models/stock_move.py#L1043

2022-07-11 08:44 UTC, JasminSForgeFlow commented
Close PR because this hook cover in Odoo https://github.com/odoo/odoo/commit/71ef4b728ea0fd3848208f83a05915e84e862b9a

2022-07-11 08:44 UTC, closed without merging