[14.0][ADD] Add stock_scheduler_assignation_horizon module
OCA/stock-logistics-workflow pull request #1042
Opened 2022-07-14 10:13 UTC by JuMiSanAr

This module allows to set a time horizon that will prevent the scheduler from marking stock pickings as *ready* before the indicated number of days (horizon).

![image](https://user-images.githubusercontent.com/77412816/178959039-255a53bd-1504-4d1c-a2da-a8fe133f5362.png)

2022-07-15 07:53 UTC, simahawk requested changes

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/models/procurement_group.py
> +        domain = super(ProcurementGroup, self)._get_moves_to_assign_domain(company_id)
```suggestion
        domain = super()._get_moves_to_assign_domain(company_id)
```

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/models/__init__.py
> +# Copyright 2022 Camptocamp SA
remove headers

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/tests/__init__.py
> +from . import test_res_config_settings_common
do not import common files

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/tests/test_res_config_settings.py
> +    def setUpClass(cls):
this override is useless

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/tests/test_res_config_settings_common.py
> +        cls.settings = cls.env["res.config.settings"].create({})
move this setup to the other file and trash this

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/tests/test_res_config_settings.py
> +        self.env["procurement.group"].run_scheduler(company_id=self.company.id)
use `self.env.company`

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/tests/test_res_config_settings.py
> +        self.assertEqual(self.company.is_moves_assignation_limited, True)
here you are testing the res.config.settings relation: split this to another test

2022-07-15 07:53 UTC, simahawk commented on stock_scheduler_assignation_horizon/tests/test_res_config_settings_common.py
> +        super().setUpClass()
```suggestion
        super().setUpClass()
        cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
```

2022-07-15 07:54 UTC, simahawk commented
runboat fails like this

```
Element '<xpath expr="//field[@name='module_procurement_jit']/ancestor::div[hasclass('o_setting_box')]">' cannot be located in parent view
```

2022-07-15 07:58 UTC, simahawk commented
> runboat fails like this
> 
> ```
> Element '<xpath expr="//field[@name='module_procurement_jit']/ancestor::div[hasclass('o_setting_box')]">' cannot be located in parent view
> ```

this comes from sale_stock but you are not depending on it

2022-07-15 09:06 UTC, JuMiSanAr commented
> runboat fails like this
> 
> ```
> Element '<xpath expr="//field[@name='module_procurement_jit']/ancestor::div[hasclass('o_setting_box')]">' cannot be located in parent view
> ```

Using "warning_info > after" instead for the view override, but the layout doesn't look as neat as it did before:
![image](https://user-images.githubusercontent.com/77412816/179191430-9c64a967-054c-4d37-9498-38956cfae1fa.png)

Thoughts?

2022-07-22 08:29 UTC, simahawk commented
> > runboat fails like this
> > ```
> > Element '<xpath expr="//field[@name='module_procurement_jit']/ancestor::div[hasclass('o_setting_box')]">' cannot be located in parent view
> > ```
> 
> Using "warning_info > after" instead for the view override, but the layout doesn't look as neat as it did before: ![image](https://user-images.githubusercontent.com/77412816/179191430-9c64a967-054c-4d37-9498-38956cfae1fa.png)
> 
> Thoughts?

what about adding a new specific section?

2022-07-22 08:30 UTC, simahawk commented on stock_scheduler_assignation_horizon/models/procurement_group.py
> +            domain = expression.AND(
move this to `domain = self._get_moves_to_assign_domain_assignation_limited()`

2022-07-22 08:30 UTC, simahawk commented on stock_scheduler_assignation_horizon/readme/CONTRIBUTORS.rst
> +* Juan Miguel Sánchez Arce <juan.sanchez@camptocamp.com>
I'd Akim here ;)

2022-07-26 09:43 UTC, JuMiSanAr commented
> > > runboat fails like this
> > > ```
> > > Element '<xpath expr="//field[@name='module_procurement_jit']/ancestor::div[hasclass('o_setting_box')]">' cannot be located in parent view
> > > ```
> > 
> > 
> > Using "warning_info > after" instead for the view override, but the layout doesn't look as neat as it did before: ![image](https://user-images.githubusercontent.com/77412816/179191430-9c64a967-054c-4d37-9498-38956cfae1fa.png)
> > Thoughts?
> 
> what about adding a new specific section?

![image](https://user-images.githubusercontent.com/77412816/180976538-a4d31c85-8103-4b9f-9618-f0927e21214a.png)

2022-08-04 14:33 UTC, ivantodorovich requested changes
Note this only affects the scheduler (triggered by the cron), but you might still get automatic reservations in some other cases

On most databases picking automatic reservation will be enabled (it's the default). This affects `StockMove._trigger_assign`, that's usually called when completing manufacturing orders or receptions

There's also the `procurement_jit` module that's installed by default, and it will also attempt to reserve automatically upon SO confirmation.

I think this deserves at least a comment in the readme

2022-08-04 14:33 UTC, ivantodorovich commented on stock_scheduler_assignation_horizon/models/res_company.py
> +    moves_assignation_horizon = fields.Integer()
Might be good to add a constraint to prevent negative numbers

2022-08-04 14:33 UTC, ivantodorovich commented on stock_scheduler_assignation_horizon/views/res_config_settings_views.xml
> +        >res.config.settings.view.form.inherit.stock.logistics.workflow</field>
```suggestion
```
This name seems copy pasted from another module.
In any case, defining the name on views is useless. Odoo generates it automatically

2022-08-04 14:33 UTC, ivantodorovich commented on stock_scheduler_assignation_horizon/views/res_config_settings_views.xml
> +                    <div class="col-12 col-lg-6 o_setting_box">
We're missing the multi-company icon informing these fields are company-specific

```xml
<span class="fa fa-lg fa-building-o" title="Values set here are company-specific." aria-label="Values set here are company-specific." groups="base.group_multi_company" role="img"/>
```

2022-08-04 14:33 UTC, ivantodorovich commented on stock_scheduler_assignation_horizon/models/procurement_group.py
> +                        + relativedelta(days=company.moves_assignation_horizon),
IMO you shuold consider datetime and timezones

The date field is a datetime field

For timezones it can be tricky, because in most databases the tz field is empty for the company partner.. but still it beats a hardcoded utc IMO

Something like this maybe?

```py
        company_tz = pytz.timezone(company.partner_id.tz or "UTC")
        max_date = (
            datetime.combine(
                datetime.now(company_tz) + timedelta(days=company.moves_assignation_horizon),
                datetime.max.time(),
            )
            .astimezone(pytz.utc)
            .replace(tzinfo=None)
        )
```

2022-08-05 12:11 UTC, ivantodorovich approved these changes

2022-08-08 07:11 UTC, simahawk approved these changes
pls squash

2022-08-08 07:47 UTC, simahawk commented
/ocabot merge nobump

2022-08-08 08:05 UTC, merged