[15.0] [MIG] sale_line_returned_qty_mrp
OCA/stock-logistics-workflow pull request #1082
Opened 2022-09-02 11:33 UTC by JasminSForgeFlow

Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/stock-logistics-workflow/pull/1080

2022-09-14 21:00 UTC, JuanyDForgeflow approved these changes
Code review LGTM

2022-10-19 08:39 UTC, MiquelRForgeFlow approved these changes

2022-10-19 08:58 UTC, rousseldenis commented
/ocabot migration sale_line_returned_qty_mrp

2022-10-19 09:00 UTC, rousseldenis requested changes
Minor remark.

Moreover, should be great to add tests for uncovered cases.

2022-10-19 09:00 UTC, rousseldenis commented on sale_line_returned_qty_mrp/models/sale_order_line.py
> +        res = super(SaleOrderLine, self)._compute_qty_returned()
You can use short notation

2022-10-19 09:03 UTC, MiquelRForgeFlow commented
Should we wait https://github.com/OCA/stock-logistics-workflow/pull/1081 to be finished before merging this PR? 🤔

2022-10-19 09:21 UTC, rousseldenis commented
> Should we wait #1081 to be finished before merging this PR? thinking

Better

2023-03-20 08:51 UTC, rousseldenis approved these changes

2023-03-20 08:52 UTC, rousseldenis commented
/ocabot merge patch

2023-03-20 09:20 UTC, merged