[14.0][IMP] compute product's outgoing and incoming qty by restrict_lot_id
OCA/stock-logistics-workflow pull request #1179
Opened 2023-01-04 14:57 UTC by mt-software-de

To be able to get the outgoing qty and the incoming qty.
For a specific lot i changed the _get_domain_locations
This was the easiest way to change the move_in_domain and move_out_domain
which is used in _compute_quantities_dict https://github.com/odoo/odoo/blob/14.0/addons/stock/models/product.py#L123

2023-01-04 15:06 UTC, mt-software-de commented
@jbaudoux

2023-01-04 15:18 UTC, jbaudoux requested changes

2023-01-04 15:18 UTC, jbaudoux commented on stock_restrict_lot/models/product_product.py
> +        restrict_lot_id = self.env.context.get("restrict_lot_id")
It is lot_id in the context according to
https://github.com/odoo/odoo/blob/14.0/addons/stock/models/product.py#L121

```suggestion
        restrict_lot_id = self.env.context.get("lot_id")
```

2023-01-04 15:18 UTC, jbaudoux commented on stock_restrict_lot/tests/test_restrict_lot.py
> +        product = product.with_context(restrict_lot_id=self.lot.id)
```suggestion
        product = product.with_context(lot_id=self.lot.id)
```

2023-01-04 15:18 UTC, jbaudoux commented on stock_restrict_lot/tests/test_restrict_lot.py
> +        product = product.with_context(restrict_lot_id=lot2.id)
```suggestion
        product = product.with_context(lot_id=lot2.id)
```

2023-01-04 18:34 UTC, jbaudoux approved these changes
LGTM, thanks

2023-01-04 18:36 UTC, jbaudoux commented
@sebalix Can you review this one?

2023-03-21 11:04 UTC, sebalix approved these changes

2023-03-21 11:05 UTC, sebalix commented
@florian-dacosta are you OK with this change?

2023-04-25 11:08 UTC, mt-software-de commented
> @florian-dacosta are you OK with this change?

Any news on this?

2023-04-25 11:08 UTC, rousseldenis commented
@florian-dacosta

2023-06-23 20:19 UTC, mt-software-de commented
@sebalix @rousseldenis @jbaudoux how should we continue here?

2023-06-23 20:32 UTC, florian-dacosta reviewed
Hi @mt-software-de 
Sorry, it seems I missed the ping...multipe times!
The changes are ok for me, but it seems a bit too much to put yourself as author of the module IMO.

2023-06-23 21:04 UTC, mt-software-de commented
> Hi @mt-software-de 
> Sorry, it seems I missed the ping...multipe times!
> The changes are ok for me, but it seems a bit too much to put yourself as author of the module IMO.

Yes for sure that is to much. I will change this.

2023-06-25 20:11 UTC, mt-software-de commented
Could we now merge this one?

2023-06-26 08:21 UTC, florian-dacosta approved these changes

2023-06-26 08:50 UTC, jbaudoux commented
/ocabot merge minor

2023-06-26 09:04 UTC, merged