[16.0][ADD] stock_procurement_customer
OCA/stock-logistics-workflow pull request #1185
Opened 2023-01-09 11:13 UTC by rousseldenis

2023-01-12 15:00 UTC, lmignon requested changes

2023-01-12 15:00 UTC, lmignon commented on stock_procurement_customer/models/stock_picking.py
> +    customer_id = fields.Many2one(
@rousseldenis This field should be displayed on the picking view if the value is filled and different of the partner_id.

2023-01-13 13:07 UTC, rousseldenis commented on stock_procurement_customer/models/stock_picking.py
> +    customer_id = fields.Many2one(
@lmignon Done

2023-01-16 08:53 UTC, lmignon approved these changes
LGTM (Code + functional)

2023-01-19 11:14 UTC, adrienpeiffer approved these changes
Code review

2023-01-30 14:54 UTC, lmignon reviewed
LGTM (Code + functional)

2023-03-21 11:07 UTC, sebalix approved these changes
LG

2023-03-21 11:08 UTC, sebalix commented
@rousseldenis do you want to squash your commits before merging?

2023-03-30 13:03 UTC, jbaudoux approved these changes

2023-03-30 13:04 UTC, jbaudoux commented on stock_procurement_customer/models/stock_move.py
> +        res["customer_id"] = self.mapped("group_id").customer_id.id
```suggestion
        res["customer_id"] = self.group_id.customer_id.id
```

2023-05-22 12:15 UTC, rousseldenis commented
/ocabot merge nobump

2023-05-22 12:22 UTC, merged