[WIP][15.0][MIG]stock_lot_scrap: Migration to 15.0
OCA/stock-logistics-workflow pull request #1193
Opened 2023-01-18 08:53 UTC by bizzappdev

2023-05-21 17:49 UTC, pedrobaeza commented on stock_lot_scrap/__manifest__.py
> +    "version": "15.0.1.0.1",
```suggestion
    "version": "15.0.1.0.0",
```

2023-05-22 05:36 UTC, pedrobaeza commented
Please squash the commit into the migration one.

2023-05-22 05:36 UTC, pedrobaeza commented
/ocabot merge nobump

2023-05-22 05:36 UTC, pedrobaeza commented
/ocabot migration stock_lot_scrap

2023-05-22 07:58 UTC, rousseldenis requested changes
Code review

2023-05-22 07:58 UTC, rousseldenis commented on stock_lot_scrap/models/stock_production_lot.py
> +        result = self.env.ref("stock.action_stock_scrap").read()[0]
```suggestion
        result = self.env["ir.actions.act_window"]._for_xml_id("stock.action_stock_scrap")
```

2023-05-22 07:58 UTC, rousseldenis commented on stock_lot_scrap/models/stock_production_lot.py
> +        for quant in quants:
Change this in order to use multi create.

2023-05-22 09:06 UTC, pedrobaeza commented
Cancelled due to Denis' comments

2023-11-05 12:31 UTC, closed without merging