[ADD] - stock_move_picking_type_origin
OCA/stock-logistics-workflow pull request #1202
Opened 2023-01-27 10:29 UTC by sbejaoui

propagate the picking type of the original move to all next moves created from procurement

2023-01-27 10:29 UTC, sbejaoui commented
cc/ @lmignon

2023-01-27 13:06 UTC, lmignon requested changes
@sbejaoui The original_picking_type_id seems to not be set properly on the first move in a push chain 
![image](https://user-images.githubusercontent.com/544090/215094064-364b9273-d545-40c3-b8cf-a5699146a25d.png)

2023-01-27 13:06 UTC, lmignon commented on stock_move_picking_type_origin/models/stock_rule.py
> +        values["original_picking_type_id"] = move_to_copy.original_picking_type_id.id
@sbejaoui 
????
```suggestion
        values["original_picking_type_id"] = move_to_copy.original_picking_type_id.id or move_to_copy.picking_type_id.id
```
?????

2023-01-27 15:44 UTC, lmignon approved these changes
LGTM (Code review + functional tests)

2023-02-02 07:51 UTC, lmignon commented on stock_move_propagate_first_move/readme/DESCRIPTION.rst
> +This addon propagate the first move reference to all moves in a multi-step route.
@sbejaoui you should explain the `why`... something like

```
Sometimes when you process your move, you need to know which move has
been at the origin of the procurement chain that lead to the creation
of the move. This information could be useful for example to know
if the move is part of an outgoing or incoming process without having
to look at the chained moves.

This module add the fields first_move_id and first_picking_type_id on the
move line to give this information in a transparent way without having
to wonder about the direction in which the move chain should be navigated
to get the information.
```

(feel free to adapt or correct the proposed description)

2023-02-02 08:02 UTC, sbejaoui commented on stock_move_propagate_first_move/readme/DESCRIPTION.rst
> +This addon propagate the first move reference to all moves in a multi-step route.
very helpful, thanks

2023-02-02 08:34 UTC, lmignon approved these changes
Code review + functional

2023-02-08 10:51 UTC, rousseldenis approved these changes
Code review

2023-02-17 13:28 UTC, lmignon requested changes

2023-02-17 13:28 UTC, lmignon commented on stock_move_propagate_first_move/models/stock_move.py
> +    )
@sbejaoui  IMO we should always initialize the first_move_id with self if not provided at create. In this way it's not required to always check if first_move_id is set...

```suggestion
    )
    
    @api.model_create_multi
    def create(self, vals_list):
        res = super().create(vals_list)
        for res in res:
            if res.first_move_id:
                continue
            res.first_move_id = res
        return res
```

2023-03-20 15:06 UTC, rousseldenis commented
/ocabot merge patch

2023-03-20 15:17 UTC, closed without merging