[MIG] stock_picking_tier_validation: Migration to 12.0
OCA/stock-logistics-workflow pull request #1255
Opened 2023-03-20 21:43 UTC by kaynnan

2023-03-21 16:06 UTC, marcelsavegnago approved these changes
LGTM

2023-03-21 16:18 UTC, rousseldenis commented on stock_picking_tier_validation/__manifest__.py
> +    "version": "12.0.1.0.1",
Don't forget to reset to '12.0.1.0.0'

2023-03-21 16:29 UTC, augustodinizl commented on stock_picking_tier_validation/i18n/stock_picking_tier_validation.pot
> +"Project-Id-Version: Odoo Server 14.0\n"
"Project-Id-Version: Odoo Server 14.0\n"
```suggestion
"Project-Id-Version: Odoo Server 12.0\n"
```

2023-03-21 16:29 UTC, augustodinizl commented on stock_picking_tier_validation/README.rst
> +
* `Escodoo <http://escodoo.com.bt>`__:

  * Kaynnan Lemes <kaynnan.lemes@escodoo.com.br>

2023-03-21 16:31 UTC, augustodinizl approved these changes
LGTM - with comments 👍 

Good Job

2023-03-21 20:24 UTC, augustodinizl requested changes

2023-03-21 20:24 UTC, augustodinizl commented on stock_picking_tier_validation/views/stock_picking_views.xml
> +        <field name="arch" type="xml">
it was aproved by me before, BUT...

i think that you missed that the buttons are declared in the view at v12...
look about it here (example): https://github.com/OCA/purchase-workflow/blob/12.0/purchase_tier_validation/views/purchase_order_view.xml

2023-03-23 09:45 UTC, rousseldenis commented
/ocabot migration stock_picking_tier_validation

2023-03-23 13:23 UTC, kaynnan commented
@augustodinizl Implemented the suggestions. I await your review again, please.

2023-03-23 14:59 UTC, augustodinizl approved these changes
Functional tests done, i think that it's ok now...

Congratulations!
![success](https://user-images.githubusercontent.com/25938418/227244292-f76c2d0b-a69e-4e6b-b447-6d911d768834.png)
!!
![success 2 reviewers -rules](https://user-images.githubusercontent.com/25938418/227244278-3bb0f495-1bee-4ad2-ae9a-6d3c21ab83cc.png)
![success 2 reviewers 2](https://user-images.githubusercontent.com/25938418/227244283-a430ea98-f9f3-412f-8a58-c40a68fd8a6a.png)
![success 2 reviewers](https://user-images.githubusercontent.com/25938418/227244288-87889749-00b2-4c82-85ef-738293275c0e.png)

2023-03-23 15:05 UTC, augustodinizl commented
@rousseldenis , i think it's ready to merge now, any considerations?

2023-03-31 16:23 UTC, marcelsavegnago commented
ping @rousseldenis

2023-04-05 07:39 UTC, rousseldenis commented
@kaynnan Do you want to keep commits as is ?

2023-04-05 14:12 UTC, kaynnan commented
> @kaynnan Do you want to keep commits as is ?

Yes, I want to keep it as it is.

2023-04-05 14:13 UTC, rousseldenis approved these changes
Code review

2023-04-05 14:13 UTC, rousseldenis commented
/ocabot merge patch

2023-04-05 14:26 UTC, merged