[16.0][MIG] stock_picking_send_by_mail
OCA/stock-logistics-workflow pull request #1272
Opened 2023-04-07 04:21 UTC by moaadbourhim

Migration from 15.0

2023-04-07 08:06 UTC, rousseldenis commented
/ocabot migration stock_picking_send_by_mail

2023-09-07 14:09 UTC, willmakenoise commented
@rousseldenis It seems this should be good to merge. The tests aren't visible anymore, so can't see why it failed.

2023-09-07 14:10 UTC, rousseldenis commented
/ocabot rebase

2023-09-07 14:53 UTC, willmakenoise commented
@moaadbourhim Can you update the test? The field move_lines on stock.picking is renamed to move_line_ids. Should be a quick fix.

2023-10-05 07:16 UTC, jorgecurso1 approved these changes

2023-10-05 07:18 UTC, rousseldenis requested changes

2023-10-05 07:18 UTC, rousseldenis commented on stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
> +                "move_lines": [
@moaadbourhim You need to change this as the filed does not exist anymore

2023-12-04 15:28 UTC, legalsylvain commented
hi @moaadbourhim. Could you take a look on @rousseldenis remarks ? Thanks !

2024-01-11 07:27 UTC, closed without merging

2024-01-11 07:27 UTC, pedrobaeza commented
Superseded by #1474