[16.0][FIX] stock_picking_auto_create_lot: immediate transfer with auto_create_lot option
OCA/stock-logistics-workflow pull request #1283
Opened 2023-04-27 03:20 UTC by AungKoKoLin1997

Related issue: https://github.com/OCA/stock-logistics-workflow/issues/1281
Related odoo commit: https://github.com/odoo/odoo/commit/dd44e1f69dfd217fafa9c2ec5da8b211b2ff3513

@qrtl

2023-04-27 03:50 UTC, yostashiro requested changes

2023-04-27 03:50 UTC, yostashiro commented on stock_picking_auto_create_lot/models/stock_move.py
> +                    move_line.qty_done = move_line.reserved_uom_qty
```suggestion
            if move.product_id.tracking == "none" or not move.product_id.auto_create_lot or not move.picking_type_id.auto_create_lot:
                continue
            for move_line in move.move_line_ids:
                if move_line.lot_id:
                    # Create-backorder wizard would open without this.
                    move_line.qty_done = move_line.reserved_uom_qty
```

2023-04-27 08:57 UTC, yostashiro commented on stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
> +
I'd consider to do something like the following, upon adjusting `_create_move()` to have the picking as an arg.
```suggestion
        picking_1 = self.picking
        self._create_move(product=self.product_serial, qty=4.0, picking=picking_1)
        picking_1.action_assign()
```

2023-04-27 08:57 UTC, yostashiro commented on stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
> +        # This test will fail before fix PR
```suggestion
        # Confirm that validation is not blocked, for example, by create-backorder wizard.
```

2023-04-27 10:16 UTC, yostashiro approved these changes
LGTM 👍

2023-04-27 10:16 UTC, yostashiro commented on stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
> +        # have 0 done qty.
I think we do not need to be so verbose as the intention should be clear.
```suggestion
        # Clear existing moves.
```

2023-05-02 02:14 UTC, kanda999 approved these changes
Functional Review : It worked as expected

2024-02-22 09:29 UTC, closed without merging