[14.0][MIG] product_cost_price_avco_sync: Migration to 14.0
OCA/stock-logistics-workflow pull request #1286
Opened 2023-05-04 06:31 UTC by zamberjo

2023-05-04 07:55 UTC, chienandalu commented on product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
> +    def setUp(self):
Why the change?

2023-05-04 07:58 UTC, carlosdauden requested changes

2023-05-05 11:58 UTC, zamberjo commented on product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
> +    def setUp(self):
Sorry, I didn't look at the guide, and I thought the change from `SavepointCase` to `TransactionCase` (which has to be done in the migration to 15.0) was in this version. I fix it. 

I have also fixed a warning I was giving, that a `with_company` was missing.

2023-05-05 13:04 UTC, carlosdauden approved these changes
Ok, thanks

2023-05-15 08:54 UTC, jessicaatic approved these changes
It is functional, I tested it and it is correct

2023-05-16 09:42 UTC, chienandalu approved these changes

2023-05-16 09:44 UTC, pedrobaeza commented
I have done some changes in 13.0 that would be good to have it here, and the refactoring is still on its way. I will write when the 13.0 version is ready for rebasing this on top of it.

2023-09-04 09:34 UTC, rafaelbn commented
/ocabot migration product_cost_price_avco_sync

2023-09-04 09:35 UTC, rafaelbn approved these changes
/ocabot merge patch

2023-09-04 09:48 UTC, merged