[15.0][ADD] stock_picking_batch_set_quantity: New module
OCA/stock-logistics-workflow pull request #1314
Opened 2023-06-16 16:31 UTC by carlosdauden

@Tecnativa
Ping @sergio-teruel @CarlosRoca13

2023-06-19 06:12 UTC, CarlosRoca13 approved these changes

2023-06-19 08:19 UTC, sergio-teruel requested changes

2023-06-19 08:19 UTC, sergio-teruel commented on stock_picking_batch_set_quantity/__manifest__.py
> +    "name": "Stock Picking Batch Sequence",
Change the name

2023-06-19 08:19 UTC, sergio-teruel commented on stock_picking_batch_set_quantity/models/stock_move.py
> +# Copyright 2022 Tecnativa - Carlos Dauden
Change copyright

2023-06-19 09:59 UTC, carlosdauden commented
Changes done

2023-07-10 11:03 UTC, sergio-teruel approved these changes

2023-11-26 15:20 UTC, carlosdauden commented
Bot, Why don't merge instead of close it?

2023-11-26 15:46 UTC, pedrobaeza commented
/ocabot merge nobump

2023-11-26 15:55 UTC, merged