[16.0][mig] stock_partner_delivery_window
OCA/stock-logistics-workflow pull request #1332
Opened 2023-07-20 09:36 UTC by heliaktiv

2023-07-28 06:06 UTC, rousseldenis commented
/ocabot migration stock_partner_delivery_window

2023-09-07 03:29 UTC, nguyenminhchien requested changes
- Functional test: ok
- pre-commit check: need to make it pass

2023-09-07 03:29 UTC, nguyenminhchien commented on stock_partner_delivery_window/models/res_partner.py
> +    def get_delivery_time_description(self):
@heliaktiv find no place call this method (`get_delivery_time_description`)

2023-09-20 04:39 UTC, nguyenminhchien commented
Because there's no feedback from the author for a long time, i created a new PR https://github.com/OCA/stock-logistics-workflow/pull/1378 to replace this one.

2023-09-20 07:22 UTC, rousseldenis commented
@heliaktiv Do you agree if we switch to #1378

2023-10-06 13:22 UTC, simahawk commented
@heliaktiv ping

2023-10-09 06:28 UTC, simahawk commented
Enough inactivity here and we've got a completed work with reviews on #1378

2023-10-09 06:28 UTC, closed without merging