[14.0][IMP] stock_restrict_lot: validate lot moved is correct
OCA/stock-logistics-workflow pull request #1443
Opened 2023-11-29 16:21 UTC by aleuffre

Adds a check on picking's validation that the lot indicated in the move line is actually the one in the restriction.

TODO:
- [x] Tests

2023-12-01 13:53 UTC, francesco-ooops commented
@florian-dacosta should be ready for review now

2023-12-02 21:38 UTC, geomer198 requested changes
Please fix the code by my comments.

2023-12-02 21:38 UTC, geomer198 commented on stock_restrict_lot/models/stock_move.py
> +        for move in self.filtered(lambda x: x.restrict_lot_id and x.move_line_ids):
In this function has 2 cycle, I think better do checks in main cycle without `filtered` function.
```py
for move in self:
    if not (move.restrict_lot_id and move.move_line_ids):
        continue
    move_line_lot = move.mapped("move_line_ids.lot_id")
    ...
```

2023-12-02 21:38 UTC, geomer198 commented on stock_restrict_lot/models/stock_move.py
> +                        move_line_lot=", ".join(x.display_name for x in move_line_lot),
Here you can use `mapped` function without cycle:
```py
move_line_lot=", ".join(move_line_lot.mapped('display_name')),
```
I think this code looks more clean.

2023-12-02 21:38 UTC, geomer198 commented on stock_restrict_lot/tests/test_restrict_lot.py
> +    def test_move_validation_inconsistent_lot(self):
Could you add docstring for this function?

2023-12-04 08:41 UTC, aleuffre commented
> Please fix the code by my comments.

Thank you for your review @geomer198 , I've addressed all your comments

2023-12-04 08:44 UTC, rousseldenis commented on stock_restrict_lot/readme/CONTRIBUTORS.rst
> +* Ooops404
@aleuffre @francesco-ooops The contributor's name should be visible

2023-12-04 09:12 UTC, francesco-ooops commented on stock_restrict_lot/readme/CONTRIBUTORS.rst
> +* Ooops404
Hi @rousseldenis , once again I think we should clarify what does "contributor" means, I would be happy to receive your feedback in https://github.com/OCA/maintainer-tools/issues/592 

this is fixed anyway

2023-12-04 09:15 UTC, rousseldenis commented on stock_restrict_lot/readme/CONTRIBUTORS.rst
> +* Ooops404
A contributor is a physical individual.

2023-12-04 09:44 UTC, francesco-ooops commented on stock_restrict_lot/readme/CONTRIBUTORS.rst
> +* Ooops404
@rousseldenis added the physical individual, myself

2023-12-05 11:51 UTC, geomer198 approved these changes
LGTM!

2023-12-05 15:45 UTC, GSLabIt approved these changes

2023-12-05 15:52 UTC, francesco-ooops commented
@florian-dacosta looks good to you? :)

2023-12-06 08:38 UTC, florian-dacosta approved these changes
LGTM
But which is the case where we could an inconsistency between the lot of the `stock.move.line` and the `stock.move`?

Is it manual mistak choosing the wrong lot in the UI? In that case, I guess it could also be solved by adding a domain on the `stock.move.line` `lot_id` depending on the `restrict_lot_id` of the stock.move.

Another possibility, to block the user before the validation, would be to replace the `action_done` override by an `api.constrains` method to check the lot.

Anyway, ok for me the way it is.

2023-12-06 08:43 UTC, aleuffre commented
> LGTM But which is the case where we could an inconsistency between the lot of the `stock.move.line` and the `stock.move`?
> 
> Is it manual mistak choosing the wrong lot in the UI? In that case, I guess it could also be solved by adding a domain on the `stock.move.line` `lot_id` depending on the `restrict_lot_id` of the stock.move.
> 
> Another possibility, to block the user before the validation, would be to replace the `action_done` override by an `api.constrains` method to check the lot.
> 
> Anyway, ok for me the way it is.

Thanks for the approval!

I didn't want to add a constraint because `stock.move` and `stock.move.line` are not written to at the same time, and there could be times just in the normal functioning of the `stock` module where the fields are not in sync (maybe the move line has been created but the lot has not been selected/reserved yet, etc), so having just a check in `._action_done()` seemed safer to me.

2023-12-07 11:12 UTC, francesco-ooops commented
@pedrobaeza go with this?

2023-12-07 11:12 UTC, francesco-ooops commented
or actually also @florian-dacosta can merge :)

2023-12-07 11:15 UTC, pedrobaeza commented
/ocabot merge patch

2023-12-07 11:27 UTC, merged