[15.0][ADD] stock_picking_move_line_detail: New module to open detailed operations
OCA/stock-logistics-workflow pull request #1459
Opened 2023-12-19 16:15 UTC by CarlosRoca13

cc @Tecnativa TT46538

ping @sergio-teruel @carlosdauden

2023-12-19 16:59 UTC, carlosdauden requested changes

2023-12-19 16:59 UTC, carlosdauden commented on stock_picking_move_line_detail/views/stock_picking_view.xml
> +                    attrs="{'invisible': [('show_operations', '=', False)]}"
Add same options (context, attributes, ...) than original view:
https://github.com/odoo/odoo/blob/d97a894751a4291b504843e316957768b657a707/addons/stock/views/stock_picking_views.xml#L347-L348

2023-12-19 21:11 UTC, sergio-teruel commented
Sorry @CarlosRoca13 Where the button is displayed??

![image](https://github.com/OCA/stock-logistics-workflow/assets/7689807/0d75b413-562b-4091-8c38-b2caf0a4e748)

![image](https://github.com/OCA/stock-logistics-workflow/assets/7689807/733e0f0b-6f3c-4dd3-b381-c9c63ac3fc4e)

2023-12-20 14:36 UTC, chienandalu commented on stock_picking_move_line_detail/views/stock_picking_view.xml
> +                    attrs="{'invisible': [('show_operations', '=', False)]}"
Don't you want the opposite condition?

2024-10-21 07:31 UTC, sergio-teruel commented
@CarlosRoca13 Can you attend the comments? Thanks

2025-03-13 20:16 UTC, pedrobaeza commented
@carlosdauden this wasn't finally used, isn't it?

2025-03-14 06:47 UTC, CarlosRoca13 commented
That's it, closed

2025-03-14 06:47 UTC, closed without merging