[15.0][ADD] stock_product_set: New module
OCA/stock-logistics-workflow pull request #1462
Opened 2023-12-22 12:16 UTC by victoralmau

New module

![ejemplo](https://github.com/OCA/stock-logistics-workflow/assets/4117568/93f83c95-3d30-42e0-920f-695b273183b7)

Please @pedrobaeza can you review it?

@Tecnativa TT46704

2023-12-22 21:21 UTC, pedrobaeza requested changes

2023-12-22 21:21 UTC, pedrobaeza commented on stock_product_set/README.rst
> +This module allows to use product sets in internal draft pickings.
It should be available in any type of pickings. The only requirement is that they are planned pickings.

2023-12-22 21:21 UTC, pedrobaeza commented on stock_product_set/README.rst
> +#. Go to *Inventory -> Internal transfer* and create new 'Planned transfer'.
Indicate how to create the "Planned transfer", as it's not obvious.

2023-12-22 21:21 UTC, pedrobaeza commented on stock_product_set/README.rst
> +The dependency sale_product_set must be changed to product_set in v16.
```suggestion
* The dependency sale_product_set must be changed to product_set in v16.
```

2023-12-22 21:21 UTC, pedrobaeza commented on stock_product_set/models/product_set_line.py
> +            "picking_type_id": picking.picking_type_id.id,
You can use https://github.com/odoo/odoo/blob/260ef3dc73f5ed7d24f535145af01d7809dd7065/addons/purchase_stock/models/purchase.py#L506 as template.

I miss here at least `partner_id`.

2023-12-22 21:21 UTC, pedrobaeza commented on stock_product_set/wizard/product_set_add_from_picking.py
> +        line_values.update(sm_model.play_onchanges(line_values, line_values.keys()))
Don't do this. It's not needed here and you don't need the dependency on `onchange_helper` (although I know right now is "hidden"). Follow the same example put before in my comments from `purchase_stock`. Remove entirely this method and call directly the other prepare in set line.

2023-12-22 21:21 UTC, pedrobaeza commented on stock_product_set/views/stock_picking_views.xml
> +                    attrs="{'invisible': ['|', '|', ('picking_type_code','!=','internal'),('state', '!=', 'draft'), ('immediate_transfer', '=', True)]}"
Don't hide it for other picking type codes.

2024-01-02 16:12 UTC, victoralmau commented
Changes done.

2024-01-02 17:23 UTC, pedrobaeza commented on stock_product_set/README.rst
> +#. Go to *Inventory > Configuration > Settings* and check "Storage Locations" option.
This configuration is not needed at all.

2024-01-02 17:23 UTC, pedrobaeza commented on stock_product_set/__manifest__.py
> +    "name": "Stock Product Set",
```suggestion
    "name": "Add product sets in pickings",
```

2024-01-02 17:23 UTC, pedrobaeza commented on stock_product_set/models/product_set_line.py
> +        return {
```suggestion
        # Inspired in .... (and put the reference to Odoo code)
        return {
```

2024-01-17 08:52 UTC, pedrobaeza approved these changes

2024-01-17 12:35 UTC, carolinafernandez-tecnativa approved these changes
Funcional Review LGTM

2024-01-17 16:06 UTC, victoralmau commented
It is ready to merge.

2024-01-17 16:08 UTC, pedrobaeza commented
/ocabot merge nobump

2024-01-17 16:18 UTC, merged