[ADD] stock_picking_batch_invoice_frecuency
OCA/stock-logistics-workflow pull request #1475
Opened 2024-01-10 18:16 UTC by EmilioPascual

Allow invoicing from the picking batch for orders with the configured invoicing frequency.

@Shide @rafaelbn @yajo @Gelojr please review

MT-4038 @moduon

2024-01-10 19:30 UTC, rafaelbn approved these changes
Tested in runboat! 👍🏼 

Works simple an easy, really intuitive.

Maybe in future need a improvement but for the Alpha MVP its great!

2024-01-11 08:27 UTC, yajo requested changes
Code review. Many comments, but most of low relevance. Thanks!

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/__manifest__.py
> +# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0)
**issue(legal):** You depend on [`sale_invoice_frequency`, which is AGPL](https://github.com/OCA/sale-workflow/blob/32c566a77285b0cc6d9e7ac52af6cbbee31f9a94/sale_invoice_frequency/__manifest__.py#L13), so you should either relicense the dependency to LGPL (that's the license under which we should have published that) or move this one to AGPL too.

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/models/sale_invoice_frequency.py
> +        "in stock picking batches when validate them."
```suggestion
        "in stock picking batches when validated."
```

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/models/stock_picking_batch.py
> +            return super().with_context(**context).action_done()
**suggestion(non-blocking):**

```suggestion
            return super().with_context(invoice_batch=True).action_done()
```

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/readme/CONFIGURE.md
> +
**suggestion(non-blocking):**

```suggestion
1. Go to Inventory > Configuration > Settings > Operations.
2. Activate Batch Transfers
```

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/readme/DESCRIPTION.md
> +This module extends the functionality of stock picking batch and to allow yo to invoicing sale orders with invoice frequency with check 'Automatic Invoicing Batch'
**issue(syntax):**

```suggestion
This module extends the functionality of stock picking batch and to allow invoicing sale orders with invoice frequency by checking 'Automatic Invoicing Batch'
```

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/readme/USAGE.md
> +
**issue:** this is garbage that you can remove.
```suggestion
```

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/readme/USAGE.md
> +4. Choose the previously set Invoicing Frequenc.
typo:

```suggestion
4. Choose the previously set Invoicing Frequency.
```

2024-01-11 08:27 UTC, yajo commented on stock_picking_batch_invoice_frequency/readme/USAGE.md
> +8. Invoices from sale orders has been created.
typo:

```suggestion
8. Invoices from sale orders have been created.
```

2024-01-12 07:27 UTC, EmilioPascual commented on stock_picking_batch_invoice_frequency/__manifest__.py
> +# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0)
Ok, I change to AGPL in comment. 
License must be AGPL because sale_invoice_frequency is AGPL and it's a dependency.

2024-01-12 08:33 UTC, yajo approved these changes

2024-01-12 08:49 UTC, Shide approved these changes
Tested locally

2024-01-12 09:24 UTC, rafaelbn approved these changes
/ocabot merge patch

2024-01-12 09:33 UTC, merged