[16.0][ADD stock picking batch print invoices
OCA/stock-logistics-workflow pull request #1485
Opened 2024-01-19 09:39 UTC by EmilioPascual

2024-01-19 09:46 UTC, rousseldenis commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +    @api.onchange("batch_print_invoices")
Please prefer a stored field readonly=False than onchanges.

2024-01-19 09:48 UTC, rousseldenis commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +                    _("The number of invoices copies must be greater than 0")
```suggestion
                    _("The number of invoices copies must be greater or equal to 0")
```

2024-01-19 10:31 UTC, EmilioPascual commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +    @api.onchange("batch_print_invoices")
OK, I changed this

2024-01-19 10:32 UTC, EmilioPascual commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +                    _("The number of invoices copies must be greater than 0")
You're right. Thank you.

2024-01-25 07:39 UTC, rousseldenis approved these changes

2024-01-25 07:59 UTC, Gelojr requested changes
Hi @EmilioPascual 
Nice job! But I think there is a behavior that is not correct. If there are several orders in an invoice that contain several delivery notes, the invoice is printed every time a delivery note is printed. And in the end, the invoice is printed as many times as there are delivery notes.
For example, if invoice F001 contains delivery notes A001, A002, and A003, it will be printed as follows:
A001
F001
A002
F001
A003
F001
https://www.loom.com/share/bd321c1fd6334327b3d660381b5e98ee?sid=46a70a72-fdc0-40c3-8500-346ad9366c4e
Can you check it please?

2024-01-25 09:29 UTC, yajo approved these changes
A lot of suggestions but none of them is blocking. Good job!

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +        help="Allow print all invoices from batch",
**suggestion(dry):** this is redundant with the field name; either explain it better or remove the help:

```suggestion
```

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +        help="Number of invoices copies invoices to print",
**suggestion:** same as above, plus one typo:

```suggestion
        "Number of copies per invoice",
```

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +                    _("The number of invoices copies must be greater or equal to 0")
```suggestion
                    _("The number of copies per invoice must be greater or equal to 0")
```

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/models/stock_picking_type.py
> +                record.number_copies_invoices = 0
**suggestion:** remove this code and give `default=1` to `number_copies_invoices`.

You don't really care about the field value if invoices of this type aren't printed in batch, so you can make the field invisible in that case and just ignore its value. Otherwise, the constrain will make sure the value is valid.

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/readme/CONTEXT.md
> +It will be useful for you if you want to print all the delivery slips and invoices included in a batch together.
**suggestion:** give a better context and move this to description.

These paragraphs fit better in the description of the module, as they explain what the module does.

The context is [a different thing](https://gitlab.com/moduon/odoo-module-template/-/blob/66f9645417f59857874015367786324aa6596045/module/%7B%25%20if%20readme_fragments%20==%20'md'%20%25%7Dreadme%7B%25%20endif%20%25%7D/CONTEXT.md#L7). Example:

```suggestion
Food wholesalers have very little time to fill all their trucks with the goods that are planned to be sold on that day.

There is no time to waste when it comes to printing multiple delivery notes and invoices. When it is done, it is necessary to print multiple copies of these documents. It is faster to distribute them if they are all together.

This module was developed to cover this or a similar use case, and increase efficiency when filling many trucks.
```

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/readme/DESCRIPTION.md
> +This module extends the functionality of stock picking batch and to allow you to print multiple invoices from batches.
```suggestion
This module extends the functionality of stock batch pickings and to allows you to print multiple invoices from batches.
```

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/readme/USAGE.md
> +4. Fill in the number of copies you want.
**suggestion:** move to `CONFIGURE.md`.

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/tests/test_batch_print_invoices.py
> +                    for m in range(2):
**suggestion:** use higher-order functions to reduce cyclomatic complexity:

```suggestion
        for i, j, k, m in itertools.product(*map(range, itertools.repeat(2, 4)))
```

Please, if possible, give variables more descriptive names.

2024-01-25 09:29 UTC, yajo commented on stock_picking_batch_print_invoices/tests/test_batch_print_invoices.py
> +                    for m in range(2):
**suggestion:** just like above:

```suggestion
        for i, j, k, m in itertools.product(*map(range, itertools.repeat(2, 4)))
```

2024-01-26 10:31 UTC, EmilioPascual commented
Fix for stock_picking_group_by_partner_by_carrier to pass the tests: Sometimes method get_remaining_to_deliver is not defined, so it is checkedt first.

2024-01-26 13:18 UTC, EmilioPascual commented
Improvement to print only once the invoice if several pickings are invoiced in single invoice.

2024-01-29 07:52 UTC, yajo approved these changes
I just found one typo, but the rest looks very good.

2024-01-29 07:52 UTC, yajo commented on stock_picking_batch_print_invoices/readme/DESCRIPTION.md
> +This module extends the functionality of stock batch pickings and to allows you to print multiple invoices from batches.
```suggestion
This module extends the functionality of stock batch pickings to let you print multiple invoices from batches.
```

2024-01-29 10:22 UTC, rafaelbn approved these changes
/ocabot merge patch

2024-01-29 10:32 UTC, merged