[14.0][ADD] stock_rule_buy_check_stock_before
OCA/stock-logistics-workflow pull request #1488
Opened 2024-01-23 09:07 UTC by TDu

2024-01-24 10:47 UTC, rousseldenis commented
@TDu Have you looked at https://github.com/OCA/stock-logistics-warehouse/tree/14.0/stock_mts_mto_rule ?

2024-02-06 14:45 UTC, TDu commented
Yes looks similar, thanks for the link.
But the idea behind this one is to use it with the dropshipment route, which I do not think it is possible with that other one. Or I am mistaken ?

2024-02-08 13:59 UTC, jbaudoux requested changes

2024-02-08 13:59 UTC, jbaudoux commented on stock_rule_buy_check_stock_before/models/procurement_group.py
> +        return product_id.free_qty >= quantity
Use `immediately_usable_qty` instead of `free_qty`
Give the warehouse in context to support multi-wh
Use float_compare

2024-02-08 14:02 UTC, jbaudoux commented on stock_rule_buy_check_stock_before/models/procurement_group.py
> +            )._is_product_available(product_id, sale_line.product_uom_qty):
Would be cleaner to give the warehouse in argument and let the method set the context

2024-02-08 14:04 UTC, jbaudoux commented on stock_rule_buy_check_stock_before/models/stock_rule.py
> +    disable_if_stock_exists = fields.Boolean(string="Bypass if stock exists")
```suggestion
    disable_if_stock_exists = fields.Boolean(string="Bypass if available stock")
```

2024-02-08 14:09 UTC, jbaudoux commented on stock_rule_buy_check_stock_before/models/procurement_group.py
> +            )._is_product_available(product_id, sale_line.product_uom_qty):
This computation in `_get_rule` seems to early. I think the approach of mentioned module of Denis is better

2024-02-08 14:13 UTC, jbaudoux commented
@Tdu Can you test by adapting https://github.com/OCA/stock-logistics-warehouse/tree/14.0/stock_mts_mto_rule ?
You need:
* to be able to set a location on the rule
* to be able to configure if you want partial qty
* to extract the method to compute the available stock and use `immediately_usable_qty`

2024-03-15 13:48 UTC, TDu commented
@rousseldenis Thanks for pointing me to that other module.
This one is a fail attempt...closing it.

2024-03-15 13:48 UTC, closed without merging