[16.0][ADD] stock_picking_to_batch_group_fields
OCA/stock-logistics-workflow pull request #1497
Opened 2024-02-06 09:31 UTC by EmilioPascual

Currently this module [stock_picking_batch_extended](https://github.com/OCA/stock-logistics-workflow/tree/16.0/stock_picking_batch_extended) includes this functionality but to make it work it is necessary to activate the OCA batches, which forces to use other behaviours than Odoo's for the picking batches.

This module extends the functionality of the picking batchs and allows you to manually group picking by any field in the model.

@Shide @rafaelbn @fcvalgar @yajo please review, if you want.

@moduon MT-5022

2024-02-06 15:03 UTC, fcvalgar approved these changes
Functional review, 

LGTM, Thank you @EmilioPascual 

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/ad98c408-386a-4c79-adae-1c6d6ffb89d8)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/8c75d7a6-b200-4594-8476-2a4c937de9ed)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/56dea207-9ea2-47ff-b12f-70db9bbf435f)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/67153afe-c2d8-4ce6-9a64-06ba82a694ba)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/3e6821c2-dddf-4862-9fba-5ccdcebf60f0)

2024-02-07 08:18 UTC, Shide approved these changes
Nice job!

2024-02-07 08:18 UTC, Shide commented on stock_picking_to_batch_group_fields/wizard/stock_picking_to_batch.py
> +    _group_field_param = "stock_batch_picking.group_field"
**suggestion (non-blocking):** Defining the param here is unnecessary

2024-02-07 08:18 UTC, Shide commented on stock_picking_to_batch_group_fields/wizard/stock_picking_to_batch.py
> +        return group_fields
**suggestion(non-blocking):** Store the parameters as strings. Eg.: ["user_id", "company_id"]

```suggestion
        group_field_names = (
            self.env["ir.config_parameter"].sudo().get_param("stock_batch_picking.group_field", None)
        )
        if not group_field_names:
            return self.env["ir.model.fields"].browse()
        
        return self.env["ir.model.fields"].search([
            ("model", "=", "stock.picking"), 
            ("name", "in", json.loads(group_fields)),
        ])
```

2024-02-08 09:15 UTC, EmilioPascual commented on stock_picking_to_batch_group_fields/wizard/stock_picking_to_batch.py
> +        return group_fields
Yes, better names than ids

2024-02-08 23:53 UTC, rafaelbn approved these changes
I have been testing in staging and it work 👍🏼 

There is a UX point that we will improve later

2024-02-12 12:25 UTC, rafaelbn requested changes
@EmilioPascual please, we should fix this

![imagen](https://github.com/OCA/stock-logistics-workflow/assets/8736623/36a35bfb-34b5-4120-82f9-dbd1eb1d0e1b)

2024-02-12 12:43 UTC, EmilioPascual commented
> @EmilioPascual please, we should fix this
> 
> ![imagen](https://private-user-images.githubusercontent.com/8736623/304069219-36a35bfb-34b5-4120-82f9-dbd1eb1d0e1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDE4NjYsIm5iZiI6MTcwNzc0MTU2NiwicGF0aCI6Ii84NzM2NjIzLzMwNDA2OTIxOS0zNmEzNWJmYi0zNGI1LTQxMjAtODJmOS1kYmQxZWIxZDBlMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTIzOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGY3YWY3M2M4NzAxYmFhNjdjZDc2ODc2NzFmZmVhZDkwNmYzZDJlNWNhOWViYTU2MmRjOTRkNGI1NTIyMzdlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DOAX6WiDb686sRid8zZ-o5Zt6p2SkU7wETaapOe_0Wc)

@rafaelbn I think you have reviewed other module. This image is an internal module from moduon to make **waves**, but this module is to make **batches**

2024-02-12 17:23 UTC, rafaelbn approved these changes
/ocabot merge patch

2024-02-12 17:29 UTC, merged