[ADD] [16.0] stock_rule_reserve_max_quantity
OCA/stock-logistics-workflow pull request #1513
Opened 2024-02-21 11:44 UTC by Shide

This module extends the functionality of stock reservation to support reserve max available quantity and to allow you to not double check quantity done in previous steps for Outgoing Shipments when is configured with 2 or 3 steps.

This operation will only apply when the available quantity exceeds the demanded quantity and the stock rule linked to the stock move has the field `Reserve Max Quantity` activated.

MT-5085 @moduon @rafaelbn @yajo @Gelojr @rousseldenis @legalsylvain please review if you want :)

2024-02-22 02:00 UTC, rafaelbn reviewed
Great short video ! ❤️ Watching you 😄 happy video make me review faster and simpler!

- [x] After video I have tested in runboat and we should try to improve updating the "demand" with done quantity in the same way it makes when on-step is activated. Futhermore in other case Odoo creates a new stock.move with the weight over the demand.

Thank!

2024-02-22 11:39 UTC, yajo requested changes
Very good one! Some minor (but blocking) issues detected.

2024-02-22 11:39 UTC, yajo commented on stock_rule_reserve_max_quantity/__manifest__.py
> +    "maintainers": ["Shide"],
issue:

```suggestion
    "maintainers": ["Shide", "rafaelbn"],
```

2024-02-22 11:39 UTC, yajo commented on stock_rule_reserve_max_quantity/models/stock_rule.py
> +        "available for the moves that has this rule linked and the quantity "
issue(typo): 

```suggestion
        "available for the moves that have this rule linked, when the quantity "
```

2024-02-22 11:39 UTC, yajo commented on stock_rule_reserve_max_quantity/readme/DESCRIPTION.md
> +This operation will only apply when the available quantity exceeds the demanded quantity and the stock rule linked to the stock move has the field `Reserve Max Quantity` activated.
issue: This isn't code:

```suggestion
This operation will only apply when the available quantity exceeds the demanded quantity and the stock rule linked to the stock move has the field *Reserve Max Quantity* activated.
```

2024-02-22 11:39 UTC, yajo commented on stock_rule_reserve_max_quantity/tests/test_stock_rule_reservation.py
> +        )
issue: avoid polluting other tests:

```suggestion
        self.wh = self.env["stock.warehouse"].search(
            [("company_id", "=", self.env.user.id)], limit=1
        )
        self.addCleanup(delattr, self, "wh")
```

Please do the same with other attributes set in this method.

OTOH, you could just do all this stuff in `setUpClass` which would be more performant. After all, all tests need it.

2024-03-12 16:00 UTC, rafaelbn approved these changes
Tested in runbot and recorded! 👍🏼 

Runnning safetly 1 week in prod

2024-03-12 16:00 UTC, rafaelbn commented
@yajo @EmilioPascual please review, take care of this! thanks!

2024-03-13 07:03 UTC, rousseldenis commented
@Shide @rafaelbn @EmilioPascual I'm wondering if this could be integrated or extend this : https://github.com/OCA/stock-logistics-warehouse/pull/1794

2024-03-15 15:34 UTC, jbaudoux requested changes
Doesn't look right to do such. Looks quite dangerous to me.

Please redo the example shown in the video but process the 2 picks before processing a OUT. I bet you can have the first OUT with the full quantity and the 2nd OUT without any quantity.

2024-03-15 15:36 UTC, jbaudoux commented
> @Shide @rafaelbn @EmilioPascual I'm wondering if this could be integrated or extend this : [OCA/stock-logistics-warehouse#1794](https://github.com/OCA/stock-logistics-warehouse/pull/1794)

@rousseldenis Doesn't related at all to that module. The one you mention is related to MTS reservation rules. Here, they change MTO.

2024-03-15 15:41 UTC, Shide commented
> Doesn't look right to do such. Looks quite dangerous to me.
> 
> Please redo the example shown in the video but process the 2 picks before processing a OUT. I bet you can have the first OUT with the full quantity and the 2nd OUT without any quantity.

You can create those pickings on Runbot and try by yourself.

We are using this PR un production with hundreds of pickings in with 2 steps, with batchs and waves.

In the video I warn to not use this setting on a first step. 
Of course it's a dangerous check if you don't know how to use. Thanks the documentation and the field help is pretty well explained and you won't do that thing.

2024-03-15 16:05 UTC, jbaudoux approved these changes
Tested and working.

It relies on the fact that the call to the method in chain of moves is already limited to the brought quantity. In fact available_quantity is the brought quantity and not what is available on the location
https://github.com/odoo/odoo/blob/16.0/addons/stock/models/stock_move.py#L1713

2024-03-15 16:14 UTC, jbaudoux commented on stock_rule_reserve_max_quantity/readme/DESCRIPTION.md
> +This module extends the functionality of stock reservation to support reserve max available quantity and to allow you to not double check quantity done in previous steps for Outgoing Shipments when i
```suggestion
This module extends the functionality of chained (pull) stock reservation to support the reservation of the total quantity brought by the done chained move lines. By default, the reservation on each step of the chain is limited to the need. If you pick more than the need, with this module the chained moves will reserve the total picked quantity.
```

2024-03-16 07:46 UTC, rafaelbn commented on stock_rule_reserve_max_quantity/readme/DESCRIPTION.md
> +This module extends the functionality of stock reservation to support reserve max available quantity and to allow you to not double check quantity done in previous steps for Outgoing Shipments when i
Thank you @jbaudoux . This has been hard work. Great work @Shide !

2024-03-16 08:10 UTC, EmilioPascual approved these changes

2024-03-18 08:08 UTC, Shide commented on stock_rule_reserve_max_quantity/readme/DESCRIPTION.md
> +This module extends the functionality of stock reservation to support reserve max available quantity and to allow you to not double check quantity done in previous steps for Outgoing Shipments when i
Thanks for the suggestion. 
This description fits much better with what the module does. ❤️

2024-03-21 22:03 UTC, rafaelbn approved these changes
/ocabot merge patch

2024-03-21 22:13 UTC, merged