[14.0][IMP] stock_picking_partner_note: make note field a text field
OCA/stock-logistics-workflow pull request #1543
Opened 2024-03-15 10:27 UTC by JuMiSanAr

@santostelmo 

I'm opening this PR after noticing that the `note` field in `stock.picking`, which was created as an HTML, created some conflicts with what shopfloor expects.

Do you think we could make it a Text field (even more considering `note.name` is a Text field too) and then apply styling through CSS if needed?

@simahawk

2024-03-20 06:05 UTC, santostelmo commented
Hello,

2024-03-20 07:05 UTC, santostelmo commented
I did some testing. With this change notes are showing in the form like that which is not a good presentation:
Partner Picking Notes
![image](https://github.com/OCA/stock-logistics-workflow/assets/67733397/55c663f8-fa3c-4755-873c-dc53a972a68f)

On stock picking aggregated notes are showing like that:
![image](https://github.com/OCA/stock-logistics-workflow/assets/67733397/d3707b5f-78d1-4342-b0cb-51c0774ba5df)

2024-03-20 07:18 UTC, santostelmo requested changes

2024-03-20 07:18 UTC, santostelmo commented on stock_picking_partner_note/models/stock_picking.py
> +        "partner_id.stock_picking_note_ids", "picking_type_id.partner_note_type_ids"
That will trigger a change in all picking notes if a single note is changed in the partner. We can't do that

2024-03-20 08:52 UTC, JuMiSanAr commented
Closing this PR as the shopfloor issue is resolved here: https://github.com/camptocamp/cosanum_odoo/pull/2458

2024-03-21 11:17 UTC, simahawk commented
> I did some testing. With this change notes are showing in the form like that which is not a good presentation: Partner Picking Notes ![image](https://private-user-images.githubusercontent.com/67733397/314404116-55c663f8-fa3c-4755-873c-dc53a972a68f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTk5NzgsIm5iZiI6MTcxMTAxOTY3OCwicGF0aCI6Ii82NzczMzM5Ny8zMTQ0MDQxMTYtNTVjNjYzZjgtZmEzYy00NzU1LTg3M2MtZGM1M2E5NzJhNjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDExMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjOTc3MmNjMDY1NzdhODgwZTE5Y2M4YzMwMWZjNDcyM2I0ODJjMjE1MWM4MWYxNGYwNGJkYWVlYjM4ODQyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3eTTE_VqoSPUdZ1qL-MSp40hfvpe6IFmum1JnMmMItg)
> 
> On stock picking aggregated notes are showing like that: ![image](https://private-user-images.githubusercontent.com/67733397/314404392-d3707b5f-78d1-4342-b0cb-51c0774ba5df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTk5NzgsIm5iZiI6MTcxMTAxOTY3OCwicGF0aCI6Ii82NzczMzM5Ny8zMTQ0MDQzOTItZDM3MDdiNWYtNzhkMS00MzQyLWIwY2ItNTFjMDc3NGJhNWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDExMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZTAwZTdhZDYwYWJiYWQyMzFlYzkxYTE1MTZmNDYzZjU0ZTMwZWE2NzUyOTM5ZDRjNjc3M2U3OGZmOTM3YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rEZrk1tHIzshfJQvGRZ9Xn3tihByOVFvhbzmmvrDFcU)

@santostelmo if it's about that display we should simply add a computed html field. Any issue w/ that?

2024-03-21 11:22 UTC, simahawk commented
Another question: how does it look like on the delivery note report?

2024-03-21 11:28 UTC, simahawk commented
@JuMiSanAr as we discussed we can:
* add `note_html` field to be displayed only in view mode
* `note` will be displayed only in edit mode

This will keep the standard behavior *intact* everywhere, w/o side effects.

2024-03-21 12:12 UTC, santostelmo commented
> > I did some testing. With this change notes are showing in the form like that which is not a good presentation: Partner Picking Notes ![image](https://private-user-images.githubusercontent.com/67733397/314404116-55c663f8-fa3c-4755-873c-dc53a972a68f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTk5NzgsIm5iZiI6MTcxMTAxOTY3OCwicGF0aCI6Ii82NzczMzM5Ny8zMTQ0MDQxMTYtNTVjNjYzZjgtZmEzYy00NzU1LTg3M2MtZGM1M2E5NzJhNjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDExMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjOTc3MmNjMDY1NzdhODgwZTE5Y2M4YzMwMWZjNDcyM2I0ODJjMjE1MWM4MWYxNGYwNGJkYWVlYjM4ODQyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3eTTE_VqoSPUdZ1qL-MSp40hfvpe6IFmum1JnMmMItg)
> > On stock picking aggregated notes are showing like that: ![image](https://private-user-images.githubusercontent.com/67733397/314404392-d3707b5f-78d1-4342-b0cb-51c0774ba5df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTk5NzgsIm5iZiI6MTcxMTAxOTY3OCwicGF0aCI6Ii82NzczMzM5Ny8zMTQ0MDQzOTItZDM3MDdiNWYtNzhkMS00MzQyLWIwY2ItNTFjMDc3NGJhNWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDExMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZTAwZTdhZDYwYWJiYWQyMzFlYzkxYTE1MTZmNDYzZjU0ZTMwZWE2NzUyOTM5ZDRjNjc3M2U3OGZmOTM3YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rEZrk1tHIzshfJQvGRZ9Xn3tihByOVFvhbzmmvrDFcU)
> 
> @santostelmo if it's about that display we should simply add a computed html field. Any issue w/ that?

The html field is not only for display. It can also be edited by the user to customize notes

2024-03-21 16:04 UTC, JuMiSanAr commented
@simahawk so can we still follow the approach with two different computed fields? I don't see how we can keep the original behavior "intact" if the idea of this module is to give the user freedom to customize the notes as they please.

2024-03-21 16:50 UTC, simahawk commented
> The html field is not only for display. It can also be edited by the user to customize notes

Why do you need HTML for that? The notes are not HTML themselves. Why do you want to enforce this?
To me allowing customers to mess up w/ the markup is dangerous.

If you really want to keep it, you can do the contrary: convert the html field to txt by stripping markup and preserving only line breaks but before doing this I'd like to understand what's the real use case.

2024-03-25 09:16 UTC, JuMiSanAr commented
> > The html field is not only for display. It can also be edited by the user to customize notes
> 
> Why do you need HTML for that? The notes are not HTML themselves. Why do you want to enforce this? To me allowing customers to mess up w/ the markup is dangerous.
> 
> If you really want to keep it, you can do the contrary: convert the html field to txt by stripping markup and preserving only line breaks but before doing this I'd like to understand what's the real use case.

@santostelmo

2024-04-03 05:29 UTC, JuMiSanAr commented
@santostelmo could you please check Simone's last comment?

2024-04-03 05:47 UTC, santostelmo commented
> > The html field is not only for display. It can also be edited by the user to customize notes
> 
> Why do you need HTML for that? The notes are not HTML themselves. Why do you want to enforce this? To me allowing customers to mess up w/ the markup is dangerous.
> 
> If you really want to keep it, you can do the contrary: convert the html field to txt by stripping markup and preserving only line breaks but before doing this I'd like to understand what's the real use case.

Answering your points:
Why do you need HTML for that? it allows the user to customize the message layout of the message block
To me allowing customers to mess up w/ the markup is dangerous. => Why ? I see it used in multiple reports.
convert the html field to txt  => New field could be created indeed

2024-04-08 08:14 UTC, JuMiSanAr commented
@simahawk 

If in the end we keep this `note` field as an HTML and then we create an `note_text` field, we would still need a glue module to implement this in shopfloor right?

2024-04-09 08:14 UTC, simahawk commented
> Answering your points: Why do you need HTML for that? it allows the user to customize the message layout of the message block 

> To me allowing customers to mess up w/ the markup is dangerous. => Why ?

Because they might break the layout.


> I see it used in multiple reports. convert the html field to txt => New field could be created indeed

The point is that you are altering a default behavior and, to be honest, having to support a glue module just because a customer wants to edit the final html does not make much sense.
IMO this should go in a customer specific module. Not the contrary.

An alternative can be to make `note` a computed non stored field w/ an inverse. The inverse will store the value into `note_txt` and through a ctx key you can compute the html version. But I wouldn't do this now.
So, please, move this feature to the specific module.

> If in the end we keep this `note` field as an HTML and then we create an `note_text` field, we would still need a glue module to implement this in shopfloor right?

That's exactly what I would like to avoid, especially if this is the need only of 1 customer out there. I've never heard of such a requirement till now :wink:

2024-04-09 08:21 UTC, simahawk commented
> Why do you need HTML for that? it allows the user to customize the message layout of the message block

BTW I still miss this. The notes are not in HTML, only the note on the picking is (in last version) -> how do you enable them to edit the markup if the field is not editable? :thinking:

2024-04-09 09:01 UTC, santostelmo commented
I understand the constraints with HTML field on shopfloor. Let me know if you need anything on my side regarding this refactoring

2024-04-10 15:38 UTC, simahawk approved these changes
@santostelmo as for your issue, ping me and when can see together how to work around that.

2024-08-14 13:12 UTC, jbaudoux approved these changes
Because note field on picking is a Text field in v14

2024-08-14 13:12 UTC, jbaudoux commented
/ocabot merge patch

2024-08-14 13:25 UTC, merged