[16.0][ADD] stock_customer_deposit_elaboration
OCA/stock-logistics-workflow pull request #1547
Opened 2024-03-20 10:28 UTC by EmilioPascual

This module was developed because the modules **sale_elaboration** and **stock_customer_deposit** create a compute method for the order line *route_id* field.

As odoo does not have a compute core method for this field, it cannot be inherited so if you install both modules, one method will be overwritten and one behaviour will be lost.

First it is necessary to merge this pr https://github.com/OCA/stock-logistics-workflow/pull/1503

@yajo @Shide please review

MT-5513 @moduon

2024-03-20 12:02 UTC, yajo requested changes

2024-03-20 12:02 UTC, yajo commented on stock_customer_deposit_elaboration/__manifest__.py
> +    "installable": True,
issue: glue modules should auto-install

```suggestion
    "auto_install": True,
```

2024-03-20 12:02 UTC, yajo commented on stock_customer_deposit_elaboration/models/sale_order_line.py
> +        return
suggestion: this is mostly the same

```suggestion
        return self.elaboration_ids.route_ids[:1]
```

2024-04-08 08:32 UTC, yajo approved these changes
Code review.

2024-04-08 13:35 UTC, fcvalgar commented
@EmilioPascual you can check to have a runboat available. Thank you.

2024-04-09 06:34 UTC, EmilioPascual commented
> @EmilioPascual you can check to have a runboat available. Thank you.

Sorry @fcvalgar, but until this PR https://github.com/OCA/stock-logistics-workflow/pull/1503 is merged, runboat will not work.

2024-04-09 11:15 UTC, rafaelbn commented
/ocabot rebase

2024-04-09 11:15 UTC, rafaelbn commented
@EmilioPascual https://github.com/OCA/stock-logistics-workflow/pull/1503 is merging please rebase when finished! Thank you!

2024-04-12 09:03 UTC, rafaelbn approved these changes
/ocabot merge patch

2024-04-12 09:29 UTC, rafaelbn commented
Please @EmilioPascual @yajo  review https://github.com/OCA/stock-logistics-workflow/commits/7ad2506e581f6ca4a3fe386a7f0836559af788aa

2024-04-12 10:00 UTC, yajo commented
There are incompatible modules, please @EmilioPascual declare them rebels.

2024-04-15 10:21 UTC, fcvalgar approved these changes
Functional review.

LGTM, thank you @EmilioPascual 

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/1029d5ef-2a5e-4dd9-8b88-0df01b410f5d)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/42601756-f7b1-4b3e-ba98-28d2649cb7e4)

2024-04-16 05:53 UTC, Shide approved these changes

2024-04-16 05:54 UTC, EmilioPascual commented
> There are incompatible modules, please @EmilioPascual declare them rebels.

Done!. Thank you  @yajo

2024-04-18 05:09 UTC, rafaelbn commented
/ocabot merge patch

2024-04-18 06:16 UTC, rafaelbn commented
/ocabot merge nobump

2024-04-18 06:59 UTC, merged