[17.0] [MIG] stock_picking_line_sequence: Migration to V17
OCA/stock-logistics-workflow pull request #1552
Opened 2024-03-27 12:42 UTC by siemenv

2024-03-27 12:45 UTC, rousseldenis commented
/ocabot migration stock_picking_line_sequence

2024-09-23 13:12 UTC, StefanRijnhart commented on stock_picking_line_sequence/models/stock.py
> +            return line_key
Well spotted that the line had to change in order to be in sync with https://github.com/odoo/odoo/blob/49d25c5/addons/stock/models/stock_move_line.py#L778-L794, but is there any reason why we can't just call that method and use the line_key that that method returns in its result dictionary?

2024-09-23 13:18 UTC, StefanRijnhart commented on stock_picking_line_sequence/views/stock_view.xml
> +                    </attribute>
Overwriting the context in the form will conflict (functionally) with other modules that need to insert a default value in the same place. Would you consider something like this to inject the additional context key on the code level?

```
    @api.model
    def get_view(self, view_id=None, view_type='form', **options):
        """Append the default sequence.

        The context of `move_ids_without_package` is already overloaded and replacing
        it in a view does not scale across other extension modules.
        """
        res = super().get_view(view_id=view_id, view_type=view_type, **options)
        if res.get('arch') and view_type == 'form':
            doc = etree.XML(res['arch'])
            elements = doc.xpath("//field[@name='move_ids_without_package']")
            if elements:
                element = elements[0]
                context = element.get('context', '{}')
                context = '%s%s, %s' % (context[0], "'default_sequence': max_line_sequence", context[1:])
                element.set('context', context)
            res['arch'] = etree.tostring(doc, encoding='unicode')
        return res
```

2024-09-23 13:44 UTC, StefanRijnhart requested changes
I've implemented my own suggestions in https://github.com/siemenv/stock-logistics-workflow/pull/1

2024-10-22 07:58 UTC, hparfr commented
/ocabot migration stock_picking_line_sequence

2024-12-03 14:41 UTC, StefanRijnhart commented
@siemenv Any comment on my suggestion to make the extension of the context attribute more scalable by injecting the additional key in python code?

2024-12-10 11:46 UTC, StefanRijnhart approved these changes
Thanks for taking my suggestions. I would have liked to retain attribution, maybe through Co-authored-by or maybe even keep the individual commits but I guess it can't be Christmas every day.

2025-01-29 09:22 UTC, AurelijaNorvaisaite commented
@rousseldenis @siemenv is this code ready to be merged?

2025-01-29 09:27 UTC, siemenv commented
> @rousseldenis @siemenv is this code ready to be merged?

I think it is ready.

2025-01-29 09:42 UTC, StefanRijnhart commented
@AurelijaNorvaisaite Please help to get this pull request merged by doing a technical or functional review (let me try to close and reopen this PR to get the pending runboat to build so we can see this code in action).

2025-01-29 11:17 UTC, StefanRijnhart commented
@siemenv Can you try a rebase to fix runboat? My attempt to revive it did not work.

2025-01-29 12:04 UTC, rousseldenis commented
/ocabot rebase

2025-01-29 14:33 UTC, StefanRijnhart commented
@rousseldenis thanks! @AurelijaNorvaisaite runboat is ready if you want to have a look.

2025-01-29 14:53 UTC, rousseldenis commented on stock_picking_line_sequence/models/stock.py
> +class StockMove(models.Model):
Moving one class per file should be done

2025-02-03 16:34 UTC, StefanRijnhart commented on stock_picking_line_sequence/models/stock.py
> +class StockMove(models.Model):
I did this in a separate commit in the migration to 18.0 in Picked an improved version of this in the migration of this module to 18.0 in https://github.com/OCA/stock-logistics-workflow/pull/1864. @siemenv you can pick that commit if you like.

2025-06-06 08:29 UTC, AEstLo approved these changes
Code LGTM

2025-06-06 08:29 UTC, AEstLo commented on stock_picking_line_sequence/models/stock.py
> +class StockMove(models.Model):
I can create a new PR or apply the commit afterwards

2025-06-09 14:51 UTC, LoisRForgeFlow approved these changes
/ocabot merge nobump

2025-06-09 14:59 UTC, merged

2025-06-09 15:03 UTC, LoisRForgeFlow commented on stock_picking_line_sequence/models/stock.py
> +class StockMove(models.Model):
@AEstLo It is merged now, you can go ahead and create the backports

2025-06-10 07:19 UTC, AEstLo commented on stock_picking_line_sequence/models/stock.py
> +class StockMove(models.Model):
thanks!

2025-06-10 07:31 UTC, AEstLo commented on stock_picking_line_sequence/models/stock.py
> +class StockMove(models.Model):
Done: https://github.com/OCA/stock-logistics-workflow/pull/1982