[FIX] stock_picking_sale_order_link: sales_team.group_sale_salesman
OCA/stock-logistics-workflow pull request #1576
Opened 2024-04-18 14:24 UTC by bk-eska

2024-04-25 07:55 UTC, lk-eska commented
This fixes the access error. Can we accept this PR?
@rafaelbn @yajo 

there is another PR for purchase too.

2024-04-25 08:02 UTC, yajo requested changes
It looks good to me. Just squash the commits please.

2024-04-26 21:57 UTC, rafaelbn commented
@jjscarafia do you agree? @Ramibha you migrate it to v17, maybe you could review and fordward port it to 17? Thank you! 😄 ❤️

2024-04-27 10:20 UTC, lk-eska commented
@bk-eska we need to backport this all the way to 14.0

2024-09-16 05:40 UTC, lk-eska commented
any progress on this issue?

@jjscarafia  @Ramibha @rafaelbn

2024-09-16 07:20 UTC, rousseldenis commented
@BerilKoksal Could you squash your commits ?

2024-09-18 11:09 UTC, rafaelbn commented
> any progress on this issue?

@lk-eska missing squash commits

2024-09-18 17:53 UTC, lk-eska commented
@BerilKoksal would you squash the commits?

2025-03-09 12:33 UTC, closed without merging