[ADD] stock_picking_batch_validate_confirm
OCA/stock-logistics-workflow pull request #1589
Opened 2024-05-08 06:24 UTC by EmilioPascual

Wizard to confirm batch if pending origin moves exists when validate batch.

@yajo @Shide @rafaelbn @Gelojr please review.

MT-5994 @moduon

2024-05-08 06:44 UTC, yajo requested changes
Code review.

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/__manifest__.py
> +    "summary": "Request confirmation when validate batch if there are pending origin moves",
```suggestion
    "summary": "Request confirmation when validating batch if there are pending origin moves",
```

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/readme/CONTEXT.md
> +-   ...
issue(docs): add context or remove file please.

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/readme/USAGE.md
> +1. A Wizard show pending origin moves, i.e. moves from picks not done yet.
```suggestion
1. A Wizard shows pending origin moves, i.e. moves from picks not done yet.
```

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/readme/USAGE.md
> +1. Click on *Validate* in wizard if you still want validate the batch.
```suggestion
1. Click on *Validate* in wizard if you still want to validate the batch.
```

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/readme/USAGE.md
> +1. Click on *Cancel* in wizard if you don't want validate the batch untill all origin moves is done.
```suggestion
1. Click on *Cancel* in wizard if you don't want to validate the batch until all origin moves are done.
```

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/wizards/batch_confirm.py
> +    _name = "batch.confirm"
suggestion: "batch" is a pretty wide term. I'd use a more pedantic name for the wizard:

```suggestion
class StockPickingBatchConfirm(models.TransientModel):
    _name = "stock.picking.batch.confirm"
```

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/wizards/batch_confirm.xml
> +                    >validate</i> batches will be validated</p>
suggestion: use a more friendly wording

```suggestion
                <p>There are still some <i>pending origin moves</i>. By clicking on <i
                    >validate</i>, batches will be validated</p>
```

2024-05-08 06:44 UTC, yajo commented on stock_picking_batch_validate_confirm/wizards/batch_confirm.xml
> +                    attrs="{'invisible': [('move_ids', '=', False)]}"
thought: this case should never happen, right?

```suggestion
```

2024-05-08 10:18 UTC, EmilioPascual commented
Thanks @yajo for your review, all request are resolved.

2024-05-09 06:42 UTC, yajo approved these changes
Excellent, thanks!

2024-05-10 09:19 UTC, EmilioPascual commented
I have recorded a video with behavior:
https://www.loom.com/share/f12d566c131c43a2873d84d550306254?sid=7c54113d-abc2-4f3c-8bd5-e38bf2df234d

2024-05-13 05:43 UTC, Shide approved these changes

2024-05-13 07:26 UTC, rafaelbn approved these changes
I've seen the video 

👍🏼

2024-05-13 07:26 UTC, rafaelbn commented
/ocabot merge patch

2024-05-13 07:37 UTC, merged