[REF] stock_picking_batch_print_pickings: Upgrading for dynamic printing
OCA/stock-logistics-workflow pull request #1602
Opened 2024-05-28 11:46 UTC by EmilioPascual

Upgrading for dynamic printing

@Shide @Gelojr @rafaelbn @yajo @fcvalgar please review.

MT-6218 @moduon

2024-05-29 08:01 UTC, EmilioPascual commented
I have recorded a video with new behavior:

https://www.loom.com/share/bfe4c28a9a8449e1bfba58a5cf14415d?sid=3b7838e4-942d-4cb5-bca8-6843722d72b5

2024-05-29 11:16 UTC, Shide requested changes

2024-05-29 11:16 UTC, Shide commented on stock_picking_batch_print_invoices/views/report_picking_batch_print_invoices.xml
> +            t-foreach="set(doc.picking_ids.filtered(lambda p: p.partner_id == partner).sale_id.invoice_ids)"
This will print all invoices even if it's an invoice from a picking invoiced before.

I think should be something like that:
```suggestion
            t-foreach="doc.picking_ids.filtered(lambda p: p.partner_id == partner).mapped("move_ids.sale_line_id.invoice_lines.move_id").filtered(lambda inv: inv.state == 'posted')"
```
With this approach you will only print recent invoices.

2024-05-29 14:36 UTC, EmilioPascual commented on stock_picking_batch_print_invoices/views/report_picking_batch_print_invoices.xml
> +            t-foreach="set(doc.picking_ids.filtered(lambda p: p.partner_id == partner).sale_id.invoice_ids)"
You're right. I have pushed changes. 
Thank you @Shide.

2024-05-30 05:44 UTC, Shide commented on stock_picking_batch_print_invoices/views/report_picking_batch_print_invoices.xml
> +            t-foreach="set(doc.picking_ids.filtered(lambda p: p.partner_id == partner).sale_id.invoice_ids)"
`set()` is not necessary

2024-05-30 06:53 UTC, Shide approved these changes
Code LGTM

2024-05-30 13:33 UTC, fcvalgar approved these changes
Functional review,

LGTM, thank you @EmilioPascual 

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/4fea94aa-6f87-481e-a601-eec3d3900781)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/2f540586-6bfa-41bf-8cb5-9b4bae6c30b8)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/47fca7f6-0f91-4c88-a2ae-a84f1d5e2b44)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/1f7e425c-55b0-4236-8540-de5b7529aaa6)

![image](https://github.com/OCA/stock-logistics-workflow/assets/17847432/9c5fe105-df6c-453b-97cc-afbc099d97c2)

2024-05-31 07:29 UTC, EmilioPascual commented
/ocabot merge minor

2024-05-31 07:40 UTC, merged