[16.0][ADD] stock_picking_auto_create_lot_sequence
OCA/stock-logistics-workflow pull request #1619
Opened 2024-06-11 04:47 UTC by AungKoKoLin1997

This module acts as a bridge between the stock_picking_auto_create_lot and product_lot_sequence modules.
Due to the changes introduced in [this commit](https://github.com/OCA/stock-logistics-workflow/commit/1f1d1cd4ba102f35971c074ca869ed6f7113cd2b) for stock_picking_auto_create_lot, using these two modules together disrupts the design of product_lot_sequence by not allowing the use of specific sequences for each product. This module restores the intended behavior.
Related: https://github.com/OCA/stock-logistics-workflow/pull/1616

@qrtl QT4624

2024-06-11 08:49 UTC, AungKoKoLin1997 commented
I created the PR to fix the tests failed.
https://github.com/OCA/stock-logistics-workflow/pull/1621/files

2024-06-24 13:33 UTC, yostashiro requested changes

2024-06-24 13:33 UTC, yostashiro commented on stock_picking_auto_create_lot_sequence/__manifest__.py
> +# Copyright 2024 Quartile Limited
```suggestion
# Copyright 2024 Quartile (https://www.quartile.co)
```

2024-06-24 13:33 UTC, yostashiro commented on stock_picking_auto_create_lot_sequence/__manifest__.py
> +    "author": "Quartile Limited, Odoo Community Association (OCA)",
```suggestion
    "author": "Quartile, Odoo Community Association (OCA)",
```

2024-06-24 13:33 UTC, yostashiro commented on stock_picking_auto_create_lot_sequence/models/stock_move_line.py
> +        return super()._get_lot_sequence()
```suggestion
        if not self.product_id.lot_sequence_id:
            return super()._get_lot_sequence()
        seq_policy = self.env["stock.lot"]._get_sequence_policy()
        if seq_policy != "product":
            return super()._get_lot_sequence()
        return self.product_id.lot_sequence_id._next()
``````

2024-06-24 13:33 UTC, yostashiro commented on stock_picking_auto_create_lot_sequence/readme/DESCRIPTION.rst
> +sequences for each product. This module restores the intended behavior.
This explanation sounds a bit off. I think we can simply remove this part.
```suggestion
```

2024-06-24 13:33 UTC, yostashiro commented on stock_picking_auto_create_lot_sequence/tests/test_stock_picking_auto_create_lot_sequence.py
> +        cls.picking_type_in_id = cls.env.ref("stock.picking_type_in").id
Might as well do this in the setup.
```suggestion
        picking_type_in = cls.env.ref("stock.picking_type_in")
        picking_type_in.auto_create_lot = True
```

2024-06-24 13:33 UTC, yostashiro commented on stock_picking_auto_create_lot_sequence/tests/test_stock_picking_auto_create_lot_sequence.py
> +        self.picking.picking_type_id.auto_create_lot = True
```suggestion
```

2024-06-25 01:37 UTC, yostashiro approved these changes
Code review.

2024-06-25 01:45 UTC, yostashiro commented
@AungKoKoLin1997 Can you please check the CI errors?

2024-06-25 02:06 UTC, AungKoKoLin1997 commented
> @AungKoKoLin1997 Can you please check the CI errors?

@yostashiro I created the PR for this https://github.com/OCA/stock-logistics-workflow/pull/1619#issuecomment-2160152486.

2024-07-23 08:29 UTC, kanda999 approved these changes
Functional and Code review.

2024-07-23 08:34 UTC, rousseldenis commented
/ocabot merge nobump

Should be great to improve coverage by adding tests that shows other scenarios are working

2024-07-23 08:45 UTC, merged