[17.0][MIG] stock_picking_show_backorder: Migration to 17.0
OCA/stock-logistics-workflow pull request #1662
Opened 2024-07-26 10:52 UTC by RogerSans

Standar migration
T-6444

@HaraldPanten 
@ValentinVinagre 
@luis-ron

2024-07-26 11:18 UTC, Tisho99 commented on stock_picking_show_backorder/views/stock_view.xml
> +                    invisible="backorder_ids == []"
i think: "not backorder_ids is better"

2024-07-30 07:48 UTC, RogerSans commented on stock_picking_show_backorder/views/stock_view.xml
> +                    invisible="backorder_ids == []"
Changed. TNX

2024-07-30 14:46 UTC, luis-ron approved these changes
Functional Review: LGTM 👍🏻

2024-08-01 09:00 UTC, Tisho99 requested changes

2024-08-01 09:00 UTC, Tisho99 commented on stock_picking_show_backorder/README.rst
> +   'Quantity'.
Its the opposite, the quantity must me less than the demand to create a backorder. You cant edit the demand

2024-08-01 09:05 UTC, RogerSans commented on stock_picking_show_backorder/README.rst
> +   'Quantity'.
Done. TNX

2024-08-01 11:46 UTC, Tisho99 approved these changes
LGTM. Functional and code review

2024-08-01 11:58 UTC, HaraldPanten approved these changes
@JordiBForgeFlow @LoisRForgeFlow 

Could we merge this one?

THX!

2024-08-05 06:31 UTC, LoisRForgeFlow approved these changes
LGTM

/ocabot merge nobump

2024-08-05 06:32 UTC, LoisRForgeFlow commented
/ocabot migration stock_picking_show_backorder

2024-08-05 06:37 UTC, merged