14.0 mig stock picking operation quick change
OCA/stock-logistics-workflow pull request #1668
Opened 2024-08-07 14:29 UTC by Ricardoalso

2024-08-14 21:37 UTC, gbrito requested changes

2024-08-14 21:37 UTC, gbrito commented on stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> +        first_move_line = pickings.mapped("move_line_ids")[:1]
No need to use mapped on relational fields, Odoo does it by default 
```suggestion
        first_move_line = pickings.move_line_ids[:1]
```

2024-08-14 21:37 UTC, gbrito commented on stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> +            record.allowed_product_ids = record.picking_id.move_lines.mapped(
No need to use mapped on relational fields, Odoo does it by default
```suggestion
            record.allowed_product_ids = record.picking_id.move_lines.product_id
```

2024-08-14 21:37 UTC, gbrito commented on stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> +            lambda x: x.move_lines.mapped("move_dest_ids")
No need to use mapped on relational fields, Odoo does it by default
```suggestion
            lambda x: x.move_lines.move_dest_ids
```

2024-08-14 21:37 UTC, gbrito commented on stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> +        move_lines = pickings.mapped("move_line_ids")
No need to use mapped on relational fields, Odoo does it by default
```suggestion
        move_lines = pickings.move_line_ids
```

2024-08-14 21:37 UTC, gbrito commented on stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> +    def action_apply(self):
```suggestion
    def action_apply(self):
        self.ensure_one()
```

2024-08-15 06:23 UTC, Ricardoalso commented
@gbrito Thanks for you review. Indeed I didn't pay attention to that during the migration, my bad.  New commit added :wink:

2024-08-15 08:36 UTC, gbrito approved these changes

2024-10-18 18:37 UTC, FrancescoBallerini approved these changes
Hello, I've tested this locally as the runbot is off. 
I think this can be reviewed as functionally ok but I do not understand why by applying the wizard with "CHANGE ALL" and setup a new `location_dest_id` , the value is correctly retrieved on wizard (and business logic as well I guess) but we still see the picking location dest ID on the stock move lines.. 

I think I can approve but I'd like to understand why this happens, if possible, thanks ! : )

2024-10-30 15:20 UTC, florian-dacosta commented
> Hello, I've tested this locally as the runbot is off. I think this can be reviewed as functionally ok but I do not understand why by applying the wizard with "CHANGE ALL" and setup a new `location_dest_id` , the value is correctly retrieved on wizard and business logic (e.g. when validating the picking the "done" quant is correctly moved to the location) but we still see the picking location dest ID on the stock move lines..
> 
> I think I can approve but I'd like to understand why this happens, if possible, thanks ! : )

@FrancescoBallerini There are 2 different notions actually : 
The stock moves (`stock.move`) which indicate a quantity of product to move from a zone to another => The same zones that are displayed at the picking level
The operations (`stock.move.line`). Depending on the configuration of your Odoo, you do not always see the operations displayed in a tab of the picking, but they exists anyway.
The goal of the operation is to indicate precisely what you move (which lot, which pack ? and which sublocation)

This module only change the destination location of the operations, that is why it does not change anything on the picking.

For instance, you have a picking with one line only with product quantity 10 and going from "supplier" to "WH/Stock".
You could fill the operations this way : 5 products are going to WH/stock/shelf1 and 5 products are going to WH/stock/shelf2
This way, only the destination location of both operation is changed, while the "zone", on the stock move is still "WH/stock".
This is how it happens, even without this module installed.
Hope it is clear

2024-10-30 15:21 UTC, florian-dacosta approved these changes

2024-10-31 20:30 UTC, FrancescoBallerini commented
@florian-dacosta I've missed your ping [here ](https://github.com/OCA/stock-logistics-workflow/pull/1232#issuecomment-2447560455) , glad it was merged aniway!

Thank you for the detailed explanation. I received similar insights about these models recently, and both were helpful.

Just a consideration: I think that if a user is going to change the "deepest" layer (`stock.move.line`) , also the highest level layer `stock.move` should reflect the change. Additionally I guess also the picking `location_dest_id` could change at this point if that's true. Does it make sense or there are some reason why it shouldn't change? 

I'm not really asking for implementation, it's just for my knowledge about this module since I'm considering to make additional customizations for a local deploy

Thank you again

2025-04-06 12:43 UTC, closed without merging