[16.0][ADD] stock_sale_product_volume
OCA/stock-logistics-workflow pull request #1695
Opened 2024-09-05 10:18 UTC by mathieudelva

2024-09-05 10:48 UTC, rvalyi requested changes

2024-09-05 10:48 UTC, rvalyi commented on stock_sale_product_volume/models/sale_order.py
> +    total_volume = fields.Float(compute="_compute_total_volume", string="Volume en m3")
s/en m3/in cubic meter/


Also eventually you add an _m3 suffix in the field name or manage its uom (see how it's done for volume on picking) so cubic meter might not be hardcoded.

2024-09-05 12:12 UTC, rvalyi commented on stock_sale_product_volume/models/sale_order.py
> +    total_volume = fields.Float(compute="_compute_total_volume", string="Volume en m3")
in fact I think managing the unit (use the product unit squared? use some kind of per company or per sale team configuration?) would make the module way more usable...  cc @sebastienbeau

2024-09-10 14:28 UTC, bealdav commented on stock_sale_product_volume/__manifest__.py
> +    ],
Missing maintainers key

2024-09-10 15:01 UTC, mathieudelva commented on stock_sale_product_volume/models/sale_order.py
> +    total_volume = fields.Float(compute="_compute_total_volume", string="Volume en m3")
@rvalyi, I updated the module, there are already the units in config parameters

2024-09-11 12:40 UTC, kevinkhao approved these changes

2024-09-11 12:40 UTC, kevinkhao commented on stock_sale_product_volume/models/stock_package_type.py
> +        conversion_uom_dict = {"mm³": 1, "cm³": 1000000, "m³": 1000000000}
convention nitpicking: you can leave constants at the top level of the file in capital letters. Otherwise LGTM

2024-09-11 15:48 UTC, jbaudoux requested changes

2024-09-11 15:48 UTC, jbaudoux commented on stock_sale_product_volume/models/stock_package_type.py
> +    )
Can you extract this to a separate module `stock_package_type_volume` in a separate PR ?

2024-09-11 16:08 UTC, jbaudoux requested changes
Rename the module to `sale_stock_volume_by_packaging_type`
and explain how the volume is computed because it's more common to use the volume of the product or product packaging

2024-09-11 16:08 UTC, jbaudoux commented on stock_sale_product_volume/__manifest__.py
> +    "summary": """""",
fill properly

2024-09-11 16:08 UTC, jbaudoux commented on stock_sale_product_volume/__manifest__.py
> +    "depends": ["stock", "sale_management"],
```suggestion
    "depends": ["stock", "sale"],
```

2024-09-11 16:08 UTC, jbaudoux commented on stock_sale_product_volume/readme/DESCRIPTION.rst
> +This module adds the volume on stock_package_type and calculate total volume on sale order
Explain your specific computation for the volume on the SO line

2024-09-11 16:08 UTC, jbaudoux commented on stock_sale_product_volume/models/sale_order.py
> +            record.total_volume = total_volume if total_volume > 0 else 0
Replace this by a sql constraint on the package type volume

2024-09-12 18:17 UTC, rvalyi requested changes

2024-09-12 18:17 UTC, rvalyi commented on stock_sale_product_volume/models/sale_order.py
> +        compute="_compute_total_volume", string="Volume in cubic meter"
So if the unit is now a setting, you should remove the cubic meter mention

2024-09-30 11:55 UTC, rousseldenis commented
@mathieudelva Could you take into account reviews ? Thanks

2025-03-30 12:43 UTC, closed without merging