18.0 mig stock lot production date
OCA/stock-logistics-workflow pull request #1771
Opened 2024-11-19 16:08 UTC by fredericgrall

2024-12-19 12:02 UTC, sebalix commented
Thanks for this migration :pray: 
Now that the v17 version has been migrated here: https://github.com/OCA/stock-logistics-workflow/pull/1683, it would make sense to retrieve the history from 17.0 branch to get a clean copy of this module, and re-apply your migration commit on top of that.
Can you handle this @fredericgrall ?

2024-12-19 12:03 UTC, sebalix commented
/ocabot migration stock_lot_production_date

2024-12-19 13:10 UTC, rousseldenis approved these changes
LGTM

2024-12-19 13:10 UTC, rousseldenis commented
@fredericgrall Could you squash your commits ? Thanks

2025-02-05 08:00 UTC, rousseldenis commented
@fredericgrall

2025-02-05 08:01 UTC, LucasTran380381 approved these changes
lgtm

2025-02-11 10:43 UTC, jbaudoux requested changes
Please move PR to https://github.com/OCA/product-attribute/tree/18.0

See https://github.com/OCA/wms/blob/18.0/README.md

2025-03-10 14:06 UTC, sebalix commented
Closing this one in favor of https://github.com/OCA/product-attribute/pull/1911

2025-03-10 14:06 UTC, closed without merging