[16.0][MIG] stock_picking_late_activity: Migration to 16.0
OCA/stock-logistics-workflow pull request #1778
Opened 2024-11-26 06:54 UTC by HeliconiaSolutions

2024-11-26 06:56 UTC, rousseldenis commented
/ocabot migration stock_picking_late_activity

2024-11-26 06:57 UTC, rousseldenis commented on stock_picking_late_activity/README.rst
> +* Heliconia Solutions
@HeliconiaSolutions You cannot put yourself as an author without major contribution to this module. Please put yourself in Contributors section (as individual).

2024-11-26 06:58 UTC, rousseldenis requested changes

2024-11-26 06:58 UTC, rousseldenis commented on stock_picking_late_activity/__manifest__.py
> +    "author": "Tecnativa, Heliconia Solutions, Odoo Community Association (OCA)",
See comment above

2024-11-26 08:45 UTC, BhaveshHeliconia commented on stock_picking_late_activity/__manifest__.py
> +    "author": "Tecnativa, Heliconia Solutions, Odoo Community Association (OCA)",
@rousseldenis Thank you for the clarification. Noted, we have made the necessary updates accordingly.

2025-02-27 11:11 UTC, HeliconiaSolutions commented
@rousseldenis, Please Review!

2025-04-15 06:28 UTC, BhaveshHeliconia commented
Hey @OCA/logistics-maintainers would be great if someone could have a look at this module.

2025-04-15 15:37 UTC, Christian-RB approved these changes
LGTM

2025-07-18 09:23 UTC, BhaveshHeliconia commented
Ping @rousseldenis

2025-11-17 06:20 UTC, BhaveshHeliconia commented
@rousseldenis Could you please review this PR? Thanks!

2025-11-17 07:50 UTC, rousseldenis approved these changes

2025-11-17 07:50 UTC, rousseldenis commented
/ocabot merge nobump

2025-11-17 08:04 UTC, merged