[18.0][MIG] stock_picking_auto_create_lot: Migration to 18.0
OCA/stock-logistics-workflow pull request #1781
Opened 2024-11-28 15:05 UTC by cem-adhoc

2024-11-29 11:48 UTC, luc-adhoc approved these changes
functional review

2024-11-29 13:58 UTC, JrAdhoc approved these changes
functional and technical review. LGTM

2024-12-05 11:35 UTC, mav-adhoc approved these changes

2024-12-06 10:03 UTC, rousseldenis commented
/ocabot migration stock_picking_auto_create_lot

2024-12-06 10:06 UTC, rousseldenis requested changes

2024-12-06 10:06 UTC, rousseldenis commented on stock_picking_auto_create_lot/tests/common.py
> +                "type": "consu",
IMHO, should be ìs_storable` too.

2025-01-14 20:15 UTC, cem-adhoc commented
@rousseldenis Thanks for the review. I’ve made the requested change.

2025-01-19 12:20 UTC, bosd requested changes
Functional test ok.
Hope this fixes the unit tests.

2025-01-19 12:20 UTC, bosd commented on stock_picking_auto_create_lot/tests/common.py
> +                "auto_create_lot": auto,
```suggestion
                "auto_create_lot": auto,
                "is_storable": True,
```

2025-01-19 12:20 UTC, bosd commented on stock_picking_auto_create_lot/tests/common.py
> +                "type": "consu",
:+1:  @cem-adhoc Can you please attend to this?

2025-01-22 18:16 UTC, bosd approved these changes
LGTM :+1:

2025-01-23 07:26 UTC, Dranyel-Bosd approved these changes
LGTM :100:

2025-01-24 05:48 UTC, bosd commented
@rousseldenis Is this one ok for you now? Can we proceed to get this merged?

2025-01-24 08:12 UTC, rousseldenis approved these changes

2025-01-24 08:37 UTC, rousseldenis commented
/ocabot merge nobump

2025-01-24 08:42 UTC, merged