[18.0][MIG] stock_partner_delivery_window: Migration to 18.0
OCA/stock-logistics-workflow pull request #1783
Opened 2024-12-04 05:20 UTC by thienvh332

2025-01-06 19:40 UTC, ivantodorovich approved these changes

2025-01-10 09:03 UTC, ajaniszewska-dev approved these changes
seems good

2025-01-10 09:04 UTC, rousseldenis commented
/ocabot migration stock_partner_delivery_window

2025-01-10 09:31 UTC, rousseldenis requested changes

2025-01-10 09:31 UTC, rousseldenis commented on stock_partner_delivery_window/models/res_partner.py
> +            domain.append(("time_window_weekday_ids", "in", week_day_id))
append is never a good idea. Using `expression.AND()` is better.

2025-01-10 09:31 UTC, rousseldenis commented on stock_partner_delivery_window/models/res_partner.py
> +        result["delivery_time_window_ids"] = [(0, 0, val) for val in values]
Minor comment, using `Command` is IMHO better.

2025-01-10 09:31 UTC, rousseldenis commented on stock_partner_delivery_window/models/stock_picking.py
> +            ).format(
You should use translate function arguments instead.

2025-01-10 09:31 UTC, rousseldenis commented on stock_partner_delivery_window/models/stock_picking.py
> +    @api.onchange("scheduled_date")
IMHO, warnings could be avoided using alerts instead.

2025-01-10 09:31 UTC, rousseldenis commented on stock_partner_delivery_window/tests/test_delivery_window.py
> +        cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
Use `BaseCommon` class to avoid this.

2025-02-04 08:17 UTC, rousseldenis commented on stock_partner_delivery_window/models/res_partner.py
> +                [domain, [("time_window_weekday_ids", "in", week_day_id)]]
```
domain = expression.AND(
                [domain, [("time_window_weekday_ids", "in", [week_day_id])]]
```

2025-02-28 10:07 UTC, AaronHForgeFlow requested changes
It works but it seems there is some formatting issue in the error message:

![image](https://github.com/user-attachments/assets/2ff7bebd-4dc2-4d26-a3ed-343da4cec0e4)

2025-04-02 08:48 UTC, ArnauCForgeFlow commented
Hello @thienvh332 will you address the comments, or I should do a supersede?

2025-04-03 13:10 UTC, sebalix commented
@ArnauCForgeFlow yes please go ahead :)

2025-04-03 14:06 UTC, ArnauCForgeFlow commented
@sebalix Done! here is the new pr: https://github.com/OCA/stock-logistics-workflow/pull/1910

2025-04-04 02:36 UTC, thienvh332 commented
Hello @ArnauCForgeFlow ,
Oh sorry I missed it. Thanks for your help :pray:

2025-04-07 14:50 UTC, sebalix commented
Closing in favor of #1910
Thanks @thienvh332 and @ArnauCForgeFlow

2025-04-07 14:50 UTC, closed without merging