[IMP] stock_picking_group_by_partner_by_carrier: merged procurement group should not be linked to the original sales order
OCA/stock-logistics-workflow pull request #1789
Opened 2024-12-11 16:34 UTC by sbejaoui

When a merged procurement group is created, it should not be linked to the original sales order. Linking it would cause any moves manually added to the delivery picking to be associated with that sales order.

The first commit reproduce the bug and show how the manual add of a move to the picking impact the sale order.

2024-12-11 16:41 UTC, sbejaoui commented
cc/ @rousseldenis , @lmignon

2024-12-12 07:46 UTC, lmignon approved these changes
Thank you for this FIX. Indeed, without this a merged procurement could introduce hard to understand unexpected behaviour. LGTM (Code review)

2024-12-12 07:57 UTC, rousseldenis approved these changes

2024-12-17 08:24 UTC, lauradiaz22 approved these changes
Good morning,
I have reviewed this FIX at a functional level and this LGTM👍

2025-01-17 10:57 UTC, jbaudoux requested changes
You cannot empty the `sale_id` field as it is used by many module (enterprise) and few OCA in delivery.
I logged what is I think the real issue https://github.com/OCA/stock-logistics-workflow/issues/1833

2025-05-28 08:09 UTC, jbaudoux commented
@lmignon @rousseldenis This needs to be reworked

2025-05-28 13:29 UTC, lmignon commented
> @lmignon @rousseldenis This needs to be reworked

@jbaudoux Ticket created into our issue tracker to don't forget it..

2025-11-09 12:47 UTC, closed without merging