[18.0][MIG] stock_valuation_layer_usage
OCA/stock-logistics-workflow pull request #1795
Opened 2024-12-18 12:55 UTC by JasminSForgeFlow

Standard Migration

@ForgeFlow

2024-12-18 13:03 UTC, MiquelRForgeFlow approved these changes

2024-12-20 08:11 UTC, rousseldenis commented
/ocabot migration stock_valuation_layer_usage

2025-03-10 09:04 UTC, AaronHForgeFlow commented
Hi Jasmin! can you please cherry-pick this commit? af90a39a7e1084cada3cbe09bfd4610bd4df62e3

2025-03-11 04:34 UTC, JasminSForgeFlow commented
> Hi @JasminSForgeFlow ! can you please cherry-pick this commit? [af90a39](https://github.com/OCA/stock-logistics-workflow/commit/af90a39a7e1084cada3cbe09bfd4610bd4df62e3)

Done, thanks

2025-03-21 10:48 UTC, ThiagoMForgeFlow requested changes

2025-03-21 10:48 UTC, ThiagoMForgeFlow commented on stock_valuation_layer_usage/views/stock_move_views.xml
> +                    groups="account.group_account_user"
Could you add `colspan="2"` to improve visual effect?

![2025-03-21_11-37](https://github.com/user-attachments/assets/8c313884-ea66-44ef-9799-4157fdb04913)

2025-03-24 04:20 UTC, JasminSForgeFlow commented on stock_valuation_layer_usage/views/stock_move_views.xml
> +                    groups="account.group_account_user"
Updated, Thanks

2025-03-24 07:37 UTC, ThiagoMForgeFlow approved these changes

2025-03-28 09:41 UTC, JordiMForgeFlow approved these changes

2025-05-01 07:29 UTC, AaronHForgeFlow approved these changes
Functional ok!

2025-05-02 09:05 UTC, LoisRForgeFlow approved these changes
/ocabot merge nobump

2025-05-02 09:13 UTC, merged