[16.0][FIX] stock_picking_return_restricted_qty: remove _onchange_quantity method
OCA/stock-logistics-workflow pull request #1799
Opened 2024-12-19 17:53 UTC by ced-adhoc

Creating this fix to remove the _onchange_quantity method because when changing the quantity on the return wizard to a greater quantity than the original and clicking on the return button, it first validate the _onchange_quantity method and, due to the user error, changes back the quantity to the original one and then it runs the _create_returns method with the original quantity. This causes that if the user made a mistake and wanted to return less quantity than the original one, they cannot correct it since the return is already created.
With this fix, after clicking on the return button, it validates the quantities and when closing the user error popup window it remains on the return wizard allowing to correct the returned quantity.

2024-12-19 18:35 UTC, luc-adhoc approved these changes
functional review

2024-12-19 18:52 UTC, mav-adhoc approved these changes

2024-12-20 07:58 UTC, rousseldenis requested changes

2024-12-20 07:58 UTC, rousseldenis commented on stock_picking_return_restricted_qty/wizard/stock_picking_return.py
> -            raise UserError(_("Return more quantities than delivered is not allowed."))
@ced-adhoc You remove here a fucntionality. Maybe in order to get user warned before validating the return should be to add an alert on the wizard form (if it is possible) or by other mean.

2024-12-26 12:54 UTC, mav-adhoc commented
@rousseldenis What's the point to put the UserError on an onchange_quantity method if either way the quantity restriction will be validated when clicking on the return button? It looks redundant. It makes any difference? Sorry to ask! I was just wondering because it doesn't make too much sense to me.

2025-02-13 17:34 UTC, ced-adhoc commented
@rousseldenis Hi! I'm taking up this task based on you suggestion. I replaced the UserError with a warning in the onchange quantity method, and it seems to work as expected. Could you please review it again and let me know your thoughts? Thanks!

2025-02-14 14:14 UTC, mav-adhoc approved these changes

2025-02-18 15:28 UTC, ced-adhoc commented on stock_picking_return_restricted_qty/wizard/stock_picking_return.py
> -            raise UserError(_("Return more quantities than delivered is not allowed."))
@rousseldenis Hi! I'm taking up this task based on you suggestion. I replaced the UserError with a warning in the onchange quantity method, and it seems to work as expected. Could you please review it again and let me know your thoughts? Thanks!

2025-02-20 18:42 UTC, florenciafrigieri2 approved these changes
Test working ok.
When the restriction is set in the operation type, Odoo is not allowing to return bigger quantities. If you have a mistake, it is possible to correct it.

2025-02-26 12:21 UTC, ced-adhoc commented
Hi @rousseldenis could you please check this fix? Thanks in advance!

2025-03-10 12:07 UTC, ced-adhoc commented
Hi @rousseldenis could you please check this? thanks!

2025-07-14 08:01 UTC, pedrobaeza commented
The idea to raise a `UserError` is to rollback the quantity to the previous one. With this change, it won't be rollbacked, and then, it's possible to validate a picking returning more quantity, which is not correct.

2025-12-28 12:54 UTC, closed without merging