Porting stock_picking_package_preparation* to 9
OCA/stock-logistics-workflow pull request #199
Opened 2016-02-02 17:44 UTC by eLBati

Modules
 - stock_picking_package_preparation
 - stock_picking_package_preparation_line

2016-05-03 14:44 UTC, gurneyalex commented
rebuilding on runbot.

@eLBati did you check #212 and #226 ?

2016-05-03 14:47 UTC, gurneyalex commented
travis should be green once #227 is merged.

2016-05-04 16:42 UTC, jgrandguillaume commented
LGTM :+1:

2016-05-13 15:47 UTC, eLBati commented
Hi @OpenCode 
I included your last changes to ```stock_picking_package_preparation_line``` to this PR.
But local tests give me
```
2016-05-13 15:44:35,913 28110 ERROR demo_9 openerp.addons.stock_picking_package_preparation_line.tests.test_package_preparation_line: `   File "/home/elbati/workspace/odoo/instances/demo9-community/parts/stock-logistics-workflow/stock_picking_package_preparation_line/tests/test_package_preparation_line.py", line 176, in test_standard_flow_with_detail_with_lot
2016-05-13 15:44:35,913 28110 ERROR demo_9 openerp.addons.stock_picking_package_preparation_line.tests.test_package_preparation_line: `     self.preparation.pack_operation_ids[0].lot_id.id,
2016-05-13 15:44:35,913 28110 ERROR demo_9 openerp.addons.stock_picking_package_preparation_line.tests.test_package_preparation_line: ` AttributeError: 'stock.pack.operation' object has no attribute 'lot_id'
```

I think this is because 9.0 introduced ```stock.pack.operation.lot``` model.
Could you give me any hint?

Thanks

2016-06-16 12:48 UTC, OpenCode commented
@eLBati I don't know. I don't use Odoo 9 andi don't know it very well. Sorry.

2016-06-16 12:54 UTC, eLBati commented
@OpenCode no problem.

Lots handling and related tests should be fixed with https://github.com/OCA/stock-logistics-workflow/pull/199/commits/2def0c34a72e77efe9099efaa1f75f978b5457cf

2016-06-20 09:48 UTC, eLBati commented
Hello @gurneyalex , why the 'needs fixing' label?

2016-08-05 10:59 UTC, gurneyalex commented
@eLBati runbot was red. I've triggered a rebuild.

2016-08-05 11:03 UTC, gurneyalex commented
You need to update the version numbers in the __openerp__.py files (s/8.0/9.0/)

2016-08-05 12:15 UTC, eLBati commented
@gurneyalex thanks, done

2016-08-05 15:12 UTC, gurneyalex commented
@eLBati still can't figure out why runbot is red :crying_cat_face:

2016-08-31 14:55 UTC, eLBati commented
@gurneyalex just rebuilded runbot but ```stock_picking_package_preparation``` is not installable.
How can I help?

2016-09-07 15:05 UTC, gurneyalex commented
@eLBati what I just checked in #254 is that if your branch is merged with 9.0 then the CI tests are green. This can happen since the runbot does not merge, it really tests the branch so if you fork from a red build, you can get a red build on the PR. 

I'm :+1: on this, and I think we can move on and merge this.

2016-10-12 12:37 UTC, lasley requested changes
Thanks for the submission @eLBati - comments inline.

Please also rebase onto the current 9.0. If I am understanding the comments correctly, this should clear up the Runbot 🔴

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation/model/stock_picking_package_preparation.py
>      @api.one
api.one is deprecated, please remove all instances of it for api.multi

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation/security/package_preparation_security.xml
> +<openerp>
`<odoo noupdate="1">` & can remove data tag

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/OCA/
Please use new ReadMe template https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/__init__.py
> +##############################################################################
Please replace the old headers with the [new short one](https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3)

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/ir_config.py
> +class ResCompany(models.Model):
Please separate model by file

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/ir_config.py
> +class StockPickingPackagePreparationLineSettings(models.TransientModel):
Class name should be UpperCamelCase version of model.name

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/ir_config.py
> +    def default_get(self, cr, uid, fields, context=None):
Please use new api

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock.py
> +# -*- coding: utf-8 -*-
Please name this file `stock_move`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock.py
> +    def get_packs(self):
`@api.model`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +        'stock.picking.package.preparation', string='Stock Move',
required?

Also, this string attr duplicates `move_id` string. On purpose?

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +    move_id = fields.Many2one('stock.move', string='Stock Move',
required?

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +    product_uom = fields.Many2one('product.uom')
`product_uom_id` - all relation fields should end in _id or _ids, depending on whether they are x2m (_ids) or x2o (_id).

This also needs a string attribute

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +    def _prepare_lines_from_pickings(self, picking_ids):
`@api.model`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +class StockPickingPackagePreparation(models.Model):
Please either move this into its own file (preferred), or name the file `stock_picking_package_preparation.py`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +    def _update_line_vals(self, values):
`api.model`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +        # ----- Create a PackagePreparationLine for every stock move
Please use Python docblock styling instead of C style comments: `"""` vs `#`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +        # ----- Delete package preparation line if the relative picking is
Please use Python docblock styling instead of C style comments: `"""` vs `#`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +            # ----- Collect new pickings to read the change
Are all the `-----`s necessary? They dirty the code IMO

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +        # ----- Create a stock move and stock picking related with
Please use Python docblock styling instead of C style comments: `"""` vs `#`

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +                    raise exceptions.Warning(
Warning should be renamed as UserError per pylint-odoo. Admittedly don't know the reasoning, but I assume a planned change in the future

```
R8101	Import Warning should be renamed as UserError from openerp.exceptions import Warning as UserError
```

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/security/package_preparation_line_security.xml
> +<openerp>
`<odoo noupdate="1">` & can remove data tag

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/views/ir_config_view.xml
> +<openerp>
`<odoo>` & remove data tag

2016-10-12 12:37 UTC, lasley commented on stock_picking_package_preparation_line/views/stock_picking_package_preparation_line.xml
> +<openerp>
`<odoo>` & remove data tag

2016-10-18 14:30 UTC, OpenCode commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +            # ----- Collect new pickings to read the change
This is my style to comment :)

2016-10-18 14:37 UTC, eLBati commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +    move_id = fields.Many2one('stock.move', string='Stock Move',
It's not, because ```stock.picking.package.preparation.line``` can be descriptive, without being linked to a stock move

2016-10-18 15:10 UTC, lasley commented on stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
> +            # ----- Collect new pickings to read the change
Understood - I won't block over this, but I recommend removing. They add nothing to the code other than more maintenance. 

I am blocking on the Doc block comments though. Doc blocks are described in [PEP8](https://www.python.org/dev/peps/pep-0008/#documentation-strings) & [PEP237](https://www.python.org/dev/peps/pep-0257/)

2016-10-18 17:09 UTC, archetipo commented on stock_picking_package_preparation/model/stock_picking_package_preparation.py
> +            quants = preparation.env['stock.quant'].browse(
@eLBati 
package.get_content()  return a recordsets, is possible to do:
preparation.quant_ids = package.get_content()
?

2016-10-18 17:59 UTC, eLBati commented on stock_picking_package_preparation/model/stock_picking_package_preparation.py
> +            quants = preparation.env['stock.quant'].browse(
@archetipo in 9.0 ```get_content``` returns a list of IDs

2016-10-18 18:00 UTC, eLBati commented
@lasley thanks, I made the changes

2016-10-18 21:44 UTC, lasley approved these changes

2016-10-18 21:44 UTC, lasley commented
No clue what's up with Runbot

```
stock_picking_package_preparation_line: Unmet dependencies: stock_picking_package_preparation
```

But stock_picking_package_preparation is definitely set to installable 😑 

Code looks good though 👍

2016-10-18 21:48 UTC, lasley commented
Once we get another signoff on this (particularly the 🔴  runbot), would you mind squashing the logical commits too please?

2016-10-19 06:21 UTC, pedrobaeza commented
Maybe it's a runbot glitch... Let's merge and see the final result, but please first squash a bit the commits in a logical way.

2016-10-19 08:34 UTC, eLBati commented
@lasley @pedrobaeza rebased and squashed

2016-10-19 08:51 UTC, merged