[ADD][9.0] New module stock_picking_rate
OCA/stock-logistics-workflow pull request #238
Opened 2016-06-17 17:05 UTC by lasley

Hi Friends,

This module introduces a concept of rate quotes and purchasing on Stock Pickings. This is one of the modules yielded from the discussion in OCA/carrier-delivery#90.

I decided to put this in the `stock.picking.dispatch` namespace, because it seemed to fit best even without the `stock_picking_dispatch` module installed. Let me know if you have a better idea for naming. I will also be making a module to link this to `stock_picking_dispatch` so that rates can be purchased for the individual dispatchings.

Rate quotes can be seen in the stock.picking `Additional Info` tab. Clicking the green checkmark to the right of the rate will begin the purchase wizard. Completing the purchase wizard nets a purchase order for the rate, and marks the rate as purchased.

I don't really see anyone using this module on its own, as it would be kind of weird to make your own rate quotes then purchase them. It will be particularly useful with a connector module though, which fills the rates & triggers a true label purchase as part of the PO generation process.

2016-10-19 10:08 UTC, rousseldenis approved these changes
:+1: Tested on runbot. Seems great to use!

2016-10-19 12:38 UTC, pedrobaeza commented
Stock picking dispatch has been renamed to stock batch picking I'm afraid...

2016-10-19 14:44 UTC, lasley commented
Alright I'm just going to drop the `dispatch` suffix then, because the naming doesn't work with `stock_batch_picking`. It's not actually dependent, I was just trying to make the namespaces match

2016-12-06 00:12 UTC, susport commented on stock_picking_rate/models/stock_picking_rate.py
> +from openerp import models, fields, api
Order by name the import

2017-01-26 22:57 UTC, bmw95 commented on stock_picking_rate/tests/test_stock_picking_rate_purchase.py
> +        res = [r.id for r in rec_id.rate_ids]
@lasley when you have a chance can you take a look at this? It's returning an empty array, which is causing another test to fail.

2017-01-26 23:46 UTC, lasley commented on stock_picking_rate/tests/test_stock_picking_rate_purchase.py
> +        res = [r.id for r in rec_id.rate_ids]
cc @tedsalmon

2017-01-26 23:47 UTC, lasley commented on stock_picking_rate/tests/test_stock_picking_rate_purchase.py
> +        res = [r.id for r in rec_id.rate_ids]
Also this shoudl be `rec_id.rate_ids.ids`. But it would still be empty

2017-01-27 19:03 UTC, bmw95 commented
Woot the build is passing locally now. Although I think Travis is failing from something unrelated?

2017-01-27 19:27 UTC, lasley commented
Yes as long as OCA/OCB build passes, you can assume odoo/odoo error is - https://odoo-community.org/groups/contributors-15/contributors-49663?mode=thread&date_begin=&date_end=

2017-01-30 22:07 UTC, bmw95 commented
Updated

2017-02-03 04:45 UTC, obulkin requested changes
I'm seeing a few spots that may need changes, but generally, it LGTM.

2017-02-03 04:45 UTC, obulkin commented on stock_picking_rate/models/stock_picking_rate.py
> +    def _compute_is_purchased(self):
Seems like there should be a `depends` here.

2017-02-03 04:45 UTC, obulkin commented on stock_picking_rate/tests/test_stock_picking_rate_purchase.py
> +        vals = self.wizard_vals if vals is None else {}
This method is not getting used anywhere. Also, the first line seems wrong. As it stands, if the call includes an argument for `vals`, that argument won't be used and `vals` will simply be set to an empty dictionary.

2017-02-03 04:45 UTC, obulkin commented on stock_picking_rate/models/stock_picking_rate.py
> +    def buy(self):
Seems like overkill to wrap this up in a method. Is this done so that it can be overloaded later?

2017-02-03 17:31 UTC, lasley commented on stock_picking_rate/models/stock_picking_rate.py
> +    def buy(self):
Exactly, it's for overload. We now have a lot of these in v10 [API interface](https://github.com/odoo/odoo/blob/10.0/addons/delivery/models/delivery_carrier.py#L142)

2017-02-03 17:32 UTC, lasley commented on stock_picking_rate/tests/test_stock_picking_rate_purchase.py
> +        vals = self.wizard_vals if vals is None else {}
Remove if not used

2017-02-13 21:35 UTC, bmw95 commented
@obulkin Thanks! Updated.

2017-02-17 23:38 UTC, tedsalmon approved these changes
👍  LGTM! There was an issue with files having the executable bit set, but I took care of that :)

2017-03-01 23:03 UTC, obulkin approved these changes
Looks like my comments were addressed, so this should be good to go now. 👍

2017-03-21 17:26 UTC, lasley commented
@OCA/logistics-maintainers - Can a PSC please review this one? It's been sitting for a while & I would like to see merged so we can start forward port.

2017-03-22 20:44 UTC, pedrobaeza requested changes
The module name misses the main concept for this: delivery. The rate is for delivery, not for other thing, so the module should be called __stock_picking_delivery_rate__ IMO, and it should be hosted not here, but on https://github.com/oca/delivery-carrier

2017-03-22 20:44 UTC, pedrobaeza commented on stock_picking_rate/models/stock_picking_rate.py
> +                rec_id.date_purchased = fields.Datetime.now()
Isn't better to just write the date on the state change?

2017-03-22 20:44 UTC, pedrobaeza commented on stock_picking_rate/models/stock_picking_rate.py
> +        string='Est Delivery Date',
s/Est/Est.

2017-03-22 20:44 UTC, pedrobaeza commented on stock_picking_rate/models/stock_picking_rate.py
> +        self.state = 'purchase'
Here is where you should write the date

2017-03-22 20:44 UTC, pedrobaeza commented on stock_picking_rate/models/stock_picking_rate.py
> +                lambda r: r.id != rec_id.id
You can compare directly records without `.id`

2017-03-22 20:44 UTC, pedrobaeza commented on stock_picking_rate/tests/test_stock_picking_rate_purchase.py
> +        res = [r.id for r in rec_id.rate_ids]
Please change this

2017-03-22 21:29 UTC, lasley commented
@bmw95 - please see to Pedro's comments & move this PR to the correct repo when done

@tedsalmon - please take note for your dependent module(s)

2017-03-25 18:32 UTC, lasley commented
Closing in favor of OCA/delivery-carrier#119

2017-03-25 18:32 UTC, closed without merging