[FIX] Partially revert a83b66705e6d49ce33293c7b7164bd440da255b1
OCA/stock-logistics-workflow pull request #250
Opened 2016-08-24 07:28 UTC by codingforfun

+ Signature of function in inherited model doesn't match parent class
function signature. 

Code broken because of:
```
TypeError: _partial_move_for() got an unexpected keyword argument
'context'
```

2016-08-24 07:34 UTC, gurneyalex commented
ping @max3903 @ehdem you were involved in a83b66705e6d49ce33293c7b7164bd440da255b1 maybe you'd like to chime in :smile_cat:

2016-10-12 12:09 UTC, lasley commented
I feel like this should be fixed in the superclass. Isn't context a required aspect of the old api method signature?

2016-10-13 06:39 UTC, codingforfun commented
> I feel like this should be fixed in the superclass.

Would be better of course but since it's not the case in the core and they probably won't fix it I don't see the point in enforcing this inside a community model if that means that the community model is functional broken then. 

> Isn't context a required aspect of the old api method signature?

Probably should be, but in fact the core has plenty of functions that do not use the full method signature. Especially functions marked as private with `_` may have arbitrary signatures from what I see in the core code.

2016-10-13 10:06 UTC, lasley approved these changes
Thanks for the elaboration @codingforfun - Didn't realize the super was core, apologies for that.

👍

2016-10-13 10:07 UTC, pedrobaeza approved these changes

2016-10-13 10:22 UTC, tafaRU commented
Strange, the parent class method is https://github.com/odoo/odoo/blob/7.0/addons/stock/wizard/stock_partial_picking.py#L157, isn'it?
Please also see https://github.com/odoo/odoo/commit/c6a5be0a195c71c7ded9cc863815d115259abfd9

2016-10-13 12:15 UTC, lasley requested changes
@codingforfun - Can you please provide the full traceback from the error? @tafaRU comments allude to there being another module in play here.

2016-10-13 12:40 UTC, codingforfun commented
Ok. You are right. This has been long fixed in the core in https://github.com/odoo/odoo/commit/c6a5be0a. 
It seams I used a not up to date patched version of the core while trying this in a customer project. 
I should have cross checked this better. Sorry for the inconvenience.

2016-10-13 12:40 UTC, closed without merging