[ADD] Migrated stock_picking_reorder_line to v9.
OCA/stock-logistics-workflow pull request #262
Opened 2016-09-23 10:03 UTC by SerpentCS

2016-09-27 06:21 UTC, pedrobaeza commented
You should convert YML tests to Python ones, as they are deprecated

2016-09-27 06:21 UTC, pedrobaeza requested changes

2016-09-27 06:21 UTC, pedrobaeza commented on stock_picking_reorder_lines/README.rst
> +Configuration
Remove empty section.

2016-09-27 06:21 UTC, pedrobaeza commented on stock_picking_reorder_lines/README.rst
> + * stock_picking_reorder_lines (https://github.com/OCA/stock-logistics-workflow/)
This module is stock_picking_reorder_line, so there's no real dependency. Remove this.

2016-09-27 06:21 UTC, pedrobaeza commented on stock_picking_reorder_lines/__openerp__.py
> +    'version': '9.0.1.0.1',
This is the first 9.0 version, so 9.0.1.0.0

2016-09-27 06:21 UTC, pedrobaeza commented on stock_picking_reorder_lines/procurement.py
> +# Jordi Ballester Alomar
Only one line per copyright, so remove this one

2016-09-27 06:21 UTC, pedrobaeza commented on stock_picking_reorder_lines/stock.py
> +# Jordi Ballester Alomar
Only one line per copyright

2017-03-16 15:01 UTC, rousseldenis commented on stock_picking_line_sequence/__openerp__.py
> -    'depends': ['stock', 'sale', 'sale_stock'],
IMO, prefer explicit dependencies than implicit

2017-03-17 07:42 UTC, darshan-serpent commented
@jbeficent I have made new changes, could you please review?

2017-03-24 09:37 UTC, lreficent commented on stock_picking_line_sequence/README.rst
> +No specific installation requirements.
remove empty section.

2017-03-24 09:37 UTC, lreficent commented on stock_picking_line_sequence/README.rst
> +No configuration is required.
remove empty section.

2017-03-24 09:37 UTC, lreficent commented on stock_picking_line_sequence/__init__.py
> +# © 2015 Serpent Consulting Services Pvt. Ltd.
why 2015? is this that old?

2017-03-24 09:37 UTC, lreficent commented on stock_picking_line_sequence/models/stock.py
> +            rec._reset_sequence()
IMO this makes no sense, the sequence is required to be kept to compare when invoicing or with the sale order (related lines will have same sequence number). If I change a minor thing in the picking the sequence is reset and the relation is lost.

2017-05-29 14:11 UTC, Cedric-Pigeon commented
@SerpentCS Hello, do you plan to achieve this PR ?

2017-05-30 06:23 UTC, darshan-serpent commented
@Cedric-Pigeon Okay Yes, we will resume working on this.

2017-06-02 10:22 UTC, closed without merging

2017-06-12 13:03 UTC, aheficent commented
Hi @darshan-serpent  are you still planning to work on this one?

2017-06-12 13:24 UTC, darshan-serpent commented
Yes this was closed because I accidentally diverged the branch and then I tried to reset it to the OCA, which took back all the commits and this PR was closed automatically.

Maybe now I'll send a new one for the same.