10.0 mig stock picking package preparation
OCA/stock-logistics-workflow pull request #271
Opened 2016-10-19 15:37 UTC by archetipo

migrate:
 stock_picking_package_preparation
 stock_picking_package_preparation_line

2016-10-20 15:27 UTC, eLBati requested changes

2016-10-20 15:27 UTC, eLBati commented on stock_picking_package_preparation/model/stock_picking_package_preparation.py
>  # -*- coding: utf-8 -*-
@archetipo dir  ```model``` should be removed

2016-10-20 15:27 UTC, eLBati commented on stock_picking_package_preparation/view/stock_picking_package_preparation_view.xml
>  <?xml version="1.0" encoding="utf-8"?>
@archetipo dir ```view``` should be removed

2016-10-22 09:37 UTC, archetipo commented
@eLBati thnaks! done.

2017-01-27 16:23 UTC, eLBati commented on stock_picking_package_preparation/README.rst
> +.. branch is "10.0" for example
Please remove comment

2017-01-27 16:34 UTC, tafaRU commented on stock_picking_package_preparation/README.rst
> +.. branch is "10.0" for example
@eLBati, done.

2017-01-27 16:35 UTC, eLBati requested changes
I tried the following steps:
 - Create a new package preparation
 - Add a line in 'details' tab, selecting a product
 - Click 'put in pack'

Get 'Cannot find a location for Delivery Orders'

It seems this use case is not working in 9.0 also.
While it works in 8.0

2017-02-03 16:24 UTC, tafaRU commented
@eLBati, please see https://github.com/OCA/stock-logistics-workflow/pull/271/commits/520bf9676fe23bf11f33d0f795b98e30c578c2cd

2017-02-03 16:49 UTC, eLBati approved these changes
Thanks

2017-03-23 11:24 UTC, eLBati commented
Moving to https://github.com/OCA/stock-logistics-workflow/pull/318
Please close this one

2017-03-23 11:37 UTC, closed without merging