9.0 mig stock picking back2draft
OCA/stock-logistics-workflow pull request #276
Opened 2016-11-18 15:00 UTC by nicomacr

MIG v9 stock picking back2draft

2016-11-18 15:55 UTC, pedrobaeza commented on stock_picking_back2draft/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/154/8.0
s/8.0/9.0

2016-11-18 17:25 UTC, jjscarafia commented
:+1: tested on runbot

2016-11-19 13:24 UTC, pedrobaeza commented on stock_picking_back2draft/models/stock.py
> +        if self.filtered(lambda p: p.state != 'cancel'):
No need to do the check 2 times.

2016-11-21 14:33 UTC, Emiq2 approved these changes

2016-12-28 11:39 UTC, jjscarafia commented
Any news with this? One more reviewer please?

2016-12-28 17:52 UTC, pedrobaeza commented
Please squash together all the "OCA Transbot updated translations from Transifex" and the commit " 	remove en.po that was erroneously created by transbot" that it's also for translations and I'll merge.

2017-02-17 22:34 UTC, jbeficent commented
@lreficent can you review?
@nicomacr Can you squash the commits, as Pedro suggested? See here instructions on how to do that: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-transifex

2017-02-18 10:38 UTC, florian-dacosta commented
Hello,
I think this module is too simple and works only for a few cases, as it does not handle procurements.
It may have unexpected behavior for user in case of chained pickings for example no?

If we have a 2 steps delivery with manufactured product for instance, if you put the delivery order back to draft, it will recreate procurements, the previous chained picking, the manufactured order... And I guess the user just expects to put the Delivery order the same way as before because he canceled it by mistake! He may has already done the manufactured order and so on.

So I guess it works for very simple case only. I would not want to block this PR as in version 8, the funcionalities are the same, but I think it would be good to put a note in the README file to explain which cases are handled or not.

2017-02-27 09:05 UTC, jbeficent commented
@nicomacr Are you planning to follow up on this one? Otherwise we will continue the work

2017-03-14 14:18 UTC, lreficent commented
Forced rebuilt on runbot and still not working.

2017-03-21 15:20 UTC, LoisRForgeFlow approved these changes
Functional and technical review. LGTM

2017-03-21 15:25 UTC, lreficent commented
However, despite this works, I think what @florian-dacosta pointed is important and is not covered by this module.

2017-03-21 15:40 UTC, florian-dacosta commented
Yes, if you want to merge this module the way it is now, no problem, but please, add a comment in the README file to inform the users that it works only for simple picking (Not chained picking).

Or maybe raise a UserError if a user try to put a picking to draft state and at least one move has the field `procure_method` to `make_to_order` value? Because this mean it will re-create a procurement, and I don't think this is a wanted behavior.

2017-05-29 14:18 UTC, Cedric-Pigeon commented
@nicomacr Could integrate @florian-dacosta  remarks in order to merge this PR ?

2019-01-01 15:52 UTC, rousseldenis commented
@nicomacr

2019-01-21 15:35 UTC, rousseldenis commented
@nicomacr Could you squash all migration commits ?

2019-01-21 15:36 UTC, rousseldenis commented
@pedrobaeza Could you update your review?

2019-01-21 15:38 UTC, pedrobaeza commented
I still see a lot of noisy commits in the PR:
![seleccion_018](https://user-images.githubusercontent.com/7165771/51484098-f55a0f80-1d9a-11e9-94c5-31aeee17062f.png)

2019-01-21 15:42 UTC, rousseldenis commented
@pedrobaeza See my remark above. I was talking about README and stock.py files

2019-01-21 15:43 UTC, pedrobaeza commented
Yeah, but I want that commits to be squashed.

2019-01-21 15:50 UTC, Nikul-Chaudhary requested changes
Minor change

2019-01-21 15:50 UTC, Nikul-Chaudhary commented on stock_picking_back2draft/__openerp__.py
> +    "website": "https://www.agilebg.com",
@nicomacr URL should be https://github.com/OCA/stock-logistics-workflow

2019-01-21 16:25 UTC, nicomacr commented on stock_picking_back2draft/__openerp__.py
> +    "website": "https://www.agilebg.com",
Done!

2019-01-21 16:29 UTC, rousseldenis approved these changes
Code review

2019-01-22 13:14 UTC, nicomacr commented
@pedrobaeza done the squash in this PR.

2019-01-22 13:15 UTC, rousseldenis commented
@Nikul-Chaudhary

2019-01-22 13:17 UTC, merged

2019-01-22 13:17 UTC, pedrobaeza commented
Thanks.

2019-01-22 13:22 UTC, rousseldenis commented
@pedrobaeza Even if the modification was done, I'd prefer let time to reviewers that have made remarks to update their review and make PR's - as possible- with all green reviews before merge.

Be moderate (not too fast, not too slow) :smiley:

2019-01-22 13:25 UTC, pedrobaeza commented
Your points are not correct:

- Everything (runbot, Travis and codecov) is green
- There are not pending remarks
- Count my merge as second review

2019-01-22 13:33 UTC, rousseldenis commented
![image](https://user-images.githubusercontent.com/19529533/51538853-9fe13980-1e52-11e9-85c0-71fc2f2e1c68.png)
Missing Nik approval

2019-01-22 13:47 UTC, pedrobaeza commented
> Missing Nik approval

No, he hasn't put "Request changes" review and I have checked that his comment has been attended.