MIG 10 stock picking show return 02
OCA/stock-logistics-workflow pull request #287
Opened 2017-01-02 14:38 UTC by fmdl

2017-03-02 21:51 UTC, rousseldenis requested changes
Code review. Thanks for migration

2017-03-02 21:51 UTC, rousseldenis commented on stock_picking_show_return/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/154/9.0
10.0

2017-03-02 21:51 UTC, rousseldenis commented on stock_picking_show_return/__manifest__.py
> +    'version': '1.0',
Check version. See travis error.

2017-03-02 21:51 UTC, rousseldenis commented on stock_picking_show_return/tests/test_stock_picking_show_return.py
> +from openerp.tests import common
odoo

2017-03-02 22:03 UTC, rousseldenis requested changes
Typos.

Could you also rename your PR to be more 'attractive' for reviewers ?

2017-03-02 22:03 UTC, rousseldenis commented on stock_picking_show_return/__manifest__.py
> +    'version': '10.0.1.0',
Sorry, I should be clearer : 10.0.1.0.0

https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

2017-03-02 22:03 UTC, rousseldenis commented on stock_picking_show_return/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/154/10
Oups : '10.0' (test link)

2017-03-03 05:33 UTC, rousseldenis approved these changes
:+1: Code review + tested on runbot

2017-03-17 01:55 UTC, pedrobaeza requested changes
The branch is not correct and contains a lot of commits.

2017-03-17 01:56 UTC, pedrobaeza commented
Please include also the recent commit 80869362acda08bcfaa0fd46615a1a8f1376830c with a patch.

2017-03-17 06:48 UTC, fmdl commented
I know there lot of commit, but in V10 there are the bad folder : stock_picking_show_return**s** (for V8). Some one make a mistake during the creation of V10 branch (don't use the V9 branch). That why there are all commit. If not good, I can not fix that (I dont know the git command to do what you demand), please remove the stock_picking_show_return**s** folder and add the stock_picking_show_return (V9). After that I can put the new code for V10.

I don't know how add 8086936.

Regards

2017-03-17 09:39 UTC, pedrobaeza commented
No, there is no error. When 10.0 branch was created, the module wasn't still renamed. For making correctly, you only need to:

- Make an initial commit renaming the module without s.
- Follow migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
- Execute the command `git cherry-pick 80869362acda08bcfaa0fd46615a1a8f1376830c` for picking last commit.

2017-03-17 11:12 UTC, fmdl commented
I started from zero : https://github.com/OCA/stock-logistics-workflow/pull/313

2017-03-17 11:12 UTC, closed without merging