[8.0][NEW] stock_picking_backorder_to_sale: New module
OCA/stock-logistics-workflow pull request #293
Opened 2017-01-19 16:03 UTC by carlosdauden

Create a new sale order from picking and cancel this picking

@Tecnativa

2017-01-19 17:31 UTC, pedrobaeza commented
Please check Travis status

2017-01-23 09:09 UTC, LoisRForgeFlow requested changes

2017-01-23 09:09 UTC, lreficent commented on stock_picking_backorder_to_sale/README.rst
> +#. Press *Create Sale* button
This numbered list is not showing properly.

2017-01-23 09:09 UTC, lreficent commented on stock_scanner/hardware/sentinel.py
> +
This is another module.

2017-01-23 09:09 UTC, lreficent commented on stock_scanner/load_scenario.py
> +
Again another module.

2017-01-23 09:09 UTC, lreficent commented on stock_picking_backorder_to_sale/views/stock_view.xml
> +                    attrs="{'invisible': [('state', '=', 'done')]}"/>
I don't know if it have too much sense to be able to use this from an internal transfer or a receipt, it may lead to wrong workflow.

2017-01-23 09:16 UTC, pedrobaeza commented on stock_picking_backorder_to_sale/README.rst
> +#. Go to *Warehouse > All Operations*
You have to put a line between.

2017-05-02 15:45 UTC, pedrobaeza commented
@chienandalu @luismontalba Please review

2017-05-02 17:55 UTC, chienandalu commented on stock_picking_backorder_to_sale/README.rst
> +#. Select a operation don't done with partner
I'd suggest the second usage point to be expressed better something like "Select an undone operation with partner set"

2017-05-02 17:56 UTC, chienandalu approved these changes
functionality tested on runbot

2017-05-03 18:07 UTC, luismontalba approved these changes
Functionality tested on runbot

2017-05-04 08:16 UTC, merged

2017-05-04 08:20 UTC, rousseldenis commented
@pedrobaeza I think there is a mix between LGPL and AGPL headers in this

2017-05-04 08:21 UTC, pedrobaeza commented
You're right. Well, it's only the flag (the module and code is marked AGPL), but I'll fix it ASAP.

2017-05-04 08:23 UTC, pedrobaeza commented
Fixed in https://github.com/OCA/stock-logistics-workflow/commit/d425234d966fd00fcf51587e309aa2acda3f7b73