[9.0][ADD] stock_picking_operation_quick_change: New module to allow change target location in picking operations
OCA/stock-logistics-workflow pull request #299
Opened 2017-02-09 09:30 UTC by sergio-teruel

cc @Tecnativa
Thanks.

2017-02-11 08:34 UTC, cubells approved these changes
Code review and test in runbot.

:+1:

2017-03-02 21:35 UTC, rousseldenis requested changes
Code review + tested on runbot.
Great usability improvement in real life !
Do you plan v10 too ?

2017-03-02 21:35 UTC, rousseldenis commented on stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> +    def _prepare_deafault_values(self, picking):
IMO, even if function names should be at developer choice, avoid spelling faults ('default')

2017-03-02 21:35 UTC, rousseldenis commented on stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> +        res.update(self._prepare_deafault_values(picking))
See here above

2017-03-03 11:22 UTC, sergio-teruel commented
@rousseldenis Changes done.
About the migration, i think that it is a direct migration... (I would have to analyze it)
If you want, you can do it... :smile:

2017-03-03 11:32 UTC, rousseldenis approved these changes
@sergio-teruel Think I'll do it as I need it ;-)

2017-03-03 11:33 UTC, jbeficent commented
May I ask, what is the use case in real life? Why do you need it?

On Mar 2, 2017 10:35 PM, "Denis Roussel (ACSONE)" <notifications@github.com>
wrote:

> *@rousseldenis* requested changes on this pull request.
>
> Code review + tested on runbot.
> Great usability improvement in real life !
> Do you plan v10 too ?
> ------------------------------
>
> In stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> <https://github.com/OCA/stock-logistics-workflow/pull/299#discussion_r104034941>
> :
>
> > @@ -0,0 +1,85 @@
> +# -*- coding: utf-8 -*-
> +# © 2017 Sergio Teruel <sergio.teruel@tecnativa.com>
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
> +
> +from openerp import _, api, fields, models
> +from openerp.exceptions import UserError
> +
> +
> +class StockPickingOperationWizard(models.TransientModel):
> +    _name = 'stock.picking.operation.wizard'
> +
> +    def _prepare_deafault_values(self, picking):
>
> IMO, even if function names should be at developer choice, avoid spelling
> faults ('default')
> ------------------------------
>
> In stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
> <https://github.com/OCA/stock-logistics-workflow/pull/299#discussion_r104035030>
> :
>
> > +from openerp.exceptions import UserError
> +
> +
> +class StockPickingOperationWizard(models.TransientModel):
> +    _name = 'stock.picking.operation.wizard'
> +
> +    def _prepare_deafault_values(self, picking):
> +        return {'location_dest_id': picking.location_dest_id.id}
> +
> +    @api.model
> +    def default_get(self, fields):
> +        res = super(StockPickingOperationWizard, self).default_get(fields)
> +        active_model = self.env.context['active_model']
> +        active_ids = self.env.context['active_ids'] or []
> +        picking = self.env[active_model].browse(active_ids)
> +        res.update(self._prepare_deafault_values(picking))
>
> See here above
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/stock-logistics-workflow/pull/299#pullrequestreview-24848695>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHU_Vi5aX84fDSCxr4XKz2qSSgsExm03ks5rhzY6gaJpZM4L75F2>
> .
>

2017-03-03 11:36 UTC, rousseldenis commented
e.g. : you have a transfer to Output Location.
This Location contains several sub-locations.
You want to put your pack in sub-location 1 and have several operations in the picking.
So, to do it as mass assignation is time earned.

2017-03-03 11:44 UTC, jbeficent commented
Ok, thanks!

On Mar 3, 2017 12:36 PM, "Denis Roussel (ACSONE)" <notifications@github.com>
wrote:

> e.g. : you have a transfer to Output Location.
> This Location contains several sub-locations.
> You want to put your pack in sub-location 1 and have several operations in
> the picking.
> So, to do it as mass assignation is time earned.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/stock-logistics-workflow/pull/299#issuecomment-283932581>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHU_VggfHieatGs9wVVDkUSI4DBgHqDwks5rh_szgaJpZM4L75F2>
> .
>

2017-03-03 12:32 UTC, sergio-teruel commented
@rousseldenis If you start the work, please notify me it.. ok? Thanks...

2017-03-10 14:21 UTC, rousseldenis commented
@jbeficent Can you review ?

2017-03-24 16:30 UTC, luismontalba approved these changes
Functionality tested on runbot

2017-03-24 16:34 UTC, merged