[10.0] Add module product_expiry_simple
OCA/stock-logistics-workflow pull request #302
Opened 2017-02-13 10:35 UTC by alexis-via

See README for more details about the module.

2017-02-14 08:27 UTC, simahawk requested changes
Just code review, no test.
LGTM but the small change for computing method ;)

2017-02-14 08:27 UTC, simahawk commented on product_expiry_simple/models/stock_production_lot.py
> +        compute='compute_display_name_field',
Just a nitpicking request: change compute method name respecting [contrib rule](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#field) for such field: `Compute Field: the compute method pattern is _compute_<field_name>`

2017-02-14 08:30 UTC, simahawk reviewed
@alexis-via BTW what's the goal of the module and what you achieve really installing it? I understood it from the code but the README should explain what you get, not just how is different from the official one, isn't it? :)

2017-04-26 15:19 UTC, alexis-via commented on product_expiry_simple/models/stock_production_lot.py
> +        compute='compute_display_name_field',
I named it that way on purpose: if you call the method compute_display_name, you have a warning in the logs of odoo v10 (this is something specific to display_name).

2017-04-28 13:08 UTC, alexis-via commented
@simahawk I improved the README as suggested

2017-04-28 13:34 UTC, cdubuit approved these changes

2017-04-28 13:47 UTC, simahawk commented on product_expiry_simple/models/stock_production_lot.py
> +        compute='compute_display_name_field',
I see. Good to know :)

2017-04-28 13:47 UTC, simahawk approved these changes

2017-05-02 07:32 UTC, merged