[9.0][ADD] stock_picking_backorders
OCA/stock-logistics-workflow pull request #321
Opened 2017-04-06 15:26 UTC by lreficent

Stock Picking Backorders
===================

This module provide a new field on stock pickings, allowing to see the
backorders associated to a picking.

Usage
=====

To use this module, you need to:

#. Go to 'Inventory' and create a picking.
#. Edit the 'Done' quantity of some operation line to be less than the 'To
   Do' quantity.
#. Save, validate and 'Create Backorder'.
#. A new page in the notebook has appeared with a list of the picking that
   are backorders of this picking.

2017-04-06 15:31 UTC, pedrobaeza commented
Please don't use plurals as stated on contribution guidelines. A better name following other modules can be _stock_picking_show_backorder_

2017-04-06 15:36 UTC, lreficent commented
@pedrobaeza Just realized about the plurals after pushing  :sweat_smile: I've just changed it, but maybe the name you propose is also better, I'll change again.

2017-05-04 02:23 UTC, lasley approved these changes
Code no test

2017-05-04 06:40 UTC, sebalix approved these changes
Helpful, should be a standard feature. :+1:

2017-05-04 07:15 UTC, pedrobaeza requested changes

2017-05-04 07:15 UTC, pedrobaeza commented on stock_picking_show_backorder/README.rst
> +    :alt: License: AGPL-3
Provide link as in the template: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2017-05-04 07:15 UTC, pedrobaeza commented on stock_picking_show_backorder/__openerp__.py
> +    'summary': "Provide a new field on stock pickings, allowing to display "
s/Provide/Provides

2017-05-04 07:27 UTC, rousseldenis approved these changes
:+1: Code review

2017-05-04 07:51 UTC, lreficent commented
@pedrobaeza this is updated

2017-05-04 08:10 UTC, pedrobaeza approved these changes

2017-05-04 08:10 UTC, merged