10.0 mig stock_picking_invoice_link
OCA/stock-logistics-workflow pull request #322
Opened 2017-04-10 14:26 UTC by eLBati

2017-06-15 11:01 UTC, pedrobaeza commented
Please squash some commits together (like "OCA Transbot" ones), and take into account https://github.com/OCA/stock-logistics-workflow/pull/296

2017-06-23 07:45 UTC, eLBati commented
Hi @pedrobaeza , squashed some commits.
Also, this PR is already based on https://github.com/OCA/stock-logistics-workflow/pull/296 and, since 10 april, no commits were added

2017-07-06 11:25 UTC, grindtildeath requested changes
Works great, just a few things to change though.

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/views/account_invoice_view.xml
> +<openerp>
odoo

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/views/account_invoice_view.xml
> +    <data>
To remove

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/views/stock_view.xml
>  <openerp>
odoo

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/views/stock_view.xml
> +    <data>
To remove

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
> +from openerp.addons.sale.tests.test_sale_common import TestSale
odoo.addons

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/models/stock_picking.py
> +from openerp import api, fields, models
from odoo

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/models/stock_move.py
> +from openerp import api, fields, models
from odoo

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/models/sale_order.py
> +from openerp import api, models
from odoo

2017-07-06 11:25 UTC, grindtildeath commented on stock_picking_invoice_link/models/account_invoice.py
> +from openerp import fields, models
from odoo

2017-07-14 14:12 UTC, eLBati commented
Moving to https://github.com/OCA/stock-logistics-workflow/pull/347

@grindtildeath thanks, fixed there

2017-07-14 14:12 UTC, closed without merging