modules packing_product_change and product_equivalence ported to version 10
OCA/stock-logistics-workflow pull request #336
Opened 2017-05-30 14:45 UTC by abaghirli

2017-06-01 09:38 UTC, yvaucher requested changes

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/__init__.py
> +##############################################################################
You can remove the header from `__init__.py` file

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/wizard/replace_product_view.xml
> +    <data>
In odoo 10.0

replace
``` xml
<openerp>
    <data>
```

by a single tag

``` xml
<odoo>
```

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/wizard/replace_product_view.xml
> +                        or
Please remove the `or` this has been removed from all wizards since odoo 8.0

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/__manifest__.py
> +    "wizard/replace_product_view.xml",
packing_product_change/__manifest__.py:15:5: E121 continuation line under-indented for hanging indent

Add 1 space here

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/__manifest__.py
> +    "views/stock_view.xml",
packing_product_change/__manifest__.py:17:9: E126 continuation line over-indented for hanging indent

Add 1 space here

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/sale.py
> +                      move.old_product_id != move.product_id:
packing_product_change/models/sale.py:82:23: E126 continuation line over-indented for hanging indent

Here you 5 spaces before move.old_product_id. 

prefer to write this like this with parenthesis and a multiple of 4 on second line:

``` python
if (move.old_product_id and
        move.old_product_id != move.product_id):
```

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/sale.py
> +            lang = partner_obj.browse(self.order_id.partner_id.id,).lang
No need to browse.

Directly use:

`self.order_id.partner_id.lang`

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/sale.py
> +            self.env.context = ctx
Don't assign context this way.

Here you must use `with_context`

https://www.odoo.com/documentation/10.0/reference/orm.html#altering-the-environment

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/wizard/__init__.py
> +##############################################################################
Here you can remove this header

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/sale.py
> +# Copyright 2017 Camptocamp
This module was created long time ago, please but the previous years before it

2010-2012, 2017

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/README.rst
> +* "Odoo Community Association (OCA)",
Here please list the following contributors:

* Joël Grand-Guillaume <joel.grandguillaume@camptocamp.com> 
* Guewen Baconnier <guewen.baconnier@camptocamp.com>
* Anar Baghirli

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/__manifest__.py
> +           "Serv. Tecnol. Avanzados - Pedro M. Baeza, "
As far as I know @pedrobaeza  didn't contribute to this module as it comes from http://bazaar.launchpad.net/~camptocamp/c2c-ecom-addons/7.0/view/head:/packing_product_change/__openerp__.py. This line to be removed.

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/sale.py
> +#     _inherit = 'sale.order.line'
Commented lines of code to clean up

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/stock.py
> +# ???????????? ported this method but was unable to find similar
Commented former code to remove

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/views/stock_view.xml
> +    <data>
Use `<odoo>` instead

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/stock.py
> +            self.write(data)
Here you want to use `move` instead of `self` otherwise if `self` is a record set of multiple records it will do a write on each loop on all moves.

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/wizard/replace_product_view.xml
> +            <form string="Replace Product" version="7.0">
`version="7.0"` to remove

2017-06-01 09:38 UTC, yvaucher commented on product_equivalence/README.rst
> +* "Odoo Community Association (OCA)",
Here please list the following contributors:

     *  Nicolas Bessi <nicolas.bessi@camptocamp.com>
     * Yannick Vaucher <yannick.vaucher@camptocamp.com>
     * Guewen Baconnier <guewen.baconnier@camptocamp.com>
     * Anar Baghirli

2017-06-01 09:38 UTC, yvaucher commented on product_equivalence/__manifest__.py
> +           "Serv. Tecnol. Avanzados - Pedro M. Baeza, "
This line to be removed

2017-06-01 09:38 UTC, yvaucher commented on product_equivalence/models/product.py
> +# from openerp.osv import orm, fields
Commented line to remove

2017-06-01 09:38 UTC, yvaucher commented on product_equivalence/models/stock.py
> +                    self.replace_product(move.product_id.equivalent_id.id)
s/self/move

2017-06-01 09:38 UTC, yvaucher commented on product_equivalence/views/product_view.xml
> +  <data>
`<data>` tag to remove

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/views/stock_view.xml
> +                      string="Replace the product" type="action"
Prefer `name="replace_product" ... type="object"

2017-06-01 09:38 UTC, yvaucher commented on packing_product_change/models/stock.py
> +                                ' on a delivered or canceled move!'))
Add 2 spaces here to be on the right level of parenthesis

2017-06-01 09:39 UTC, yvaucher commented
Thanks for the porting, some stuff to fix in addidion to the pep8

2017-06-08 11:24 UTC, yvaucher requested changes
One error to fix when looping on records and few other nitpicking. Otherwise LGTM

2017-06-08 11:24 UTC, yvaucher commented on product_equivalence/README.rst
> +* "Odoo Community Association (OCA)",
You can remove Camptocamp and Odoo Community Association from this list. We put them in author in order to have them displayed in apps.odoo.com and we want only individuals here.

2017-06-08 11:24 UTC, yvaucher commented on packing_product_change/README.rst
> +* "Odoo Community Association (OCA)",
You can remove Camptocamp and OCA from this list, we keep only individuals.

2017-06-08 11:24 UTC, yvaucher commented on packing_product_change/README.rst
> +* Anar Baghirli a.baghirli@mobilunity.com
please put emails between <>

2017-06-08 11:24 UTC, yvaucher commented on packing_product_change/wizard/replace_product.py
> +# from openerp.osv import orm, fields
Please remove this line

2019-05-12 09:44 UTC, rousseldenis commented
@abaghirli Do you plan to finish this? Could you a little bit squash your commits to keep relevant ones ?

2019-05-28 08:13 UTC, rousseldenis commented
Closing this. Please feel free to reopen it if you want to finish it

2019-05-28 08:13 UTC, closed without merging