[9.0][IMP]stock_pack_operation_auto_fill: fill operations automatically
OCA/stock-logistics-workflow pull request #361
Opened 2017-09-06 10:55 UTC by zakiuu

Check issue https://github.com/OCA/stock-logistics-workflow/issues/360

2017-09-07 07:39 UTC, LoisRForgeFlow requested changes
Tested on runbot and works fine but you have to finish the documentation.

2017-09-07 07:39 UTC, lreficent commented on stock_pack_operation_auto_fill/README.rst
> +In this module we have added a button that helps users to fill automatically
Extra Line above this to be displayed as different paragraphs.

2017-09-07 07:39 UTC, lreficent commented on stock_pack_operation_auto_fill/README.rst
> +#. Go to ...
You have to complete the README...

2017-09-07 08:20 UTC, rousseldenis requested changes
Minor comment. LGTM

2017-09-07 08:20 UTC, rousseldenis commented on stock_pack_operation_auto_fill/views/stock_picking.xml
> +                <button name="action_pack_operation_auto_fill"
Maybe a help (with a short explanation on the not filling in case of lots and already filled quantities)

2017-09-07 09:16 UTC, zakiuu commented
@rousseldenis @lreficent done

2017-09-08 06:56 UTC, lmignon requested changes

2017-09-08 06:56 UTC, lmignon commented on stock_pack_operation_auto_fill/models/stock_picking.py
> +        self.ensure_one()
@zakiuu Why to you restrict the use of this method to `self.ensure_one`? I do not see why it could not be called on a recordset.

2017-09-08 11:06 UTC, LoisRForgeFlow requested changes

2017-09-08 11:06 UTC, lreficent commented on stock_pack_operation_auto_fill/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/{repo_id}/{branch}
`https://runbot.odoo-community.org/runbot/154/9.0`

2017-09-08 11:06 UTC, lreficent commented on stock_pack_operation_auto_fill/README.rst
> +.. repo_id is available in https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt
remove this

2017-09-08 11:06 UTC, lreficent commented on stock_pack_operation_auto_fill/README.rst
> +<https://github.com/OCA/{project_repo}/issues>`_. In case of trouble, please
fill project repo

2017-09-08 11:06 UTC, lreficent commented on stock_pack_operation_auto_fill/README.rst
> +======================
If empty better to remove

2017-09-08 11:06 UTC, lreficent commented on stock_pack_operation_auto_fill/__openerp__.py
> +    ],
If empty better to remove

2017-09-10 12:55 UTC, zakiuu commented
@lmignon @lreficent done!

2017-09-11 07:01 UTC, ThomasBinsfeld approved these changes
Nitpicking comments, LGTM.

2017-09-11 07:01 UTC, ThomasBinsfeld commented on stock_pack_operation_auto_fill/README.rst
> +the schedulled quanties. Then, the user can just change back
@zakiuu s/quanties/quantities

2017-09-11 07:01 UTC, ThomasBinsfeld commented on stock_pack_operation_auto_fill/models/stock_picking.py
> +        if self.filtered(lambda r: not r.action_pack_op_auto_fill_allowed):
@zakiuu I would use `any` instead of `filtered`.

2017-09-12 09:04 UTC, LoisRForgeFlow approved these changes
LGTM now

2017-09-13 07:25 UTC, rousseldenis requested changes

2017-09-13 07:25 UTC, rousseldenis commented on stock_pack_operation_auto_fill/models/stock_picking.py
> +        for op in self.mapped('pack_operation_ids'):
@zakiuu Maybe a filtered here to have one continue (less code)

2017-09-13 07:28 UTC, jbeficent commented
@rgarnau can you review?

2017-09-13 10:55 UTC, rgarnau requested changes
Functional and code review (few comments inline)

2017-09-13 10:55 UTC, rgarnau commented on stock_pack_operation_auto_fill/__openerp__.py
> +    'website': 'https://acsone.eu/',
In website should be https://github.com/OCA/stock-logistics-workflow according to https://github.com/OCA/maintainer-tools/blob/f036ab8c259298769926fd98bad0c7e4fe980608/template/module/__openerp__.py#L9

2017-09-13 10:55 UTC, rgarnau commented on stock_pack_operation_auto_fill/models/stock_picking.py
> +        readonly=True
Trailing comma

2017-09-13 10:55 UTC, rgarnau commented on stock_pack_operation_auto_fill/views/stock_picking.xml
> +                            help="This button will automatically fill all operations that has no tracking set on the product, no processed qty and no selected package."/>
Should be "all operations that have", no?

2017-09-14 11:40 UTC, rousseldenis approved these changes
Code review

2017-09-14 11:49 UTC, zakiuu commented
ping @lmignon @rgarnau

2017-09-15 07:49 UTC, rgarnau approved these changes

2017-09-15 09:35 UTC, JordiBForgeFlow approved these changes
:+1: Technical and functional review

Great addition!

2017-09-15 09:36 UTC, jbeficent commented
@zakiuu Can you squash your commits?

2017-09-15 10:30 UTC, zakiuu commented
@jbeficent thanks, the squashed is done!

2017-09-18 11:48 UTC, merged