[FIX] stock_plit_picking: do not write date_done when splitting closes
OCA/stock-logistics-workflow pull request #379
Opened 2017-10-13 09:25 UTC by oihane

issue #375

Proposed change to odoo / ocb
https://github.com/OCA/OCB/pull/661
https://github.com/odoo/odoo/pull/20131

2018-05-12 07:19 UTC, rousseldenis requested changes
Code review

2018-05-12 07:19 UTC, rousseldenis commented on stock_split_picking/model/stock.py
> +            del values['date_done']
@oihane Please add test

2018-06-25 12:41 UTC, oihane commented on stock_split_picking/model/stock.py
> +            del values['date_done']
@rousseldenis test added

2019-05-12 09:52 UTC, rousseldenis approved these changes
Code review.
@oihane Is this ok ?

2019-05-13 10:27 UTC, oihane commented
:+1: perfect

2019-05-28 08:18 UTC, rousseldenis commented
As very old, but tests are ok, merging this

2019-05-28 08:18 UTC, merged