11.0 mig stock pack operation auto fill
OCA/stock-logistics-workflow pull request #399
Opened 2018-01-17 00:55 UTC by luistriana28

@pedrobaeza Could you review this aportation?

Best Regards

2018-01-17 01:09 UTC, pedrobaeza commented
Hi, Luis, thanks for the contribution!

I'm not able to review all the PRs that incomes, but for sure if there's interest other will review it. You can also review other PRs and ask in exchange that they review yours.

2018-01-18 10:39 UTC, LoisRForgeFlow requested changes
Thanks for the migration! See my comments inline plus:

* You should remove all `# -*- coding: utf-8 -*-` as it is not needed in python3.
* Squash together all transifex commits to reduce history lenght.

Always good to have a look to the [migration guide](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0)

2018-01-18 10:39 UTC, lreficent commented on stock_pack_operation_auto_fill/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/154/9.0
11.0

2018-01-18 10:39 UTC, lreficent commented on stock_pack_operation_auto_fill/__manifest__.py
> +    'version': '10.0.1.0.1',
11.0.1.0.0

2018-01-19 16:15 UTC, alan196 requested changes
Runbot is in warning due the following message:
`The 'phonenumbers' Python module is not installed. Try: pip install phonenumbers.`

2018-01-19 16:15 UTC, alan196 commented on stock_pack_operation_auto_fill/models/__init__.py
> +from . import stock_picking
`# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).`

2018-01-19 16:15 UTC, alan196 commented on stock_pack_operation_auto_fill/models/stock_picking.py
> +from odoo import api, fields, models, _
`from odoo import _, api, fields, models`

2018-01-19 16:15 UTC, alan196 commented on stock_pack_operation_auto_fill/tests/__init__.py
> +from . import test_stock_picking
`# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).`

2018-01-22 18:34 UTC, alan196 approved these changes
👍 Technical review.
👍 Functional test.

2018-01-23 13:45 UTC, lreficent commented
Functional review is fine :+1: , waiting for the [CLAs](https://github.com/OCA/stock-logistics-workflow/pull/399#issuecomment-358158599) before approving

2018-01-23 17:26 UTC, luistriana28 commented
@lreficent 

I already sent it! 

Regards!

2018-01-23 17:28 UTC, lasley commented
ICLA for @luistriana28 confirmed

2018-01-24 09:39 UTC, LoisRForgeFlow approved these changes
Great, thanks for the migration!

2018-01-31 22:16 UTC, ougc27 approved these changes
:+1: Tested on runbot!

2018-02-01 14:05 UTC, merged