[WIP][11.0] Add module stock picking restrict cancel dest move
OCA/stock-logistics-workflow pull request #427
Opened 2018-05-11 11:39 UTC by grindtildeath

2018-05-14 07:44 UTC, simahawk requested changes
LGTM, small things

2018-05-14 07:44 UTC, simahawk commented on stock_picking_restrict_cancel_with_orig_move/__manifest__.py
> +    "author": "Camptocamp SA, Odoo Community Association (OCA)",
remove SA

2018-05-14 07:44 UTC, simahawk commented on stock_picking_restrict_cancel_with_orig_move/models/stock_move.py
> +                or self.env.context.get('bypass_check_state')):
ctx key check should the 1st thing to do to avoid all the rest if not needed.

2018-05-16 12:01 UTC, tschanzt approved these changes

2018-05-17 07:43 UTC, jgrandguillaume approved these changes
LGMT ! Thanks (fct + code review)

2018-05-19 01:43 UTC, pedrobaeza commented
Merging this module, but this maybe can be proposed at least for master for fixing the behavior upstream.

2018-05-19 01:43 UTC, merged