[11.0] Allow cancellation of stock.move when applying push rules
OCA/stock-logistics-workflow pull request #444
Opened 2018-07-18 15:53 UTC by grindtildeath

TODO :
 - [ ] Add test

2018-07-18 21:54 UTC, max3903 approved these changes

2018-07-19 05:55 UTC, simahawk requested changes
small - not blocking - request: put yourself in out-of-context-ppl shoes and it your future shoes within 1 year and drop a small explanation :wink:

2018-07-19 05:55 UTC, simahawk commented on stock_picking_restrict_cancel_with_orig_move/tests/test_restrict_cancel.py
> +        # qc_to_stock_move has merged all the moves so it's quantity is 5
*its

2018-07-19 05:55 UTC, simahawk commented on stock_picking_restrict_cancel_with_orig_move/tests/test_restrict_cancel.py
> +        self.env['stock.picking'].create({
a comment on the pre-conditions on why this should work as tested would be nice :)

2018-07-24 15:10 UTC, max3903 commented
@simahawk Can you update your review please?

2018-07-25 07:54 UTC, simahawk approved these changes

2018-07-25 13:08 UTC, merged