[10.0][ADD] stock_change_price_at_date
OCA/stock-logistics-workflow pull request #462
Opened 2018-10-17 12:43 UTC by rousseldenis

2018-10-18 08:28 UTC, rousseldenis commented
@Cedric-Pigeon

2018-10-18 08:41 UTC, Cedric-Pigeon requested changes
Small remarks

2018-10-18 08:41 UTC, Cedric-Pigeon commented on stock_change_price_at_date/models/product_product.py
> +        return super(ProductProduct, self - products_to_write).write(vals)
what if `self - products_to_write` leads to an empty recordset ?

2018-10-18 08:41 UTC, Cedric-Pigeon commented on stock_change_price_at_date/tests/test_change_price_at_date.py
> +        if template:
I would protect this method by `self.ensure_one()`

2018-10-18 08:41 UTC, Cedric-Pigeon commented on stock_change_price_at_date/tests/test_change_price_at_date.py
> +        product_domain = [('product_id', '=', self.product.id)]
Same remark hre, I would ensure a singleton

2018-10-22 07:59 UTC, rousseldenis commented on stock_change_price_at_date/tests/test_change_price_at_date.py
> +        if template:
Test function

2019-01-01 16:26 UTC, rousseldenis commented
@Cedric-Pigeon

2019-01-02 15:36 UTC, Cedric-Pigeon approved these changes

2019-01-03 14:38 UTC, LoisRForgeFlow approved these changes
Tested on runbot

2019-01-03 14:49 UTC, merged