[11.0][ADD] stock_picking_auto_create_lot: Create lot for incoming pickings
OCA/stock-logistics-workflow pull request #463
Opened 2018-10-22 12:26 UTC by sergio-teruel

cc @Tecnativa

2018-10-23 08:04 UTC, rousseldenis requested changes
Code review. Minor comment

2018-10-23 08:04 UTC, rousseldenis commented on stock_picking_auto_create_lot/models/stock_picking.py
> +        if self.picking_type_code == 'incoming':
@sergio-teruel IMHO to be flexible, this should be an option in stock.picking.type (doing this you limit lot auto creation to incoming pickings).

So,

```suggestion
        if self.picking_type_id.auto_create_lot:
```

2018-10-23 08:04 UTC, rousseldenis commented on stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
> +    post_install = True
I don't think this module breaks normal behaviour

2018-10-24 20:38 UTC, sergio-teruel commented
@rousseldenis Changes done!!. About add field to operation types, I was a bit lazy... :smiley:

2018-10-30 21:55 UTC, rousseldenis approved these changes
LGTM. Code review

2018-10-30 22:51 UTC, pedrobaeza approved these changes

2018-10-30 22:51 UTC, merged