[11.0][ADD] stock_picking_deactivate_immediate_transfer
OCA/stock-logistics-workflow pull request #486
Opened 2018-12-21 09:13 UTC by ageficent

Adds module stock_picking_deactivate_immediate_transfer

2018-12-21 09:36 UTC, rousseldenis requested changes
Tested on runbot :+1: 
Minor comments

2018-12-21 09:36 UTC, rousseldenis commented on stock_picking_deactivate_immediate_transfer/__manifest__.py
> +    'website': 'http://www.eficent.com',
Please change this to https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L11

2018-12-21 09:36 UTC, rousseldenis commented on stock_picking_deactivate_immediate_transfer/__manifest__.py
> +}
Maybe you could improve it with some missing entries https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py

2018-12-21 10:06 UTC, rousseldenis approved these changes

2018-12-28 15:20 UTC, LoisRForgeFlow approved these changes
Functional and technical review :+1: 

Thanks!

2018-12-28 15:20 UTC, merged