[8.0][ADD] Backport stock_picking_send_by_mail from 9.0
OCA/stock-logistics-workflow pull request #492
Opened 2019-01-23 14:06 UTC by quentinDupont

Backport from 9.0 to 8.0

2019-01-23 16:21 UTC, Nikul-Chaudhary requested changes
Improve Code

2019-01-23 16:21 UTC, Nikul-Chaudhary commented on stock_picking_send_by_mail/__openerp__.py
> +    "version": "8.0.1.0.0",
@quentinDupont Add website key : `https://github.com/OCA/stock-logistics-workflow`

2019-01-23 16:21 UTC, Nikul-Chaudhary commented on stock_picking_send_by_mail/data/stock_picking_mail.xml
> +</openerp>
and new blank line

2019-01-23 16:21 UTC, Nikul-Chaudhary commented on stock_picking_send_by_mail/views/stock_picking_view.xml
> +</openerp>
also here

2019-01-25 09:42 UTC, quentinDupont commented
> Improve Code

Thanks ! Here is the new commit with the changes.
Do i need to squash the commits ?

2019-01-25 09:54 UTC, rousseldenis commented
@quentinDupont Yes and you can rename IMHO the commit to "[8.0][MIG] stock_picking_send_by_mail: Backport from 9.0"

2019-02-06 16:41 UTC, rousseldenis commented
@quentinDupont Could you check travis?

2019-02-06 18:15 UTC, Nikul-Chaudhary commented
> > Improve Code
> 
> Thanks ! Here is the new commit with the changes.
> Do i need to squash the commits ?

Yes, Need to squashed

2019-02-07 14:22 UTC, quentinDupont commented
> @quentinDupont Could you check travis?

Ok so i check travis, made the changes to be green.
Now i have an error i don't understand.

 ```
fatal: unable to access 'https://github.com/odoo/odoo.git/': transfer closed with outstanding read data remaining
The command "travis_install_nightly" failed and exited with 128 during .
```

Can I do something about it ?

2019-02-07 14:36 UTC, rousseldenis commented
> Ok so i check travis, made the changes to be green.
> Now i have an error i don't understand.
> 
> ```
> fatal: unable to access 'https://github.com/odoo/odoo.git/': transfer closed with outstanding read data remaining
> The command "travis_install_nightly" failed and exited with 128 during .
> ```
> Can I do something about it ?

I see that in other PR's too. Will ask. Maybe related to 8.0 branch

2019-02-07 14:40 UTC, quentinDupont commented
> I see that in other PR's too. Will ask. Maybe related to 8.0 branch
Thank you !

2019-02-07 15:35 UTC, quentinDupont commented
Ok Travis went well this time. I squash my commits. Everything is fine now :)

2019-02-07 15:46 UTC, rousseldenis approved these changes
Code review

2019-04-19 16:34 UTC, tbaden approved these changes
code review

@Nikul-Chaudhary the requested changes were done

2019-04-19 17:20 UTC, merged