[10.0][FIX] stock_picking_line_sequence
OCA/stock-logistics-workflow pull request #521
Opened 2019-04-11 07:00 UTC by ageficent

Fix for stock_picking_line_sequence:

* Sequence was not propagated correctly from procurement to picking
* Remove sequence resetting in write method that was preventing correct propagation of sequences from sales orders.
* Prevent sequence resetting on picking copy.

cc ~ @aheficent @bjeficent

2019-04-11 08:58 UTC, rousseldenis requested changes
Code review. LGTM

Could you update module version?

2019-04-11 09:13 UTC, ageficent commented
> Code review. LGTM
> 
> Could you update module version?

Done :+1:

2019-04-11 09:53 UTC, rousseldenis approved these changes

2019-04-11 11:49 UTC, AaronHForgeFlow approved these changes
:+1: Tested locally. Thank you!

2019-04-15 16:16 UTC, LoisRForgeFlow approved these changes

2019-04-15 16:16 UTC, merged