[IMP] stock_batch_picking: implement use case of tranfers using lot
OCA/stock-logistics-workflow pull request #531
Opened 2019-06-06 11:19 UTC by nicomacr

In the case if you want to transfer products by a lot and hasn't availability in a quant with this lot,
find a quantity by a quant with not lot and with quantity availability.

This is because odoo do the same in this case like see in this https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move_line.py#L437

More details in this [video](https://drive.google.com/file/d/1Vd8i5CxzJCiBXp-XIN1BVQu0scS1Qu4H/view)

2019-06-06 11:32 UTC, rousseldenis commented
@carlosdauden Could you add a test for that case ?

2019-06-07 16:28 UTC, nicomacr commented
> @nicomacr Could you add a test for that case ?

It's Done!

2019-06-10 14:26 UTC, nicomacr commented
@carlosdauden could you review this PR?
Thanks

2019-06-10 14:28 UTC, zaoral approved these changes

2019-06-10 14:32 UTC, sotolucas approved these changes

2019-06-11 09:01 UTC, LoisRForgeFlow approved these changes
Thanks for the detailed explanaition and the tests :+1:

2019-06-11 09:01 UTC, lreficent commented
@pedrobaeza @carlosdauden anything against this?

2019-06-11 09:07 UTC, carlosdauden approved these changes

2019-06-11 09:08 UTC, pedrobaeza requested changes

2019-06-11 09:08 UTC, pedrobaeza commented on stock_no_negative/models/stock_quant.py
> +                    else:
No need of this else and thus you reduce the diff.

2019-06-11 09:09 UTC, rousseldenis requested changes
LGTM. Code review.

@nicomacr Please change module version

2019-06-11 09:09 UTC, rousseldenis commented on stock_no_negative/models/stock_quant.py
> +                            " lot '%s'") % quant.lot_id.name_get()[0][1]
Why not using display_name ?

2019-06-11 11:33 UTC, nicomacr commented
@rousseldenis @pedrobaeza already apply those changes to this PR.

Thanks

2019-06-11 13:50 UTC, pedrobaeza approved these changes

2019-06-11 13:56 UTC, rousseldenis approved these changes

2019-06-11 13:59 UTC, merged