[13.0][MIG] stock_picking_back2draft
OCA/stock-logistics-workflow pull request #602
Opened 2019-12-25 07:38 UTC by ps-tubtim

2020-02-20 10:33 UTC, acsonefho requested changes
Tested and works properly.
Just few minor changes.
Thanks for the migration!

2020-02-20 10:33 UTC, acsonefho commented on stock_picking_back2draft/__manifest__.py
> +    "website": "https://www.agilebg.com",
It should be:
`"website": "https://github.com/OCA/stock-logistics-workflow",`

2020-02-20 10:33 UTC, acsonefho commented on stock_picking_back2draft/models/stock.py
> +    _inherit = "stock.move"
Can you split into 2 files please? 1 file per `Model`

2020-03-16 02:24 UTC, ps-tubtim commented
@acsonefho Thank you for review.

2020-06-05 08:43 UTC, CasVissers-360ERP approved these changes
Functional review

2020-06-05 09:09 UTC, acsonefho approved these changes

2020-06-05 10:35 UTC, ps-tubtim commented
/ocabot merge nobump

2020-06-05 10:52 UTC, merged