[12.0] Add module product_expiry_stock_move_line_use_date
OCA/stock-logistics-workflow pull request #605
Opened 2020-01-02 12:59 UTC by grindtildeath

This module extends the functionality of `product_expiry` module in order to
allow users to enter a 'Best before Date' on the stock move line before the lot
creation.

2020-01-02 15:22 UTC, rousseldenis commented
@grindtildeath Is this WIP ?

2020-01-02 16:29 UTC, grindtildeath commented
@rousseldenis It wasn't supposed to be :laughing: 

As usual there can still be some fixes coming in the next few days...

2020-01-03 08:00 UTC, Tonow-c2c approved these changes
LGTM

2022-02-09 14:56 UTC, rousseldenis commented
@grindtildeath I think few days have passed :smile: What's the status of this?

2022-02-28 16:50 UTC, grindtildeath commented
@rousseldenis I didn't had to do any other fixes since then, so I guess the module works well for the customer using it. :sweat_smile: 
IMO PR could be merged if there are enough reviews.

2022-03-07 08:09 UTC, rousseldenis requested changes
Code erview. Minor comment

2022-03-07 08:09 UTC, rousseldenis commented on product_expiry_stock_move_line_use_date/models/stock_move.py
> +class StockMoveLine(models.Model):
Please split one model per file

2022-08-14 12:40 UTC, closed without merging