[12.0][MIG] product_cost_price_avco_sync: Migration to 12.0
OCA/stock-logistics-workflow pull request #610
Opened 2020-01-16 11:26 UTC by carlosdauden

@Tecnativa TT20698

2020-01-17 08:31 UTC, sergio-teruel approved these changes

2020-01-22 17:22 UTC, Tardo requested changes

2020-01-22 17:22 UTC, Tardo commented on product_cost_price_avco_sync/models/stock_move.py
> +            PriceHistory.create({
I think that here can use "multi style"

2020-01-22 17:53 UTC, carlosdauden commented on product_cost_price_avco_sync/models/stock_move.py
> +            PriceHistory.create({
Changes done

2020-02-11 12:44 UTC, pedrobaeza approved these changes

2020-02-11 12:44 UTC, pedrobaeza commented
/ocabot merge

2020-02-11 12:56 UTC, pedrobaeza commented
/ocabot merge

2020-02-11 13:08 UTC, merged