[WIP][MIG][13.0] stock_picking_show_return: Migration to v13.0
OCA/stock-logistics-workflow pull request #616
Opened 2020-01-28 20:13 UTC by sergio-teruel

TT21693

2020-01-29 18:13 UTC, Tardo requested changes

2020-01-29 18:13 UTC, Tardo commented on stock_picking_show_return/readme/CONTRIBUTORS.rst
> +* Ruchir Shukla <ruchir@bizzappdev.com>
Add yourself here...

2020-01-29 18:13 UTC, Tardo commented on stock_picking_show_return/readme/USAGE.rst
> +   :target: https://runbot.odoo-community.org/runbot/154/11.0
:fire: This will be added by the script

2020-01-29 18:16 UTC, carlosdauden approved these changes

2020-01-31 08:48 UTC, carlosdauden approved these changes
Code LGTM

2020-01-31 08:52 UTC, rousseldenis commented
@sergio-teruel I think pre-commit is not happy

2020-01-31 08:55 UTC, sergio-teruel commented
@rousseldenis jajajajaja the pre commit is driving me crazy!!!

2020-01-31 08:59 UTC, rousseldenis commented
> @rousseldenis jajajajaja the pre commit is driving me crazy!!!

When you are used to, it becames transparent and you don't think about formatting anymore :-)

2020-02-03 15:43 UTC, sergio-teruel commented
@rousseldenis changes done

2020-02-07 12:46 UTC, rousseldenis approved these changes
Code review

2020-02-07 14:36 UTC, pedrobaeza commented
/ocabot merge

2020-02-07 14:56 UTC, merged