[WIP][MIG][13.0] stock_picking_sale_order_link: Migration to v13.0
OCA/stock-logistics-workflow pull request #621
Opened 2020-02-06 16:39 UTC by sergio-teruel

TT21692

2020-02-06 23:37 UTC, carlosdauden requested changes

2020-02-06 23:37 UTC, carlosdauden commented on stock_picking_sale_order_link/tests/test_stock_picking_sale_order_link.py
> +            {"name": "Customer - test", "customer": True}
customer field removed in v13

2020-02-19 18:04 UTC, sergio-teruel commented
@carlosdauden changes done!!

2020-02-20 18:32 UTC, carlosdauden approved these changes

2020-02-25 13:09 UTC, pedrobaeza approved these changes

2020-02-25 13:10 UTC, pedrobaeza commented
/ocabot merge

2020-02-25 13:26 UTC, merged