[IMP] stock_picking_invoice_link: Allow invoice lines linked with more than one stock move
OCA/stock-logistics-workflow pull request #623
Opened 2020-02-07 22:12 UTC by sergio-teruel

This commit is forwardport from a v11.0 commit (https://github.com/OCA/stock-logistics-workflow/commit/c087ce6c20cade3823f4b8ae985b0fab51bfe519)

cc @Tecnativa

2020-03-05 11:50 UTC, sergio-teruel commented
@carlosdauden Can you review please??

2020-03-05 11:56 UTC, manuelcalerosolis approved these changes
I have tested the functionality of the module, and everything works correctly.

2020-03-05 13:29 UTC, pedrobaeza requested changes
Indeed we need here a migration script for converting one2many to many2many, but we have to do it conditionally (you can detect if the m2m table is empty as condition), as if not, when migrating from v11 with the upgrade module 11.0.2.0.0 to v12, there will be duplicated data.

2020-03-05 14:12 UTC, rousseldenis requested changes
Code review. Indeed as @pedrobaeza this needs a migration script.

2020-03-05 14:12 UTC, rousseldenis commented on stock_picking_invoice_link/models/sale_order.py
> +        if qty < 0.0:
Please use float_compare()

2020-03-05 15:50 UTC, carlosdauden commented
I don't understand...

Are you see this?:
https://github.com/OCA/stock-logistics-workflow/blob/11.0/stock_picking_invoice_link/migrations/11.0.2.0.0/post-migrate.py#L6-L9

This field is changed in v11.
The instance must be updated before major version migration

2020-03-05 15:51 UTC, pedrobaeza commented
@carlosdauden the migration script is needed for those with version 12.0.1.0.0, but the migration should check for avoiding applying twice for those migrating from 11.0.2.0.0. Let's have a meeting if you still don't understand.

2020-03-05 15:54 UTC, carlosdauden commented
Ok, sorry.
I thought this was the PR migration module to v12...

2020-03-20 18:06 UTC, sergio-teruel commented
@pedrobaeza Added migration script
@rousseldenis Changes done!

2020-03-31 06:56 UTC, carlosdauden approved these changes

2020-03-31 06:58 UTC, carlosdauden commented
@pedrobaeza @rousseldenis Can you check?

2020-03-31 07:17 UTC, rousseldenis approved these changes
Code review

2020-03-31 07:17 UTC, pedrobaeza approved these changes

2020-03-31 07:17 UTC, pedrobaeza commented
/ocabot merge

2020-03-31 07:36 UTC, merged