[12.0][ADD] stock_picking_return_restricted_qty: Don't allows you to return more quantity than delivered
OCA/stock-logistics-workflow pull request #636
Opened 2020-03-10 12:44 UTC by CarlosRoca13

cc @Tecnativa TT22466

2020-03-13 11:18 UTC, sergio-teruel requested changes

2020-03-13 11:18 UTC, sergio-teruel commented on stock_picking_return_restricted_qty/README.rst
> +#. Create an outgoing or an internal picking.
Please take an account incoming pickings.

2020-03-13 11:18 UTC, sergio-teruel commented on stock_picking_return_restricted_qty/__manifest__.py
> +    "author": "Tecnativa," "Odoo Community Association (OCA)",
```suggestion
    "author": "Tecnativa, Odoo Community Association (OCA)",
```

2020-03-13 11:18 UTC, sergio-teruel commented on stock_picking_return_restricted_qty/__manifest__.py
> +    "data": [],
Remove empty dictionary key

2020-03-13 11:18 UTC, sergio-teruel commented on stock_picking_return_restricted_qty/wizard/stock_picking_return.py
> +        return_line = self.env['stock.return.picking.line']
Add  a comment explaing what are you doing

2020-03-16 08:37 UTC, CarlosRoca13 commented
@sergio-teruel Changes done!

2020-03-17 16:08 UTC, manuelcalerosolis approved these changes
Code Review: it's ok
Functional Review : It's Ok (test localy)

2020-03-17 16:08 UTC, manuelcalerosolis commented on stock_picking_return_restricted_qty/readme/CONTRIBUTORS.rst
> +* Carlos Roca <carlos.roca@tecnativa.com>
Write your name under a link to the Tecnativa website like it is here
https://github.com/OCA/web/blob/12.0/web_decimal_numpad_dot/readme/CONTRIBUTORS.rst

2020-03-18 08:27 UTC, CarlosRoca13 commented
@manuelcalerosolis Changes done!

2020-04-28 09:16 UTC, rafaelbn approved these changes
Functionally tested in runbot :+1: 

@sergio-teruel last review please

2020-04-28 14:07 UTC, sergio-teruel approved these changes

2020-04-28 14:14 UTC, pedrobaeza commented
/ocabot merge nobump

2020-04-28 14:33 UTC, merged