[FIX] stock_request: CI random fails
OCA/stock-logistics-workflow pull request #662
Opened 2020-05-27 09:02 UTC by chienandalu

When the CI is very fast, the moves could have the same datetime, so the
date asc order would not work as expected

cc @Tecnativa TT24083

2020-05-27 11:29 UTC, HaraldPanten approved these changes
small [FIX]. Seems to be OK

2020-05-27 11:32 UTC, pedrobaeza requested changes
Can't you write only once in `setUp`? You should also a comment before that lines saying why you do that, or migrating the module in the future these lines will be removed as useless.

2020-05-28 05:15 UTC, chienandalu commented
> Can't you write only once in setUp? 

What do you mean?

2020-05-28 07:22 UTC, pedrobaeza commented
You are setting several times the date in 4 places. Can you reduce this to once (maybe having good data in `setUp`/`setUpClass`)?

2020-08-12 17:19 UTC, pedrobaeza commented
@chienandalu any news about this?

2020-08-13 05:30 UTC, chienandalu commented
Sorry. The patch is ugly, but the thing here is that the `date` of the `stock.move.line` is forced to `now()`: https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move_line.py#L454 so when the test go very fast they get done in the same second, so the expected sort in the test won't behave well. In real life, this is not issue an issue, as it's quite improbable an if it happend it wouldn't be a problem at all.

2020-08-13 06:17 UTC, rousseldenis commented
> Sorry. The patch is ugly, but the thing here is that the `date` of the `stock.move.line` is forced to `now()`: https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move_line.py#L454 so when the test go very fast they get done in the same second, so the expected sort in the test won't behave well. In real life, this is not issue an issue, as it's quite improbable an if it happend it wouldn't be a problem at all.

You can maybe init the date in a variable at the beginning of setupClass and reuse it.

Usually, when dates are important in tests, the good way is mocking fields.Datetime.now()

2020-08-13 06:21 UTC, rousseldenis commented
There is also the excellent library to do that : https://pypi.org/project/freezegun/

2020-08-13 06:27 UTC, chienandalu commented
> You can maybe init the date in a variable at the beginning of setupClass and reuse it.
> Usually, when dates are important in tests, the good way is mocking fields.Datetime.now()
> There is also the excellent library to do that : https://pypi.org/project/freezegun/

@rousseldenis Good to know, but aren't we overcomplicating a simple solution? A code comment is needed indeed to clarify anyway :sweat_smile:

2020-08-13 06:32 UTC, rousseldenis commented
> > You can maybe init the date in a variable at the beginning of setupClass and reuse it.
> > Usually, when dates are important in tests, the good way is mocking fields.Datetime.now()
> > There is also the excellent library to do that : https://pypi.org/project/freezegun/
> 
> @rousseldenis Good to know, but aren't we overcomplicating a simple solution? A code comment is needed indeed to clarify anyway

It was an informative comment :smiley: here, just put the date at the beginning and reuse it.

2020-08-13 10:47 UTC, chienandalu commented
Thanks. I think is neater now :)

2020-08-13 14:46 UTC, pedrobaeza commented
Travis is red

2020-08-14 12:58 UTC, yajo approved these changes

2020-08-14 13:09 UTC, JordiBForgeFlow approved these changes

2020-08-14 14:05 UTC, pedrobaeza approved these changes

2020-08-14 14:06 UTC, pedrobaeza commented
/ocabot merge patch

2020-08-14 14:18 UTC, marcelsavegnago approved these changes

2020-08-14 14:19 UTC, merged