[12.0][ADD] stock_picking_late_activity: new module
OCA/stock-logistics-workflow pull request #699
Opened 2020-08-28 04:51 UTC by ernestotejeda

This module adds a 'scheduled action' that periodically checks that the 'scheduled date' of the pickings belonging to certain 'operation types' is prior to the datetime that these checks are performed. For each of the pickings that meet this condition, an activity will be created indicating that the 'scheduled date' must be updated.
The operation types that will be taken into account are those that you determine by checking a specific checkbox for that.

Configuration:
![Selection_015](https://user-images.githubusercontent.com/38267832/91522560-8cb50c00-e8c8-11ea-934d-7b67aab82280.png)

Activities for late pickings are atomatically created:
![Selection_016](https://user-images.githubusercontent.com/38267832/91522576-950d4700-e8c8-11ea-9359-decf923c193f.png)

cc @Tecnativa TT25212

2020-08-28 04:58 UTC, nikul-serpentcs commented on stock_picking_late_activity/__manifest__.py
> +# Copyright <YEAR(S)> <AUTHOR(S)>
```suggestion
# Copyright 2020 Tecnativa - Ernesto Tejeda

```

2020-08-28 05:01 UTC, ernestotejeda commented on stock_picking_late_activity/__manifest__.py
> +# Copyright <YEAR(S)> <AUTHOR(S)>
Thanks @nikul-serpentcs , change done

2020-08-28 06:56 UTC, pedrobaeza requested changes

2020-08-28 06:56 UTC, pedrobaeza commented on stock_picking_late_activity/__manifest__.py
> +    "development_status": "Stable",
This development status is not correct:
```suggestion
    "development_status": "Production/Stable",
```

2020-08-28 06:56 UTC, pedrobaeza commented on stock_picking_late_activity/data/mail_activity_type_data.xml
> +        <field name="name">Update scheduled date</field>
```suggestion
        <field name="name">Late picking</field>
```

2020-08-28 06:56 UTC, pedrobaeza commented on stock_picking_late_activity/models/stock_picking.py
> +class StockPickingType(models.Model):
Put it in a separate file (it is not a one2many model).

2020-08-28 06:56 UTC, pedrobaeza commented on stock_picking_late_activity/models/stock_picking.py
> +        """ Create an activity for late pickings. """
```suggestion
        """Create an activity for late pickings."""
```

2020-08-28 06:56 UTC, pedrobaeza commented on stock_picking_late_activity/models/stock_picking.py
> +        activity."""
Follow proper PEP257 for docstring
```suggestion
        activity.
        """
```

2020-08-28 06:56 UTC, pedrobaeza commented on stock_picking_late_activity/tests/test_stock_picking_late_activity.py
> +        cls.picking_1 = cls._create_validate_picking(
Picking is not validated in the method AFAIK

2020-08-28 06:56 UTC, pedrobaeza commented on stock_picking_late_activity/tests/test_stock_picking_late_activity.py
> +        )
Check also the user associated to the activity

2020-08-31 14:26 UTC, pedrobaeza commented
Check Travis

2020-08-31 14:28 UTC, rousseldenis commented on stock_picking_late_activity/models/stock_picking.py
> +            ("state", 'not in', ["done", "cancel"]),
Maybe include draft too ?

2020-08-31 16:05 UTC, ernestotejeda commented on stock_picking_late_activity/models/stock_picking.py
> +            ("state", 'not in', ["done", "cancel"]),
done

2020-08-31 16:05 UTC, ernestotejeda commented
Changes done

2020-08-31 16:39 UTC, pedrobaeza approved these changes

2020-09-02 23:20 UTC, bodedra approved these changes
Added minor correction.

Functional reviewed. LGTM :+1:

2020-09-02 23:20 UTC, bodedra commented on stock_picking_late_activity/readme/CONFIGURE.rst
> +#. Find the 'activity type' named 'Update scheduled date'
```suggestion
#. Find the 'activity type' named 'Late picking'
```

2020-09-02 23:22 UTC, marcelsavegnago approved these changes

2020-09-03 13:03 UTC, ernestotejeda commented
@bodedra changes done

2020-09-03 13:29 UTC, pedrobaeza commented
/ocabot merge nobump

2020-09-03 13:54 UTC, merged