[13.0][FIX] stock_picking_sale_order_link: New sale line added to done picking
OCA/stock-logistics-workflow pull request #711
Opened 2020-10-07 11:01 UTC by carlosdauden

if access from picking to sale with smartbutton

@Tecnativa TT26009

2020-10-07 11:08 UTC, pedrobaeza commented on stock_picking_sale_order_link/models/stock_picking.py
> +        return self.with_context(default_picking_id=False).sale_id.get_formview_action()
Better to simply remove the key as others do, as sometimes the inexistence of the key is not the same than having it with False:
```suggestion
        ctx = self.env.context.copy()
        ctx = ctx.pop(default_picking_id, False)
        return self.with_context(ctx).sale_id.get_formview_action()
```

2020-10-07 12:11 UTC, victoralmau requested changes
Exist travis error related to this change (https://travis-ci.org/github/OCA/stock-logistics-workflow/jobs/733630849#L1307), maybe because `sale_id` field may no't be defined (`False` value)
What dou you think about it?

2020-10-07 12:20 UTC, carlosdauden commented
@victoralmau travis error was solved here:
https://github.com/OCA/stock-logistics-workflow/compare/9126e11534374d0f37529004c304def59812890f..1b3c0cb452532e92073dffe03ec8c8470c6b343d

2020-10-07 12:28 UTC, pedrobaeza commented
Sorry for my typo in the suggestion... :cry:

2020-10-08 07:50 UTC, carlosdauden commented
Travis green

2020-10-08 09:53 UTC, pedrobaeza commented
/ocabot merge patch

2020-10-08 10:14 UTC, merged