[13.0][MIG]stock_push_delay
OCA/stock-logistics-workflow pull request #724
Opened 2020-11-04 15:47 UTC by AaronHForgeFlow

Standard migration

@ForgeFlow

2020-11-04 18:41 UTC, rousseldenis requested changes

2020-11-04 18:41 UTC, rousseldenis commented on stock_push_delay/models/stock.py
> +class StockMove(models.Model):
Please split one model per file.

2020-11-04 18:42 UTC, rousseldenis commented
@AaronHForgeFlow Please check pre-commit. development_status key should respect standard values.

2020-11-05 08:11 UTC, AaronHForgeFlow commented
Trying to fix pre-commit here: https://github.com/OCA/stock-logistics-workflow/pull/727

2020-11-06 14:36 UTC, rousseldenis commented
@AaronHForgeFlow Can you check pre-commit. Missing line

2020-11-07 10:56 UTC, rousseldenis approved these changes
Code review.

2020-11-11 11:14 UTC, HviorForgeFlow approved these changes

2020-11-11 11:33 UTC, AaronHForgeFlow commented
Please do not merge this yes, I need to check if a picking with multiple products creates just one single new procurement group, and not one for each product.

2021-03-15 17:26 UTC, AaronHForgeFlow commented
cc @LoisRForgeFlow

2021-05-03 07:56 UTC, hparfr approved these changes

2021-05-03 07:59 UTC, hparfr commented
/ocabot merge nobump

2021-05-03 08:21 UTC, merged