[13.0][ADD] stock_move_line_qty_done_constraint
OCA/stock-logistics-workflow pull request #769
Opened 2021-01-10 18:33 UTC by rousseldenis

2021-01-13 15:36 UTC, yostashiro commented on stock_move_line_qty_done_constraint/models/stock_move_line.py
> +        for rec in self.filtered("picking_id.picking_type_id.qty_done_constraint"):
```suggestion
        for rec in self.filtered("move_id.picking_type_id.qty_done_constraint"):
```
Could be a bit more generic to make it like this if this is a chance of this to be applied on move lines from manufacturing orders?

2021-02-08 14:03 UTC, lmignon commented on stock_move_line_qty_done_constraint/models/stock_picking_type.py
> +    qty_done_constraint = fields.Boolean(
@rousseldenis The name is meaningless... Why not `disallow_reserved_qty_overflows`?

2021-02-08 14:05 UTC, lmignon requested changes
@rousseldenis Thank you. LGTM (Code review). A little comment on the name of the field on the picking_type

2021-02-08 14:05 UTC, lmignon approved these changes
@rousseldenis Thank you. LGTM (Code review). A little comment on the name of the field on the picking_type

2022-05-22 12:39 UTC, closed without merging