[13.0] Add stock_dangerous_goods
OCA/stock-logistics-workflow pull request #854
Opened 2021-06-14 12:12 UTC by mmequignon

This glue module between `stock` and `l10n_eu_product_adr` adds a few utility fields

2021-06-16 09:20 UTC, simahawk requested changes

2021-06-16 09:20 UTC, simahawk commented on stock_dangerous_goods/models/product_product.py
> +    is_lq_product = fields.Boolean(compute="_compute_is_lq_product")
add `help`

2021-06-16 09:20 UTC, simahawk commented on stock_dangerous_goods/models/stock_quant_package.py
> +            )
```suggestion
            record.has_lq_products = record._has_lq_product()

    def _has_lq_product(self):
        for quant in self.quant_ids:
            if quant.product_id.is_lq_product:
                return True
```

2021-06-18 08:02 UTC, TDu commented on stock_dangerous_goods/models/product_product.py
> +    def _compute_is_lq_product(self):
The function needs an `api.depends`

2021-06-18 08:02 UTC, TDu commented on stock_dangerous_goods/models/stock_quant_package.py
> +    def _compute_has_lq_products(self):
Also needs an `api.depends`

2021-06-18 08:02 UTC, TDu commented on stock_dangerous_goods/models/stock_quant_package.py
> +                return True
Would be nicer to return `False` if there is no lq products, instead of relying to the default return value

2021-06-18 08:05 UTC, mmequignon commented on stock_dangerous_goods/models/stock_quant_package.py
> +    def _compute_has_lq_products(self):
No, this fields isn't stored and will be computed every time

2021-06-18 08:07 UTC, mmequignon commented on stock_dangerous_goods/models/product_product.py
> +    def _compute_is_lq_product(self):
Not stored, no need to set an api.depends

2021-06-18 08:14 UTC, TDu commented on stock_dangerous_goods/models/stock_quant_package.py
> +    def _compute_has_lq_products(self):
I would think the `compute` method is also useful for non stored fields. So its value is not recomputed every time it is used, it is still temporarily stored in memory.

2021-06-18 08:14 UTC, simahawk approved these changes
LG, non blocking comments on depends. Please squash on your next push.

2021-06-18 08:14 UTC, simahawk commented on stock_dangerous_goods/models/stock_quant_package.py
> +    def _compute_has_lq_products(self):
Actually depends is not just for stored field. It makes sure cache is invalidated where already computed.
It also documents on which fields you depend on functionally.
So, not mandatory, good to have.

2021-06-18 09:26 UTC, sebalix commented on stock_dangerous_goods/models/product_product.py
> +    def _compute_is_lq_product(self):
`api.depends` is not used only when `store=True`, computed fields also act as onchange, here if I tick the `is_dangerous` field on the form it's better to see the `is_lq_product` field updated on the fly, for that you need to define an `api.depends`.

2021-06-18 12:55 UTC, mmequignon commented
@TDu @sebalix I updated my PR.

2021-06-18 15:47 UTC, sebalix approved these changes

2021-07-02 09:48 UTC, rousseldenis commented
Just one remark, I would have named it l10n_eu_stock_dangerous_goods as it is not a 'l10n_eu' agnostic module.

2021-07-26 17:56 UTC, dreispt commented
Travis is red.

2021-08-19 08:49 UTC, simahawk commented
```
----------

FAIL: TestStockValuationLayerUsage.test_02_drop_ship

Traceback (most recent call last):

  File "/home/travis/build/OCA/stock-logistics-workflow/stock_valuation_layer_usage/tests/test_stock_valuation_layer_usage.py", line 294, in test_02_drop_ship

    self.assertEquals(balance_grni, -10.0)

AssertionError: 0 != -10.0
```
https://app.travis-ci.com/github/OCA/stock-logistics-workflow/jobs/532510229#L1971

no time to solve it now :cry:

2021-08-19 08:51 UTC, simahawk commented
NOTE: I made some unrelated changes to boost some test classes

2021-08-20 09:59 UTC, dreispt commented
/ocabot merge nobump

2021-09-09 13:46 UTC, simahawk commented
@JordiBForgeFlow hola, could you check this failing test? https://app.travis-ci.com/github/OCA/stock-logistics-workflow/jobs/535992180#L1874 There's no change in this PR that affects it.

I've tried w/ and without this module or its dependencies. Nothing. The test was failing even before I refactored its setup to use setUpClass of course. 

The issue seems caused by the lack of AML found for the product.

2021-09-14 06:50 UTC, mmequignon commented
> @JordiBForgeFlow hola, could you check this failing test? https://app.travis-ci.com/github/OCA/stock-logistics-workflow/jobs/535992180#L1874 There's no change in this PR that affects it.
> 
> I've tried w/ and without this module or its dependencies. Nothing. The test was failing even before I refactored its setup to use setUpClass of course.
> 
> The issue seems caused by the lack of AML found for the product.

I don't know how this module tests can run correctly, since it uses `product.template.invoice_policy` which is introduced by the `sale` module, on which it does not depends.

2021-09-14 08:50 UTC, simahawk commented
> > @JordiBForgeFlow hola, could you check this failing test? https://app.travis-ci.com/github/OCA/stock-logistics-workflow/jobs/535992180#L1874 There's no change in this PR that affects it.
> > I've tried w/ and without this module or its dependencies. Nothing. The test was failing even before I refactored its setup to use setUpClass of course.
> > The issue seems caused by the lack of AML found for the product.
> 
> I don't know how this module tests can run correctly, since it uses `product.template.invoice_policy` which is introduced by the `sale` module, on which it does not depends.
> I'm unable to run `stock_valuation_layer_usage` when installed alone.

I fixed it here https://github.com/OCA/stock-logistics-workflow/pull/854/commits/9cd0fe5fb3d24b45b1d6882423ad4d63ede10767

You can run tests if you reset hard on this branch version ;)

2021-09-15 11:21 UTC, simahawk commented
FTR a test w/out all the tests improvements has been made here https://github.com/OCA/stock-logistics-workflow/pull/887

2021-10-07 13:37 UTC, TDu approved these changes

2021-10-18 10:05 UTC, rousseldenis commented
@simahawk @mmequignon What's the status of this concerning tests ?

2021-10-18 14:07 UTC, simahawk commented
> @simahawk @mmequignon What's the status of this concerning tests ?

status is: no time to get back to it so far :sob: 

We'll have to do it soon though. But we are facing issue on v14 too because of the refactoring of the base module.... we'll see :man_shrugging:

2022-07-11 09:45 UTC, simahawk commented
@mmequignon pls try to get back to this when you have time :pray:

2022-10-10 07:21 UTC, rousseldenis commented
@mmequignon

2022-10-10 07:21 UTC, rousseldenis commented
/ocabot rebase

2023-01-20 09:53 UTC, rousseldenis commented
@mmequignon Could you rebase ?

2023-04-21 09:02 UTC, bosd commented
ping @mmequignon

2023-05-19 07:56 UTC, rousseldenis commented
@mmequignon

2023-05-19 13:47 UTC, mmequignon commented
sorry, totally forgot about that...

2023-09-22 03:58 UTC, bosd commented
> @mmequignon Could you rebase ?

:pray:

2024-01-16 12:55 UTC, rousseldenis commented
@mmequignon What's the status of this ?

2024-06-23 12:34 UTC, closed without merging