[13.0][ADD][WIP] stock_deferred_assign: Add new module
OCA/stock-logistics-workflow pull request #892
Opened 2021-09-17 15:26 UTC by carlosdauden

@Tecnativa TT31143

2021-10-18 07:59 UTC, rousseldenis commented
@carlosdauden Still WIP ?

2021-12-01 08:35 UTC, carlosdauden commented
WIP removed

2021-12-01 10:39 UTC, pedrobaeza requested changes
No daily cron for reassigning stocks?

2021-12-01 10:39 UTC, pedrobaeza commented on stock_deferred_assign/models/stock_move.py
> +        store=True,
This compute will be triggered for all existing moves, so that can be killing when installing the module.

2021-12-01 10:39 UTC, pedrobaeza commented on stock_deferred_assign/models/stock_picking.py
> +        else:
Nitpicking: no need of `else`, just directly `return`

2021-12-01 10:39 UTC, pedrobaeza commented on stock_deferred_assign/models/stock_picking.py
> +    _inherit = "stock.picking.type"
This should be in its own file.

2021-12-01 10:39 UTC, pedrobaeza commented on stock_deferred_assign/models/stock_rule.py
> +            [[("reservation_date", "<=", fields.Date.today())], moves_domain]
Isn't this duplicated discarding with the `action_assign` code of `stock.picking`?

2021-12-01 10:39 UTC, pedrobaeza commented on stock_deferred_assign/readme/DESCRIPTION.rst
> +This module allows
Missing description and usage instructions.

2022-02-09 18:44 UTC, rousseldenis commented
@carlosdauden Could you attend comments ?

2022-07-19 23:05 UTC, carlosdauden commented on stock_deferred_assign/models/stock_picking.py
>              method = picking.picking_type_id.reservation_method
Why picking_type_id.reservation_method has "by_date" in incoming pickings?

2022-10-10 07:47 UTC, rousseldenis commented
@carlosdauden What's the status of this ?

2022-10-10 08:50 UTC, carlosdauden commented
Changes done

2022-10-19 22:14 UTC, carlosdauden commented
@chienandalu can you review?

2022-10-20 06:56 UTC, rousseldenis commented
@carlosdauden @sergio-teruel @pedrobaeza Have you ever looked at this https://github.com/OCA/wms/tree/13.0/stock_available_to_promise_release?

2022-10-20 07:01 UTC, sergio-teruel commented
@rousseldenis No, I didn't know about it.. I'll take a look.

Thanks!!

2022-10-25 14:13 UTC, carlosdauden commented
@rousseldenis  The module you indicate is much more complete and therefore more complex.
The idea of this PR is to practically backport the functionality of odoo in later versions and that this module does not have continuity.

The fields created by this module match with core fields to avoid migration scripts:
https://github.com/odoo/odoo/blob/08f53ffa30479cfb452ebaed61b42655eb0e6a95/addons/stock/models/stock_move.py#L175
https://github.com/odoo/odoo/blob/c02b1986ccda6666b23fe75bf79adae8ac51de63/addons/stock/models/stock_picking.py#L72
https://github.com/odoo/odoo/blob/c02b1986ccda6666b23fe75bf79adae8ac51de63/addons/stock/models/stock_picking.py#L76

2022-12-31 17:11 UTC, pedrobaeza approved these changes

2023-05-07 16:13 UTC, rvalyi approved these changes

2023-05-07 16:45 UTC, pedrobaeza commented
/ocabot merge nobump

2023-05-07 17:01 UTC, merged