[ADD] Add new module sale_order_deliverable_rate
OCA/stock-logistics-workflow pull request #966
Opened 2022-02-09 13:43 UTC by mathieuOdobescu

This module adds a deliverable rate to a sale order. The deliverable rate is use to know (in percentage) how much of the order the stock can satisfy it.

2022-02-09 14:36 UTC, acsonefho requested changes

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/models/sale_order.py
> +        lines = self.env["sale.order.line"].search([("qty_to_ship", ">=", 0)])
You can not search on no-stored field (cfr `sale.order.line` model).

And if you can use a more restrictive `domain`, it should be better for perf.

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/models/sale_order_line.py
> +                rec.deliverable_rate = 100 if rate >= 1 else rate * 100
More readable like this:
`rec.deliverable_rate = min(100, rate * 100)`

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/tests/test_sale_order.py
> +        so = self.create_basic_so(self.array_products[:1])
You're creating a sale order into every test (except one). So best practice is to create it once during `setUpClass()`.
But you can let it into a dedicated function.

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/tests/test_sale_order_line.py
> +    def _update_stock(cls, product, qty):
As there are some shared function/code into your 2 tests files, you have to create a `CommonClass`.

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/views/sale_order.xml
> +        <field name="inherit_id" ref="sale.view_order_form" />
Missing priority.
`<field name="priority" eval="90" />`

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/views/sale_order.xml
> +        <field name="inherit_id" ref="sale.view_order_tree" />
Missing priority.
`<field name="priority" eval="90" />`

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/views/sale_order.xml
> +        <field name="inherit_id" ref="sale.view_sales_order_filter" />
Missing priority.
`<field name="priority" eval="90" />`

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/__manifest__.py
> +    "depends": ["sale_stock", "product"],
Useless `product` depends. Already in `sale_stock`. Not bad but useless.

2022-02-09 14:36 UTC, acsonefho commented on sale_order_deliverable_rate/models/sale_order_line.py
> +    @api.depends("product_uom_qty", "qty_delivered", "qty_to_ship")
You can add `product_id` into your depends as you're using it.
But I don't know why you have `product_uom_qty` as you don't use it at all.

2022-02-17 08:59 UTC, acsonefho approved these changes
Code LGTM

2022-02-23 16:31 UTC, rousseldenis approved these changes

2022-03-02 06:42 UTC, acsonefho requested changes

2022-03-02 06:42 UTC, acsonefho commented on sale_order_deliverable_rate/tests/test_sale_order.py
> +        orders = self.env["sale.order"].search([("deliverable_rate", "<", 100)])
Your test is really not relevant... You must be more precise

2022-03-02 15:04 UTC, acsonefho requested changes
Minor changes

2022-03-02 15:04 UTC, acsonefho commented on sale_order_deliverable_rate/tests/test_sale_order.py
> +        self.assertTrue(self.so_one_line in orders)
`self.assertIn(self.so_one_line, orders)`

2022-03-02 15:04 UTC, acsonefho commented on sale_order_deliverable_rate/tests/test_sale_order.py
> +        self.assertFalse(self.so_one_line in orders)
Same remark here

2022-03-02 15:22 UTC, acsonefho approved these changes
Code LGTM

2022-03-10 06:24 UTC, Cedric-Pigeon commented on sale_order_deliverable_rate/models/sale_order.py
> +    def order_line_need_delivery(self):
a better name would be "_get_order_lines_to_ship"

2022-03-10 07:00 UTC, Cedric-Pigeon commented on sale_order_deliverable_rate/models/sale_order.py
> +        compute="_compute_order_line_need_delivery", store=False
compute method must contain field name. "_compute_no_order_line_need_delivery"
"nb_" would be better to understand than "no_"

2022-03-10 07:18 UTC, Cedric-Pigeon commented on sale_order_deliverable_rate/models/sale_order.py
> +            lambda line: line.product_id.type == "product" and line.qty_to_ship > 0
add "not line.display_type" to exclude sections and note lines

2022-03-10 07:20 UTC, Cedric-Pigeon commented on sale_order_deliverable_rate/models/sale_order.py
> +        orders = lines.mapped("order_id")
use a read-group for better performances:

order_data = self.env["sale.order.line"].read_group([("qty_to_ship", ">=", 0)], ["qty_to_ship"], ["order_id"])
order_ids = [data['order_id'][0] for data in order_data]
orders = self.browse(order_ids)

2022-04-18 10:02 UTC, dreispt commented
/ocabot merge nobump

2022-04-18 10:34 UTC, merged